### DISCUSSION TITLE
Can't find certificate in RTSPS with docker

### DISCUSSION THREAD

**Discussion by RTae** [bluenviron/mediamtx#1001] [Questions]
Hi, I use rtsp-simple-server with docker with SSL certificate by mounting certificate folder in docker volumes, but the server could find the certificate. Would someone help me to solve this problem?

*Error log*
```
2022/06/23 01:07:00 INF [RTSP] listener opened on :8554 (TCP)
2022/06/23 01:07:00 ERR open server.crt: no such file or directory
2022/06/23 01:07:00 INF [RTSP] listener is closing
2022/06/23 01:07:00 INF waiting for external commands
```

*Docker-compose*
```
version: '3.8'
networks:
  test_net:
    driver: bridge

services:
  mock_rtsp_server:
    image: aler9/rtsp-simple-server:latest
    container_name: rtsp.$DOMAIN
    environment:
      TZ: Asia/Bangkok
      RTSP_PROTOCOLS: tcp
      RTSP_READBUFFERCOUNT: 1024
      RTSP_READBUFFERSIZE: 4096
    networks:
      - test_net
    volumes:
      - ./rtsp-simple-server.yml:/rtsp-simple-server.yml
      - ./cer/server.key:/server.key:ro
      - ./cer/server.crt:/server.crt:ro
    ports:
      - 8554:8554
```

*rtsp-simple-server.yml*
```
###############################################
# General parameters

# Sets the verbosity of the program; available values are "error", "warn", "info", "debug".
logLevel: info
# Destinations of log messages; available values are "stdout", "file" and "syslog".
logDestinations: [stdout]
# If "file" is in logDestinations, this is the file which will receive the logs.
logFile: rtsp-simple-server.log

# Timeout of read operations.
readTimeout: 10s
# Timeout of write operations.
writeTimeout: 10s
# Number of read buffers.
# A higher number allows a wider throughput, a lower number allows to save RAM.
readBufferCount: 512

# HTTP URL to perform external authentication.
# Every time a user wants to authenticate, the server calls this URL
# with the POST method and a body containing:
# {
#   "ip": "ip",
#   "user": "user",
#   "password": "password",
#   "path": "path",
#   "action": "read|publish"
#   "query": "url's raw query"
# }
# If the response code is 20x, authentication is accepted, otherwise
# it is discarded.
externalAuthenticationURL:

# Enable the HTTP API.
api: no
# Address of the API listener.
apiAddress: 127.0.0.1:9997

# Enable Prometheus-compatible metrics.
metrics: no
# Address of the metrics listener.
metricsAddress: 127.0.0.1:9998

# Enable pprof-compatible endpoint to monitor performances.
pprof: no
# Address of the pprof listener.
pprofAddress: 127.0.0.1:9999

# Command to run when a client connects to the server.
# This is terminated with SIGINT when a client disconnects from the server.
# The following environment variables are available:
# * RTSP_PORT: server port
runOnConnect:
# Restart the command if it exits suddenly.
runOnConnectRestart: no

###############################################
# RTSP parameters

# Disable support for the RTSP protocol.
rtspDisable: no
# List of enabled RTSP transport protocols.
# UDP is the most performant, but doesn't work when there's a NAT/firewall between
# server and clients, and doesn't support encryption.
# UDP-multicast allows to save bandwidth when clients are all in the same LAN.
# TCP is the most versatile, and does support encryption.
# The handshake is always performed with TCP.
protocols: [tcp]
# Encrypt handshake and TCP streams with TLS (RTSPS).
# Address of the TCP/RTSP listener. This is needed only when encryption is "no" or "optional".
rtspAddress: :8554
# Address of the TCP/TLS/RTSPS listener. This is needed only when encryption is "strict" or "optional".
rtspsAddress: :8322
encryption: "optional"
serverKey: server.key
serverCert: server.crt
# Authentication methods.
authMethods: [basic, digest]

# Path parameters

# These settings are path-dependent, and the map key is the name of the path.
# It's possible to use regular expressions by using a tilde as prefix.
# For example, "~^(test1|test2)$" will match both "test1" and "test2".
# For example, "~^prefix" will match all paths that start with "prefix".
# The settings under the path "all" are applied to all paths that do not match
# another entry.
paths:
  all:
    # Source of the stream. This can be:
    # * publisher -> the stream is published by a RTSP or RTMP client
    # * rtsp://existing-url -> the stream is pulled from another RTSP server / camera
    # * rtsps://existing-url -> the stream is pulled from another RTSP server / camera with RTSPS
    # * rtmp://existing-url -> the stream is pulled from another RTMP server
    # * http://existing-url/stream.m3u8 -> the stream is pulled from another HLS server
    # * https://existing-url/stream.m3u8 -> the stream is pulled from another HLS server with HTTPS
    # * redirect -> the stream is provided by another path or server
    source: publisher

    # If the source is an RTSP or RTSPS URL, this is the protocol that will be used to
    # pull the stream. available values are "automatic", "udp", "multicast", "tcp".
    sourceProtocol: automatic

    # Tf the source is an RTSP or RTSPS URL, this allows to support sources that
    # don't provide server ports or use random server ports. This is a security issue
    # and must be used only when interacting with sources that require it.
    sourceAnyPortEnable: no
```
