### DISCUSSION TITLE
How to proxy rtmp to llhls， from origin to edge server

### DISCUSSION THREAD

**Discussion by fastfading** [bluenviron/mediamtx#1008] [Questions]
can we proxy in this mode ?
[Publisher] --rtmp--> [Origin] --??--> [Edge] --llhls--> [Player] 
Origin Server get original stream
Edge Server  are many ,  used for for load balance. and may deployed in customer site .

How can we do this ?
which protocol should be used between  [Origin] --??--> [Edge]

**Comment by aler9** [comment]
Hello, you can do this by instantiating an arbitrary number of edge servers with this configuration:

```yml
paths:
  stream:
    source: rtsp://origin-ip:8554/stream
    sourceProtocol: tcp
```

The protocol between Origin and edge servers is RTSP.

[a comment by an automated account is not shown]
