### DISCUSSION TITLE
Invalid credentials in RTMP

### DISCUSSION THREAD

**Discussion by Killers0992** [bluenviron/mediamtx#1015] [Questions]
I am doing something wrong with publishing RTMP and using credentials? because its always invalid

My URL
rtmp://myuser:mypass@localhost:1935/movienight

```
paths:
  movienight:
    publishUser: myuser
    publishPass: mypass
```
