### DISCUSSION TITLE
How to reduce latency of a forwarded live stream

### DISCUSSION THREAD

**Discussion by caecilius7** [bluenviron/mediamtx#1021] [Questions]
Hello,

I have two rtsp-simple-server servers, both currently running in my Windows 10 localhost (server-1 and server-2).

server-1 is expected to pull a stream from an IP camera and forward it to server-2.
Basically, I'm doing this by:
```
paths:
  myCam:
    source: rtsp://admin:admin@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0
    sourceProtocol: tcp
    runOnReady: ffmpeg -hide_banner -re -an -rtsp_transport tcp -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -r 10 -preset ultrafast -tune zerolatency -rtsp_transport tcp -f rtsp rtsp://localhost:<server-2_port>/$RTSP_PATH
    runOnReadyRestart: yes
```

<br>
Here's my IP camera ffprobe (no audio): <br>

> Input #0, rtsp, from 'rtsp://admin:admin@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0':
>   Metadata:
>     title           : Media Server
>   Duration: N/A, start: 1.500000, bitrate: N/A
>   Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720, 10 fps, 100 tbr, 90k tbn, 20 tbc
> 

<br>
  
On the other side, server-2 is simply a publisher:<br>

```
paths:
  myCam:
    source: publisher
    sourceProtocol: tcp
```

<br>

_And this is working fine, except for latency part._

<br>

In fact, by both executing
`vlc rtsp://localhost:<server-1_port>/myCam`
and
`vlc rtsp://localhost:<server-2_port>/myCam`

...I can easily notice that server-2 is 2s behind server-1.

<br>

**So, is there a way to reduce/eliminate this latency?**

<br>

As I'm currently running both servers in my localhost, I know this latency cannot be caused by inter-networking issues. But I still can foresee a few options for improvement:

1) Changing from TCP to UDP
I don't think I can change this because, in my final setup, server-2 will have a public address, traffic will be encrypted between servers and between servers and clients and it may exist NAT/firewall between servers and clients.
But I'm opened to suggestions...

2) Tune the ffmpeg (forward) command
Any suggestions?...

3) Tune the rtsp-simple-server (server-1)
Currently, I'm pulling a source (the IP camera) and, when stream is ready, I'm getting it from ffmpeg and forward it to server-2. This, basically, is a 2-step operation then.
Would it make a difference if I would do it just in one step, something like:
`ffmpeg -hide_banner -re -an -rtsp_transport tcp -i rtsp://admin:admin@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0 -c copy -r 10 -preset ultrafast -tune zerolatency -rtsp_transport tcp -f rtsp rtsp://localhost:<server-2_port>/$RTSP_PATH`
Would this reduce the latency?
In fact, would this be even possible? Since the execution of this command would not be triggered by a stream, how to setup this solution in server-1?
Still in this scenario, would local clients still be able to access the stream locally (e.g., vlc localhost:<server-1_port>/myCam)??

<br>

Other suggestions? Please advise.
Thank you!

[a comment by an automated account is not shown]
