### DISCUSSION TITLE
Make stream publishing itself in app.

### DISCUSSION THREAD

**Discussion by Killers0992** [bluenviron/mediamtx#1024] [Questions]
Its possible to configure rtsp-simple-server to publish stream to x path soo anyone accessing this will see video read from path and anyone else trying joining will see same stream

**Comment by caecilius7** [comment]
If I understood your scenario correctly, you may have 2 options:

1) Use **RunOnInit** to publish your stream  to a path:
In your _rtsp-simple-server.yml_, add to your "paths":

```
myStream:
    source: publisher
    runOnInit: ffmpeg (...) -i "rtsp://(...)camera_ip:camera_port(...)" -codec copy -f rtsp rtsp://your_rtsp_simple_server_ip:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
```

- If you are running _rtsp-simple-server_ in your local machine, your_rtsp_simple_server_ip may be replaced by _localhost_
- Instead of a RTSP camera input you can, for instance, stream a movie stored locally:
  `(...) -re -stream_loop -1 -i "C:\movie.mp4" (...)`
- Access your stream with a client (e.g., VLC), using the URL: `rtsp://your_rtsp_simple_server_ip:8554/myStream`

2) Run an external publish command manually (instead of using runOnInit)
In your rtsp-simple-server.yml, add to your "paths":
```
myStream:
    source: publisher
```

Run in cmd/sh:
`ffmpeg (...) -i "rtsp://(...)camera_ip:camera_port(...)" -codec copy -f rtsp rtsp://your_rtsp_simple_server_ip:$RTSP_PORT`

<br>
Hoped this helped.

[a comment by an automated account is not shown]
