### DISCUSSION TITLE
How to add different watermask to rtsp

### DISCUSSION THREAD

**Discussion by yuyinw** [bluenviron/mediamtx#1056] [Questions]
Hello 
       i  have a question, how to add different watermask (like  client ip ,  client mark )to rtsp ?
       i  try to use ffmpeg to pull rtsp, add watermask, then  push  to local  proxy ,  but the watermask only show the first client info, because of  session.  
       how  can i  add different watermask (like  client ip ,  client mark )to rtsp ?

thank you very much

**Comment by aler9** [comment]
Hello, the problem is that the stream is shared between all clients. You have to make each client connect to a different path, and generate an on-demand stream for each path:

```yml
paths:
  mycamera:
    source: rtsp://my-camera
  client_*:
    runOnDemand: ffmpeg -i rtsp://127.0.0.1:8554/mycamera ... (filters) ... rtsp://localhost:$RTSP_PORT/$RTSP_PATH
```

Each client must connect to `rtsp://ip:8554/client_NUMBER`, for instance: `rtsp://ip:8554/client_123`

[a comment by an automated account is not shown]
