### DISCUSSION TITLE
HLS has no audio when RTSP source is PCM codec

### DISCUSSION THREAD

**Discussion by cmglifep** [bluenviron/mediamtx#1071] [Questions]
Hi, I am not sure if this is my problem. I have a RTSP source (H264 video and PCM audio), it works on RTSP, but no audio on HLS. Is there any settings I can add to rtsp-simple-server.yml to convert the PCM to ACC for HLS, or it is not supported?

Thank you for your time!

**Comment by aler9** [comment]
Hello, HLS only supports the H264 and AAC codecs, you can convert any track you like to these codecs by using `runOnReady` and `ffmpeg`:

```yml
paths:
  mycamera:
    source: rtsp://myurl
    runOnReady: ffmpeg -i rtsp://127.0.0.1:8554/mycamera -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -c:a aac -b:a 160k -f rtsp rtsp://127.0.0.1:8554/hls
  hls:
```

You can then watch the stream by using this URL:

```
http://127.0.0.1:8888/hls
```

[a comment by an automated account is not shown]
