### DISCUSSION TITLE
Can source-on-demand and conversion be combined?

### DISCUSSION THREAD

**Discussion by seranpion** [bluenviron/mediamtx#1178] [Questions] [answered]
Hello.

I am trying to convert a video+audio stream into an audio-only stream.
But I want this save bandwidth with the `sourceOnDemand` mode.

It seems to me that the two features are uncompatible.
Is this true?

If not, how would I achieve this.

This is my paths config so far:

```yaml
 original:
   source: rtsp://someStream
  # If I enable the sourceOnDemand, the second feed fails to work, obviously.
   sourceOnDemand: no
   sourceProtocol: udp
   sourceAnyPortEnable: yes
 audio-only:
   source: publisher
   sourceOnDemand: no
   sourceProtocol: udp
   sourceAnyPortEnable: yes
   runOnInit: ffmpeg -i rtsp://localhost:$RTSP_PORT/original -q:a 0 -map a -f rtsp rtsp://localhost:$RTSP_PORT/audio-only
   runOnInitRestart: yes
```
