### DISCUSSION TITLE
FFmpeg never reconnects.

### DISCUSSION THREAD

**Discussion by Wheemer** [bluenviron/mediamtx#1252] [Questions]
I have one feed being filtered through ffmpeg to convert from 265 to 264 and strip the audio.

Every couple days the feed disappears and never reconnects until I restart rtsp simple server.

Is there anything more that can be done to have rtsp simple server respawn the ffmpeg instance upon failure?

The feed is 24/7 so any drops maybe are just wifi glitches, normally the signal is very strong.

**Comment by aler9** [comment]
Hello, you didn't provide much details, but in order to respawn ffmpeg in case of failure there's either `runOnInitRestart` or you could wrap the command into a bash loop:

```yml
paths:
  mypath:
    runOnInit: bash -c 'while true; do ffmpeg -i .... -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH; sleep 1; done'
```
