### DISCUSSION TITLE
Splitting a quad view stream into 4 streams

### DISCUSSION THREAD

**Discussion by creategui** [bluenviron/mediamtx#1269] [Questions] [answered]
Any suggestions to split a stream that has 4 cameras into 4 streams?  They are laid out in a 2 x 2 format.  Each is 1920x1080.  The combined stream is 3840x2160 but I would like to have 4 separate rtsp endpoints in rtsp-simple-server one fore each camera.

**Comment by aler9** [comment, marked as answer]
Hello, use the `crop` filter of FFmpeg. 

```yml
paths:
  video1:
    runOnInit: ffmpeg -i rtsp://original-stream -filter:v "crop=1920:1080:0:0" -f rtsp -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH

  video2:
    runOnInit: ffmpeg -i rtsp://original-stream -filter:v "crop=1920:1080:1920:0" -f rtsp -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH

  video3:
    runOnInit: ffmpeg -i rtsp://original-stream -filter:v "crop=1920:1080:1920:1080" -f rtsp -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH

  video4:
    runOnInit: ffmpeg -i rtsp://original-stream -filter:v "crop=1920:1080:0:1080" -f rtsp -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH

```

It's a little heavyweight since you'll end up encoding 4 streams, maybe you can try replacing libx264 with nvenc as described in the [ffmpeg wiki](https://trac.ffmpeg.org/wiki/HWAccelIntro).
