### DISCUSSION TITLE
Help Needed - IPCam to HTTP

### DISCUSSION THREAD

**Discussion by RJGill84** [bluenviron/mediamtx#1310] [Questions]
Hello - I must not be doing something correctly. I am not an expert unfortunately but am a fairly technical person. What I'm trying to accomplish is: Taking the RTSP stream from a 4 Channel NVR (individual RTSP streams) and make it available via a web browser inside and outside my home. It seems this program will accomplish that. How do I properly configure the YAML? I'm running Windows 11, using the executable. Thanks in advance for any help!

**Comment by aler9** [comment]
Ingest the streams by using the `source` parameter:

```yml
paths:
  channel1:
    source: rtsp://url-of-channel-one

  channel2:
    source: rtsp://url-of-channel-two

  channel3:
    source: rtsp://url-of-channel-three

  channel4:
    source: rtsp://url-of-channel-four

```

And read them with HLS:

```
http://localhost:8888/channel1
http://localhost:8888/channel2
http://localhost:8888/channel3
http://localhost:8888/channel4
```

[a comment by an automated account is not shown]
