### DISCUSSION TITLE
Multiple paths for rpiCamera

### DISCUSSION THREAD

**Discussion by gallofeliz** [bluenviron/mediamtx#1348] [Questions]
Hello,

At the beginning, I wanted to have root path "/" to the rpiCamera but I did'nt found how. Finally, I thought that I can have paths for differents quality like many ip cameras (no ?). But now, I have the error "ERR: 'rpiCamera' is used as source in two paths ('fhd' and 'ld')".

Does somebody knows how I can have either a root path for rpiCamera (calling rtsp://cam/ to join it) or paths with differents qualities ?

Here my config :
```
paths:
  fhd:
    source: rpiCamera
  hd:
    source: rpiCamera
    rpiCameraMode: 1280:720
  ld:
    source: rpiCamera
    rpiCameraMode: 778:432

rtspAddress: :554
```

Regards,

**Comment by aler9** [comment]
Hello, you can create a secondary stream with a lower resolution by using ffmpeg inside `runOnReady`, as explained in the README:

```yml
paths:
  hd:
    source: rpiCamera
    rpiCameraMode: 1280:720
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -vf scale=320:240 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/sd
    runOnReadyRestart: yes

  sd:
```

The Raspberry Pi can encode a video to H264  at both hardware and software level.
The hardware encoder is already performing the raw video --> h264 hd conversion.
You're left with the software encoder, which will perform the h264 hd --> h264 sd conversion.
I don't know if the Raspberry has the computational capability required to run two instances of ffmpeg at once, but you can try, in order to provide a third stream.

**Reply by gallofeliz** [reply]
Ok thanks, I will see that.

Regards

**Reply by gallofeliz** [reply]
Thanks for your answer. I adapted your answer for https://github.com/gallofeliz/my-own-ip-camera :

```yaml
  fhd:
    source: rpiCamera
    sourceOnDemand: yes
    sourceOnDemandCloseAfter: 1s
  hd:
    runOnDemand: ffmpeg -hide_banner -loglevel error -i rtsp://localhost/fhd -vf scale=1280:720 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost/hd'
```

Both streams endpoints are onDemand to avoid to put cam device as busy (I use it to make stills). Htop shows CPU low with fhd but very high with hd, maybe I will try to improve it trying use of HLS, changing some options, but as the project is mainly just to play (I only need stills ...) it is not urgent. I tested both endpoints and some seconds after I quit my client, the source is closed. So goooood :+1:
