### DISCUSSION TITLE
How to connect multiple RTSP clients to raspberry pi camera?

### DISCUSSION THREAD

**Discussion by adyanth** [bluenviron/mediamtx#1378] [Questions]
I am trying to have multiple clients connect to the RTSP streams whose source is the raspberry pi camera. But only the first client is able to consume the stream and the rest cannot.

What am I missing?

Config: (camera not in legacy mode):

```yaml
paths:
  live:
    source: rpiCamera
    rpiCameraWidth: 1280
    rpiCameraHeight: 720
    rpiCameraMode: 1296:972
    rpiCameraFPS: 30
```

**Comment by adyanth** [comment]
I tried using ffmpeg to stream to this with the camera in legacy mode, but that fails to show any image when using the h264_v4l2m2m codec. Using libx264 works, but is too slow and consumes ~80% CPU making it unusable.

Config (camera in legacy mode):

```yaml
paths:
  all:
    runOnDemand: ffmpeg -f v4l2 -i /dev/video0 -c:v h264_v4l2m2m -preset ultrafast -tune zerolatency  -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnDemandRestart: yes
```
