### DISCUSSION TITLE
Restream to another Server

### DISCUSSION THREAD

**Discussion by DL9EVO** [bluenviron/mediamtx#1434] [Questions]
Hello everybody,

i use the rtsp-simpe-server on my RasPi4 8GB to stream via RTMP from my DJi Drone.

HLS works perfectly with Firefox and Chrome.

Now i want to "restream" the stream to other server (for example to Facebook, Twitch etc) automaticly.

With another RTMP Server i addet "push [url]" in the config file and that works.

Is that possible with that tool too?

Thanks for answering my question.

**Comment by aler9** [comment]
Hello, currently it's possible by using ffmpeg inside `runOnReady`:

```yml
paths:
  mypath:
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f rtmp://my-other-server
```

In the future it will be possible natively, without FFmpeg. Follow issue #981 to track the development.
