### DISCUSSION TITLE
RTMP Proxy/Routing depends on ingest URL or HOST

### DISCUSSION THREAD

**Discussion by eggcho** [bluenviron/mediamtx#1480] [Questions]
Hello,

I want to ask if is it possible to make such type of proxy/routing task in server, to forward ingest RTMP streams to specific server.
My goal is to made server that stays in public network and forward RTMP streams from clients to their specific ingest point in private network. Clients has their own RTMP server (based on nginx) that accepts connections with authentication and I want to forward them their servers.
For example:
Client1 has ingest point in 10.0.1.1 (app1.example.int/live) 
Client2 has ingest point in 10.0.1.2 (app2.example.int/live)
I want to give them single public server with public IP 193.168.0.1 (rtmp.example.com) its possible to make DNS record that point *.rtmp.example.com -> 193.168.0.1
So when Client1 is send stream to rtmp://193.168.0.1/app1 or rtmp://app1.rtmp.example.com/ to forward their request to rtmp://10.0.1.1 or rtmp://app1.example.int/{live} 
The best solution is if ingest point can be rtmp://193.168.0.1/**$var** that forward to rtmp://**$var**.example.int/
or
from ingest rtmp://**$var**.rtmp.example.com -> to dest rtmp://**$var**.example.int/  

Thank you.

**Comment by aler9** [comment]
Hello, in order to forward an incoming RTMP stream to a private server, you can use a publicly-exposed MediaMTX instance with this configuration:

```yml
paths:
  '~stream-(.*?)':
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f flv rtmp://private-rtmp-server:1935/stream-$G1
```

Any stream published to a path that starts with `stream-` will be proxied to a private RTMP server of your choice. You can also create multiple paths in order to proxy to different private servers:

```yml
paths:
  '~stream-to-srv1-(.*?)':
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f flv rtmp://private-rtmp-server-one:1935/stream-$G1
  '~stream-to-srv2-(.*?)':
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f flv rtmp://private-rtmp-server-two:1935/stream-$G1
```

**Reply by RoxyBoxxy** [reply]
So this config is not working for me i keep getting 
```
ERR: invalid path name 'stream-(.*?)': can contain only alphanumeric characters, underscore, dot, tilde, minus or slash
```

**Reply by aler9** [reply]
use a tilde as prefix of regexp paths:

```yml
paths:
  '~stream-to-srv1-(.*?)':
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f flv rtmp://private-rtmp-server-one:1935/stream-$G1
  '~stream-to-srv2-(.*?)':
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f flv rtmp://private-rtmp-server-two:1935/stream-$G1
```

[a comment by an automated account is not shown]
