### DISCUSSION TITLE
h265 re-encoding to h264 with Reolink Duo 2 - Error decoding stream

### DISCUSSION THREAD

**Discussion by clangren** [bluenviron/mediamtx#1500] [Questions]
We are re-encoding the h265 main stream from an Reolink Duo 2 into h264 so we can pass the re-encoded h264 stream to Frigate for improved viewing support across browsers. We are running rtsp-simple-server natively (outside of Docker) on Debian 11. We have installed FFmpeg at the OS level in Debian.

Our abbreviated rtsp-simple-server.yml follows. Note the use of two paths, one for the h265 stream from the camera with RunOnReady configured and outputing to 'new' path. The 'new' path (h264 / drivewayh264) is also separately listed as a path in the rtsp-simple-server.yml file which is essentially blank.

```
logLevel: error
logDestinations: [stdout]
logFile: rtsp-simple-server.log
readTimeout: 20s
writeTimeout: 20s
readBufferCount: 2048
api: no
metrics: no
pprof: no
runOnConnect:
runOnConnectRestart: no
rtspDisable: no
protocols: [tcp]
encryption: "no"
rtspAddress: :8554
rtmpDisable: yes

paths:
# There are multiple cameras, but showing only the problem child here
  drivewayh265:
    source: rtsp://user:password@192.168.xx.xx:554/h265Preview_01_main
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/drivewayh265 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/drivewayh264
    runOnReadyRestart: yes
  drivewayh264:
```
In VLC we can view rtsp://192.168.xx.xx:8554/drivewayh265.
VLC describes those streams as follows:
Stream 0
-Codec: MPEG-H Part2/HVEC (H.265) (hevc)
-Type: Video
-Video resolution: 4608x1728
-Buffer dimensions: 4608x1728
-Frame rate 29.970029
-Decoded format: Planar 4:2:0 YUV
-Orientation: Top left
Stream 1
-Codec: MPEG AAC Audio (mp4a)
-Channels: Stereo
-Sample rate: 32000 Hz
-Bits per sample: 32

In VLC we can view rtsp://192.168.xx.xx/drivewayh264.
VLC describes those streams as follows:
Stream 0
-Codec: H264 - MPEG-4 AVC (part 10) (h264)
-Type: Video
-Video resolution: 4608x1728
-Buffer dimensions: 4608x1730
-Frame rate 20
-Decoded format: Planar 4:2:0 YUV
-Orientation: Top left
-Chroma location: Left
Stream 1
-Codec: MPEG AAC Audio (mp4a)
-Channels: Stereo
-Sample rate: 32000 Hz
-Bits per sample: 32

The system service rtsp-simple-server.service successfully starts and 'systemctl status rtsp-simple-server' displays the following at startup:

user@frigate:~/frigate# systemctl status rtsp-simple-server
● rtsp-simple-server.service
     Loaded: loaded (/etc/systemd/system/rtsp-simple-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-02-21 06:49:54 CST; 2s ago
   Main PID: 105139 (rtsp-simple-ser)
      Tasks: 56 (limit: 19040)
     Memory: 762.2M
        CPU: 3.817s
     CGroup: /system.slice/rtsp-simple-server.service
             ├─105139 /usr/local/bin/rtsp-simple-server /usr/local/etc/rtsp-simple-server.yml
             └─105153 ffmpeg -i rtsp://localhost:8554/clivedrivewayhiresh265 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f >

Feb 21 06:49:56 frigate rtsp-simple-server[105153]:     title           : Stream
Feb 21 06:49:56 frigate rtsp-simple-server[105153]:     encoder         : Lavf58.45.100
Feb 21 06:49:56 frigate rtsp-simple-server[105153]:     Stream #0:0: Video: h264 (libx264), yuv420p, 4608x1728, q=-1--1, 600 kb/s, 20 fps, 90k tbn, 20 tbc
Feb 21 06:49:56 frigate rtsp-simple-server[105153]:     Metadata:
Feb 21 06:49:56 frigate rtsp-simple-server[105153]:       encoder         : Lavc58.91.100 libx264
Feb 21 06:49:56 frigate rtsp-simple-server[105153]:     Side data:
Feb 21 06:49:56 frigate rtsp-simple-server[105153]:       cpb: bitrate max/min/avg: 0/0/600000 buffer size: 0 vbv_delay: N/A
Feb 21 06:49:56 frigate rtsp-simple-server[105153]:     Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp, 69 kb/s
Feb 21 06:49:56 frigate rtsp-simple-server[105153]:     Metadata:
Feb 21 06:49:56 frigate rtsp-simple-server[105153]:       encoder         : Lavc58.91.100 aac

Any input for alternatives and correction would be appreciated. Otherwise, the only reason we are posting is so some other noob might find this and save a little time.

Additional example here: https://github.com/aler9/rtsp-simple-server/discussions/930

Thanks very much to Alessandro for creating this application!

**Comment by aler9** [comment]
Hello, if i may give an additional advice, use GPU to decode and encode when possible:

```yml
paths:
# There are multiple cameras, but showing only the problem child here
  drivewayh265:
    source: rtsp://user:password@192.168.xx.xx:554/h265Preview_01_main
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/drivewayh265 -pix_fmt yuv420p -c:v h264_nvenc -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/drivewayh264
    runOnReadyRestart: yes
```

FFmpeg must be compiled with the `--enable-ffnvcodec`, as described here:
https://trac.ffmpeg.org/wiki/HWAccelIntro

Setup is longer but it's worth it since CPU consumption will decrease drastically. I've installed servers with single GPUs decoding 50 streams at once.

Best regards

[a comment by an automated account is not shown]
