### DISCUSSION TITLE
How to use Remuxing, re-encoding, compression with web cam

### DISCUSSION THREAD

**Discussion by tristan-f-r** [bluenviron/mediamtx#1516] [Questions]
Hello! I'm trying to remux my webcam in order to get it working in firefox (repeated from other issues: #1443), but the guide on it is a bit confusing as it's asking me to replace my existing configuration. If possible, can someone add an example for the camera with a remux? (It seems to be a very common issue:
- #1491
- #1443
- #1448
- #1396
- #1329

**Comment by aler9** [comment]
Hello, the sample configuration present in the guide is an example on how to "re-encode an existing stream, that is available in the /original path, and publish the resulting stream in the /compressed path". If you need to re-encode any stream you like in any path, it's enough to add the `runOnReady` parameter to the configuration that corresponds to your stream:

```yml
paths:
  mycamera:
    source: rtsp://url-of-camera
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/compressed
    runOnReadyRestart: yes

  # remember to add another path to receive the compressed stream
  compressed:
```
