### DISCUSSION TITLE
How to publish from one server(slinger) to rtsp simple server

### DISCUSSION THREAD

**Discussion by lehmbarsingh** [bluenviron/mediamtx#1527] [Questions]
I have the slinger server running on my pc  and I also have rtsp simple server running. presently I am going thru rtsp simple server and ffmpeg to convert to rtsp stream and hosting to echo show devices . Is there way to bypass the process of using ffmpeg converting to rtsp and hosting to web . what is proper configuration for .
this is my present config.
stream1:
     source: publisher
     runOnDemand: ffmpeg -i http://192.168.1.233:64642/mytv/m1v1sd -vcodec libx264 -f rtsp -rtsp_transport tcp rtsp://192.168.1.233:8554/stream1
     runOnDemandStartTimeout: 20s
     runOnDemandCloseAfter: 10s

**Comment by rpatidar** [comment]
i have limited background to media streaming so read the below suggestion with pinch of salt :)

Out of the box, I don't  think there is anyway it can be done, from all the example i came across unless there is a active rtsp source, it will be difficult, ffmpeg  command was providing that layer 

alternative 
you can also check the media formats here : https://github.com/aler9/gortsplib/tree/main/pkg/format , or may have to write your own

you may have to onboard new format and may need to change the streaming source here
https://github.com/aler9/rtsp-simple-server/blob/main/internal/core/rtsp_source.go#L78C18-L93

**Comment by aler9** [comment]
Hello, raw HTTP sources are currently not supported, so you'll have to unfortunately stick with FFmpeg.

Furthermore, if you need the `-vcodec libx264` option, the source stream probably uses a codec different than H264 (M-JPEG?), so you'd have to use FFmpeg to re-encode anyway.

You can however optimize the FFmpeg command line in order to use less CPU, by choosing a less-demanding preset and bitrate:

```yml

stream1:
  source: publisher
  runOnDemand: ffmpeg -i http://192.168.1.233:64642/mytv/m1v1sd -vcodec libx264  -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp -rtsp_transport tcp rtsp://192.168.1.233:8554/stream1
  runOnDemandStartTimeout: 20s
  runOnDemandCloseAfter: 10s
```

[a comment by an automated account is not shown]
