### DISCUSSION TITLE
How can I pass an ampersand character "&" in the runOnDemand command line?

### DISCUSSION THREAD

**Discussion by tomgat6** [bluenviron/mediamtx#1652] [Questions]
I'd need to pass an ampersand character "&" in the runOnDemand command line, but it does not work. The command generated ends at the "&" character, and everything after this is ignored. I've tried double quotes, quote with "\", but nothing works. Any help?

**Comment by aler9** [comment]
Hello, i tried to replicate the issue but in my case everything worked flawlessly. This is the configuration i used:

```yml

paths:
  ondemand:
    runOnDemand: ffmpeg -i rtsp://localhost:8554/proxied?key1=val1&key2=val2 -c copy -f rtsp rtsp://localhost:8554/proxied

  proxied:
    source: rtsp://camera-url

```
