### DISCUSSION TITLE
Branding

### DISCUSSION THREAD

**Discussion by dandanthedev** [bluenviron/mediamtx#1660] [Questions]
## Describe the feature

Hi, is there any way to add a custom logo in the top left corner? If not, can it be added?

**Comment by aler9** [comment]
Hello, you can add a logo to a video stream by using FFmpeg inside the `runOnReady` setting:

```yml
paths:
  original:
    runOnReady: ffmpeg -i rtsp://localhost:8554/original -i logo.png -filter_complex "overlay=5:5" -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:8554/branded

  branded:
```

Publish a video stream to path `/original` and you'll see the stream with the custom logo in path `/branded`.

For more complex usage, take a look at the documentation of the overlay filter of FFmpeg.

[a comment by an automated account is not shown]
