### DISCUSSION TITLE
How to link ffmeg to mediamtx on windows?

### DISCUSSION THREAD

**Discussion by dams92210** [bluenviron/mediamtx#1664] [Questions] [answered]
I am running successfully mediamtx on Windows 11 but I cannot make any call to ffmpeg.
I tried having it in same fonder, In the path system variable but nothing works.
Can you help?

**Comment by aler9** [comment]
Hello, make sure that you're using the native Windows version of FFmpeg (not the Cygwin one, not the MinGW one, not the WSL one) and use the absolute path in the configuration:

```yml
paths:
  mypath:
    runOnReady: 'C:\Users\my user\ffmpeg.exe' ...
```
