### DISCUSSION TITLE
Forward RTSP Camera Stream to Remote Server

### DISCUSSION THREAD

**Discussion by kidproquo** [bluenviron/mediamtx#1703] [Questions]
Hello,

I am trying to forward a stream from a camera on my local network to a remote server.

Camera RTSP stream -> Local mediamtx server ---Internet---> Remote mediamtx server -> VLC

I just can't figure out how to configure the two mediamtx servers. I can just run ffmpeg on the local server and copy the stream across to the remote server but I wanted to check if it's possible to do it with just mediamtx.

Very similar question on stack overflow: https://stackoverflow.com/questions/13755281/forward-rtsp-stream-to-remote-socket-rtsp-proxy

**Comment by Tokolosh** [comment]
i currently use datarhei restreamer for forwarding streams over the internet, however it would be nice to be able to use 1 program instead of 2

**Comment by aler9** [comment]
Hello, this can be achieved by using MediaMTX and FFmpeg. Configuration of the local MediaMTX server:

```yml
paths:
  camera:
    source: rtsp://my-camera-url
    runOnReady: ffmpeg -i rtsp://localhost:8554/$RTSP_PATH -c copy -f rtsp rtsp://remote-mediamtx-host:8554/cam
    runOnReadyRestart: yes
```

Configuration of the remote MediaMTX:

```yml
paths:
  camera:
```
