### DISCUSSION TITLE
The container doens't recognize the video device

### DISCUSSION THREAD

**Discussion by rbappi** [bluenviron/mediamtx#1707] [Questions]
Hey everyone

I have an issue that's making me insane, so I have an USB Webcam connected to a Ubuntu X86 machine who runs Docker.
I run the Docker file as suggested in the docs but I have the same error shown in the logs every single time, which is `Cannot open video device /dev/video0: No such file or directory`. I have checked with `v4l2-ctl` on my Ubuntu machine that all the USB webcam that I have tested, work perfectly. But no, I have no way to making it work with the Docker container. I have searched online, but it seems that I'm the only one having this error on Ubuntu :cry: 

Here is my .yml config file:
```
paths:
    usbcam:
        runOnInit: ffmpeg -f v4l2 -i /dev/video0 -preset ultrafast -c:v libx264 -x264-params keyint=60:scenecut=0 -f rtsp rtsp://<my_ip>:$RTSP_PORT/$RTSP_PATH
        runOnInitRestart: yes
```

And here is my Docker run command:
```
docker run --network=host \
-v $PWD/rtsp-simple-server.yml:/rtsp-simple-server.yml \
-d --privileged \
aler9/rtsp-simple-server:latest
```

Thanks in advance for your help.
