### DISCUSSION TITLE
Encode RTMP audio to Opus

### DISCUSSION THREAD

**Discussion by TheLion092** [bluenviron/mediamtx#1723] [Questions]
All examples i have seen with the "RunOnReady" argument to encode video or audio are with RTSP. So is it possible to encode the audio of a RTMP stream only and let the video untouched?

My goal is to stream via RTMP and watch via WebRTC with audio. As i know WebRTC doesn't support the standard RTMP audio so it needs to encode to opus.

I tried this but unfortunately it didn't work

```
paths:
  stream_original:
    source: publisher
    runOnReady: ffmpeg -i rtmp://localhost:1935/stream_original -c:a libopus -f rtmp rtmp://localhost:1935/stream_opus

  stream_opus:
```

**Comment by aler9** [comment]
Hello, the issue here is that the RTMP specification doesn't mention the Opus codec, and therefore there's no support for the RTMP/Opus combination anywhere. There's an [open group](https://github.com/veovera/enhanced-rtmp) that is working on improving RTMP in order to add support for Opus, but they haven't released a specification yet. You have to use RTSP to perform the conversion:

```yml
paths:
  stream_original:
    source: publisher
    runOnReady: ffmpeg -i rtsp://localhost:8554/stream_original -c:a libopus -f rtsp rtsp://localhost:8554/stream_opus

  stream_opus:
```

You can pull the `stream_opus` path with RTMP, it will contain only a video track:

```
ffmpeg -i rtmp://localhost:1935/stream_opus -c copy -f null -
```

[a comment by an automated account is not shown]
