### DISCUSSION TITLE
Does RTMP stream to WebRTC support Simulcast?

### DISCUSSION THREAD

**Discussion by guerinoni** [bluenviron/mediamtx#1724] [Questions]
It's a nice project! I didn't understand deeply how transcode happens from RTMP to webrtc but I don't think this supports simulcast...
Thanks

**Comment by aler9** [comment]
Hello,
the RTMP protocol allows streaming only two tracks at once, a video and an audio one, it can't be used for simulcast.
WebRTC allows simulcast but this is not currently implemented, since the server works by placing each stream in a separate path.
If you want to simulcast, i.e. publishing the same stream encoded multiple times with different resolutions, you can do that by publishing each variant in a dedicated path, i.e.

```yml
paths:
  stream_high_quality:
  stream_mid_quality:
  stream_low_quality:
```
