### DISCUSSION TITLE
I want to know the client's monitoring time ?

### DISCUSSION THREAD

**Discussion by volkankoc** [bluenviron/mediamtx#1753] [Questions]
How can I get the start and stop date/time of a consumer to watch the broadcast.
for ex:
Watch started: 13:00:50
Watch stoppped: 13:10:00 like

"I want to impose a certain watch time restriction on the broadcast."

**Comment by aler9** [comment]
Hello, you can setup a web hook that is called every time someone starts reading the stream:

```yml

paths:
  mypath:
    runOnRead: curl http://my-webhook/user-started
```

Inside the web hook handler, you can call the server API  to get the `created` field of every RTSP reader:

```
curl http://localhost:9997/v2/rtspsessions/list
```

response:

```yml
{
  "pageCount": 0,
  "items": [
    {
      "id": "string",
      "created": "string",
      "remoteAddr": "string",
      "state": "idle",
      "bytesReceived": 0,
      "bytesSent": 0
    }
  ]
}
```

you can then setup a timer for each reader and call `/v1/rtspsessions/kick` when you want to close the reader session:

```
curl http://localhost:9997/v2/rtspsessions/kick/{id}
```

This can be done int the same exact way for RTMP and WebRTC, by replacing `rtspsessions` with `rtmpconns` and `webrtcsessions`. It can't be done for HLS since HLS has no concept of "readers".

[a comment by an automated account is not shown]
