### DISCUSSION TITLE
How to connect opencv and rtsp-simple-server containers for RTSP publishing?

### DISCUSSION THREAD

**Discussion by datascientistlin** [bluenviron/mediamtx#1839] [Questions]
Dear All,

I'm trying to have containerized solution for RTSP streaming with both opencv and rtsp-simple-server. I composed both containers as follows:

```
version: '3'
services:
  stream_server:
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
    environment:
      MTX_PROTOCOLS: tcp

  stream_generator:
    build:
      context: .
      args:
        - OPENCV_VERSION=4.5.4
      dockerfile: Dockerfile
    image: opencv
    depends_on:
      - stream_server
```

And within the opencv container, I'm generating a continuous stream of frames to be published as RTSP through the rtsp-simple-server. The script is mostly adopted from the official guide [here](https://github.com/bluenviron/mediamtx#from-opencv)

```
import cv2
import numpy as np
from time import sleep, time

fps = 15
width = 800
height = 600
colors = [
    (0, 0, 255),
    (255, 0, 0),
    (0, 255, 0),
]

out = cv2.VideoWriter('appsrc ! videoconvert' + \
    ' ! x264enc speed-preset=ultrafast bitrate=600 key-int-max=' + str(fps * 2) + \
    ' ! video/x-h264,profile=baseline' + \
    ' ! rtspclientsink location=rtsp://stream_server:8554/mystream',
    cv2.CAP_GSTREAMER, 0, fps, (width, height), True)
if not out.isOpened():
    raise Exception("can't open video writer")
  
curcolor = 0
start = time()

while True:
    frame = np.zeros((height, width, 3), np.uint8)

    # create a rectangle
    color = colors[curcolor]
    curcolor += 1
    curcolor %= len(colors)
    for y in range(0, int(frame.shape[0] / 2)):
        for x in range(0, int(frame.shape[1] / 2)):
            frame[y][x] = color

    out.write(frame)
    print(f"frame written to the server")

    now = time()
    diff = (1 / fps) - (now - start)
    if diff > 0:
        sleep(diff)
    start = now
```

I'm getting the the message from terminal "**frame written to the server**" which seems to suggest the stream has been published successfully. However, I'm not able to view this RTSP stream anywhere.

Questions:

1. Do I have the right setup here for the 2 containers?
2. Which address should I use to get the RTSP output? I have tried `rtsp://localhost:8554/mystream`, `rtsp://localhost:8000/mystream`, `rtp://localhost:8554/mystream`, but none seems to work.

Thanks in advance for any advise and support!
