### DISCUSSION TITLE
stream hls direct to youtube

### DISCUSSION THREAD

**Discussion by ransariel** [bluenviron/mediamtx#1859] [Questions]
Thanks for the project
We have an ip cam feed streamed via mediamtx in HLS format (port 8888) to a server, 
Youtube now supports HLS as a live stream option, is there a way to include that in the conversion and direct the stream to youtube also?

**Comment by aler9** [comment]
Hello, streaming HLS to YouTube can be performed by using `ffmpeg` inside `runOnReady`, but it introduces a lot of latency and is not efficient at all. Since the server converts automatically from HLS to any of the supported protocols, you can stream the IP cam to YouTube with RTMP, by using:

```yml
paths:
  mycam:
    source: rtsp://my-camera-url
    runOnReady: ffmpeg -i rtsp://localhost:8554/$RTSP_PATH -c copy -f flv rtmp://youtube-url
```

And you can still watch the camera feed with HLS.

**Reply by ransariel** [reply]
thank you, I get an error (invalid url)
INF [RTSP] [conn [::1]:42040] opened
INF [RTSP] [conn [::1]:42040] closed (invalid URL (/cam))
it is running on an ipv6 network, hence the [::1] for local host, not sure why the port was converted to 42040 though

**Reply by aler9** [reply]
port 42040 is the port of the client, while the port of the server is still 8554. In TCP/IP, server and client use a port each. The client port is random. In my previous answer i wrote http:// instead of rtsp://, here's the right setup:

```yml
paths:
  mycam:
    source: rtsp://my-camera-url
    runOnReady: ffmpeg -i rtsp://localhost:8554/$RTSP_PATH -c copy -f flv rtmp://youtube-url
```
