### DISCUSSION TITLE
Auth for RTSP/RTMP Streams

### DISCUSSION THREAD

**Discussion by Tormund1985** [bluenviron/mediamtx#1865] [Questions]
Hi, 

I am trying to achieve authentication for my stream.

My YML code:
```
paths:
  cam:
    source: rpiCamera
    rpiCameraWidth: 1920
    rpiCameraHeight: 1080
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f segment -strftime 1 -segment_time 3600 -segment_format mpegts /home/pi/Vídeos/IMX708_%Y-%m-%d_%H-%M.ts
    runOnReadyRestart: yes
    readUser: user
    readPass: password
```

Then in theory you could open it from VLC or another player with:
rtmp://user:password@ip:1935/cam

But I get an error and it won't open.

When I disable readUser and readPass y can open the stream with:
rtmp://ip:1935/cam

Am I doing something wrong?

Thank you.
