### DISCUSSION TITLE
Help with configuration - still getting errors in log.

### DISCUSSION THREAD

**Discussion by gwinterboer** [bluenviron/mediamtx#1882] [Questions]
I'm trying to set this server up to take in udpvideo from vlc and then restream it back out to vlc using rtsp. 

I'm currently getting these repeating error msgs 

INF [path STREAM1/EO] runOnInit command exited with code 1 

WARNING: erroneous pipeline: no element "80"

This my current yml file, could someone confirm my syntax. The waves.ts test works as expected. 

```
###############################################
# General parameters

# Sets the verbosity of the program; available values are "error", "warn", "info", "debug".
logLevel: debug
# Destinations of log messages; available values are "stdout", "file" and "syslog".
logDestinations: [stdout]
# If "file" is in logDestinations, this is the file which will receive the logs.
logFile: rtsp_stable_streams.log

# Timeout of read operations.
readTimeout: 10s
# Timeout of write operations.
writeTimeout: 10s
# Number of read buffers.
# A higher number allows a wider throughput, a lower number allows to save RAM.
readBufferCount: 65536

# Enable the HTTP API.
api: no
# Address of the API listener.
apiAddress: 0.0.0.0:8558


###############################################
# RTSP parameters

# Disable support for the RTSP protocol.
rtspDisable: no
# List of enabled RTSP transport protocols.
# UDP is the most performant, but doesn't work when there's a NAT/firewall between
# server and clients, and doesn't support encryption.
# UDP-multicast allows to save bandwidth when clients are all in the same LAN.
# TCP is the most versatile, and does support encryption.
# The handshake is always performed with TCP.
protocols: [udp, tcp]
# Encrypt handshake and TCP streams with TLS (RTSPS).
# Available values are "no", "strict", "optional".
encryption: "no"
# Address of the TCP/RTSP listener. This is needed only when encryption is "no" or "optional".
rtspAddress: :80
# Address of the TCP/TLS/RTSPS listener. This is needed only when encryption is "strict" or "optional".
rtspsAddress: :8555
# Address of the UDP/RTP listener. This is needed only when "udp" is in protocols.
rtpAddress: :8550
# Address of the UDP/RTCP listener. This is needed only when "udp" is in protocols.
rtcpAddress: :8551


# Path to the server key. This is needed only when encryption is "strict" or "optional".
# This can be generated with:
# openssl genrsa -out server.key 2048
# openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650
serverKey: server.key
# Path to the server certificate. This is needed only when encryption is "strict" or "optional".
serverCert: server.crt
# Authentication methods.
authMethods: [basic, digest]
# Read buffer size.
# This doesn't influence throughput and shouldn't be touched unless the server
# reports errors about the buffer size.
#readBufferSize: 2048

###############################################
# RTMP parameters

# Disable support for the RTMP protocol.
rtmpDisable: no
# Address of the RTMP listener.
rtmpAddress: :8440

###############################################
hlsDisable: yes

###############################################
# Path parameters

# These settings are path-dependent, and the map key is the name of the path.
# It's possible to use regular expressions by using a tilde as prefix.
# For example, "~^(test1|test2)$" will match both "test1" and "test2".
# For example, "~^prefix" will match all paths that start with "prefix".
# The settings under the path "all" are applied to all paths that do not match
# another entry.
paths:
  #  WAVES/EO:   # Simple test stream to verify access to server. Availble at //rtsp://<IP>:80/WAVES/EO
  #   runOnInit: ffmpeg -y -re -stream_loop -1 -i /config/waves.ts -c:v copy -f rtsp -rtsp_transport tcp rtsp://0.0.0.0:$RTSP_PORT/$RTSP_PATH 
  #   runOnInitRestart: yes

  STREAM1/EO: # example for udp broadcast from vlan
    runOnInit: gst-launch-1.0 udpsrc port=11222 ! queue ! filesink location=$NAMED_PIPE $RTSP_PORT $RTSP_PATH
    runOnInitRestart: yes

  STREAM2/EO: # example for video coming from udp unicast
    # runOnInit: "gst-launch-1.0 udpsrc  port=60120 ! queue !  filesink location=$NAMED_PIPE" $RTSP_PORT $RTSP_PATH
    # runOnInitRestart: yes






```

**Comment by aler9** [comment]
Hello, the GStreamer pipelines contained in your configuration are wrong and need to be fixed, but this is not related to the server.

If the UDP streams are in MPEG-TS format, the server supports receiving them natively without GStreamer:

```yml
paths:

  STREAM1/EO: 
    source: udp://0.0.0.0:11222

  STREAM2/EO: 
    source: udp://0.0.0.0:60120
```

[a comment by an automated account is not shown]
