### DISCUSSION TITLE
Saving multiple streams

### DISCUSSION THREAD

**Discussion by nazikus** [bluenviron/mediamtx#1896] [Questions] [answered]
Hi,
Trying to setup server for RTSP and RTMP streams and save them to disk. Readme example for RTSP worked like a charm, but when I do it for both RTSP and RTMP I get errors. Although, If I run the same ffmpeg command out of mediamtx, it saves rtmp stream with no problems, but not when launched by mediamtx.

I added these lines in the place of original config, after [line 235](https://github.com/bluenviron/mediamtx/blob/main/mediamtx.yml#L235) (and commented out [line 449](https://github.com/bluenviron/mediamtx/blob/main/mediamtx.yml#L449)):
```yaml
  live/stream1:
    runOnReady: ffmpeg -hide_banner -loglevel error -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts rtsp_%Y-%m-%dT%H-%M-%S.ts
    runOnReadyRestart: yes
  live/stream2:
    runOnReady: ffmpeg -hide_banner -loglevel error -i rtmp://localhost:$RTMP_PORT/$RTMP_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts rtmp_%Y-%m-%dT%H-%M-%S.ts
    runOnReadyRestart: yes
```

Stream I use:
```bash
gst-launch-1.0 filesrc location=videos/2.mp4  ! qtdemux ! queue ! flvmux ! rtmpsink location='rtmp://127.0.0.1:1935/live/stream2'
```
I can read with no problems:
```bash
gst-launch-1.0 rtmpsrc location=rtmp://127.0.0.1/live/stream2 ! flvdemux ! h264parse ! avdec_h264 ! queue ! fpsdisplaysink sync=false
```

But save command fails:
```
2023/06/01 19:10:05 INF [RTMP] [conn 127.0.0.1:54560] opened
2023/06/01 19:10:05 INF [path live/stream2] runOnReady command started
2023/06/01 19:10:05 INF [RTMP] [conn 127.0.0.1:54560] is publishing to path 'live/stream2', 1 track (H264)
[tcp @ 0x555b3c83fc40] Port missing in uri
[rtmp @ 0x555b3c83f380] Cannot open connection tcp://localhost:0?tcp_nodelay=0
rtmp://localhost:$RTMP_PORT/$RTMP_PATH: Invalid argument
2023/06/01 19:10:05 INF [path live/stream2] runOnReady command exited with code 1
```

**Comment by aler9** [comment, marked as answer]
Hello, variables `RTMP_PORT` and `RTMP_PATH` are not available, you can use `:1935` and `RTSP_PATH` in place of them:

```yml
  live/stream2:
    runOnReady: ffmpeg -hide_banner -loglevel error -i rtmp://localhost:1935/$RTSP_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts rtmp_%Y-%m-%dT%H-%M-%S.ts
    runOnReadyRestart: yes
```

Anyway, reading a stream with RTMP, even if it is being published with RTMP, doesn't have any benefit, since the server automatically performs the conversion from a protocol to another. Therefore, you can publish with RTMP and read with RTSP. Reading with RTSP is advised since it supports multiple transport protocols and multiple codecs.
