### DISCUSSION TITLE
rtsp streaming setup

### DISCUSSION THREAD

**Discussion by ganesh-Eccma** [bluenviron/mediamtx#1917] [General]
Hi I have downloaded the mediamtx plugin and started to to run in the server and gstreamer was installed in the system.
can you please share us the ellaborated steps to setup a NVR with rtsp and gstreaming

**Comment by aler9** [comment]
Hello, there are no elaborate steps.

First open the configuration file and list all the cameras you want to record:

```yml
paths:
  proxied1:
    source: rtsp://url1

  proxied2:
    source: rtsp://url2
```

then you can record them by using `runOnReady` and `ffmpeg` as explained in the README:

```yml
paths:
  proxied1:
    source: rtsp://url1
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts saved_%Y-%m-%d_%H-%M-%S.ts
    runOnReadyRestart: yes

  proxied2:
    source: rtsp://url2
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts saved_%Y-%m-%d_%H-%M-%S.ts
    runOnReadyRestart: yes

```

[a comment by an automated account is not shown]
