### DISCUSSION TITLE
A real beginners question - help needed

### DISCUSSION THREAD

**Discussion by chris-haste** [bluenviron/mediamtx#1925] [Questions]
Apologies for this being a very basic question.

I want to know if mediamtx is suitable for the following:

I want to use a RPi with a usb webcam that produces h264 data. I want to send that stream, active 24/7, to mediamtx (RTP?) and have it saved to disk, in chunks (not sure on size/duration, or format atm). I then plan to use nginx as a way to serve those recorded files in an on-demand way to a browser (HLS?) Allowing the user to select a moment in time from which to start viewing the video.
In addition to the above usecase I want to be able to allow the client to connect to the live video feed when requested (No idea on what format this needs to be. hopefully HLS also?)

How suitable is mediamtx for this requirement?
After reading the documentation it looks like a good fit but i thought i would ask the experts in case there is something my lack of experience in all this has missed.
Also, what protocols formats are most suitable for each of these steps?

Thanks in advance

**Comment by aler9** [comment]
Hello,
First ingest the RPI Camera video feed into the server, by using this configuration:

```yml
paths:
  cam:
    source: rpiCamera
```

then enable recording as explained in the [README](https://github.com/bluenviron/mediamtx#save-streams-to-disk), just change the format from MPEG-TS to mp4 in order to produce browser-compatible and seekable segments:


```yml
paths:
  cam:
    source: rpiCamera
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts saved_%Y-%m-%d_%H-%M-%S.ts
    runOnReadyRestart: yes
```

then start nginx to serve the recorded files:

```
docker run -v /path/to/recorded/files:/usr/share/nginx/html:ro nginx
```

Recorded files can be accessed by opening URL:

```
http://nginx-ip/file-name.mp4
```

while the HLS live feed can be accessed by using MediamMTX and this URL:

```
http://mediamtx-ip:8888/stream
```

or the WebRTC feed:

```
http://mediamtx-ip:8889/stream
```

[a comment by an automated account is not shown]
