### DISCUSSION TITLE
Connection to RTSP server is dropping in Kubernetes

### DISCUSSION THREAD

**Discussion by datascientistlin** [bluenviron/mediamtx#1942] [Questions]
Dear all,

I'm setting up a RTSP streaming on my AKS using the rtsp simple server. I have a simple opencv script running in a container to generate frames and publish them to the rtsp simple server.

This setup works fine locally when I stream from one container to the server. But it doens't work on kubernetes.

The logs from rtsp simple server is like this. The connection is created, and then immediately closed.

```
2023/06/11 17:21:50 INF MediaMTX v0.23.5
2023/06/11 17:21:50 INF [RTSP] listener opened on :8554 (TCP)
2023/06/11 17:21:50 INF [RTMP] listener opened on :1935
2023/06/11 17:21:50 INF [HLS] listener opened on :8888
2023/06/11 17:21:50 INF [WebRTC] listener opened on :8889 (HTTP)
2023/06/11 17:22:48 INF [RTSP] [conn 10.244.125.215:58764] opened
2023/06/11 17:22:50 INF [RTSP] [session a7f70cef] created by 10.244.125.215:58764
2023/06/11 17:22:50 INF [RTSP] [conn 10.244.125.215:58764] closed (EOF)
2023/06/11 17:22:50 INF [RTSP] [session a7f70cef] destroyed (not in use)
```
What I have in my manifest files are as follows

- Stream generator
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: stream-generator
  name: stream-generator
  namespace: flux-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      service: stream-generator
  template:
    metadata:
      labels:
        service: stream-generator
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: stream_generator
          name: stream-generator
          ports:
            - containerPort: 8554
          env:
            - name: RTSP_SERVER_HOST
              value: "stream-server"
            - name: RTSP_SERVER_PORT
              value: "8554"
            - name: RTSP_SERVER_SUFFIX
              value: "mystream"
          volumeMounts:
            - mountPath: /tmp
              name: stream-generator-claim
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
      volumes:
        - name: stream-generator-claim
          persistentVolumeClaim:
            claimName: stream-generator-claim
```
- Stream Server (with cluster IP)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: stream-server
  name: stream-server
  namespace: flux-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      service: stream-server
  template:
    metadata:
      labels:
        service: stream-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: stream-server
          env:
            - name: MTX_PROTOCOLS
              value: tcp
          image: rtsp-simple-server:latest
          ports:
            - containerPort: 8554
            - containerPort: 1935
            - containerPort: 8189
              protocol: UDP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: stream-server
  name: stream-server
  namespace: flux-namespace
spec:
  ports:
    - name: "8554"
      port: 8554
      targetPort: 8554
    - name: "1935"
      port: 1935
      targetPort: 1935
    - name: "8189"
      port: 8189
      protocol: UDP
      targetPort: 8189
  selector:
    service: stream-server
```

Any help or hints are appreciated.

Thank you!
