### DISCUSSION TITLE
cannot open audio device

### DISCUSSION THREAD

**Discussion by klausmcm** [bluenviron/mediamtx#1960] [Questions]
Hi, I have a USB webcam with integrated microphone. I'm using the docker image `bluenviron/mediamtx:0.23.5-ffmpeg` and the following `mediamtx.yml`

```
paths:
  cam:
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -pix_fmt yuv420p -preset ultrafast -b:v 600k -f rtsp rtsp://127.0.0.1:8554/cam
    runOnInitRestart: yes
```

I'm able to view the video stream. I also would like to get the audio stream and tried

```
paths:
  cam:
    runOnInit: ffmpeg -f alsa -i default -f v4l2 -i /dev/video0 -pix_fmt yuv420p -preset ultrafast -b:v 600k -f rtsp rtsp://127.0.0.1:8554/cam
    runOnInitRestart: yes
```

but I get error messages like these

```
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
[alsa @ 0x7f831359a100] cannot open audio device default (No such file or directory)
```

Outside the docker container, I used `arecord -L` to determine the name of the webcam microphone and outside the docker container, this command allows me to record a video with audio using the webcam: `ffmpeg -f alsa -i plughw:CARD=CameraB404271,DEV=0 -f v4l2 -i /dev/video0 -pix_fmt yuv420p -preset ultrafast -b:v 600k -c:a libmp3lame -b:a 128k out.mp4`. How do I figure out a similar command to use inside the docker container? `arecord` is not available in the container. Thanks,
