### DISCUSSION TITLE
how to host mediamtx behind a reverse-proxy with lets encrypt..?

### DISCUSSION THREAD

**Discussion by magnuszetterberg** [bluenviron/mediamtx#2023] [Questions]
Hello all!

First post here... and I have been trying to find any discussions regarding hosting mediamtx behind a reverse-proxy(though directly mapped port to port, but only using http(s) and TCP) through traefik.

I have got something that works when running it locally on my computer, and accessing it through http://localhost/streamkey/publish and I can view it when loading http://localhost/streamkey/ in another tab...

However, when I try to get this working with letsencrypt and use it as the resolver, things start acting up.

Does anyone have an example of something like this working?  Im using traefik right now, but I dont really care which setup i use, as long as i get proper certificates working infront of mediamtx..

Br
Magnus Zetterberg

**Comment by magnuszetterberg** [comment]
```
version: '3'

services:
  traefik:
    image: traefik:v2.4
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.rtmp.address=:1935
      - --entrypoints.rtsp.address=:8554
      - --entrypoints.hls.address=:8888
      - --entrypoints.api.address=:9997
      #- --entrypoints.rtp.address=:8000
      #- --entrypoints.rtcp.address=:8001
    ports:
      - 80:80
      - 443:443
      - 1935:1935 #rtmp port
      - 8080:8080 #traefik dashboard - disable during production
      - 8554:8554 #rtsp port
      - 8888:8888 #hls port
      - 9997:9997 #api port
      #- 8000:8000/udp
      #- 8001:8001/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mediamtx:
      image: bluenviron/mediamtx:latest
      volumes:
        - ./mediamtx.yml:/mediamtx.yml
      labels:
        - traefik.enable=true
        - traefik.http.routers.web.entrypoints=web
        - traefik.http.routers.web.rule=Host(`localhost`)
        - traefik.http.routers.web.service=web-service
        - traefik.http.services.web-service.loadbalancer.server.port=8889

        - traefik.http.routers.api.entrypoints=api
        - traefik.http.routers.api.rule=Host(`localhost`)
        - traefik.http.routers.api.service=api-service
        - traefik.http.services.api-service.loadbalancer.server.port=9997

        - traefik.tcp.routers.rtmp.entrypoints=rtmp
        - traefik.tcp.routers.rtmp.rule=HostSNI(`*`)
        - traefik.tcp.routers.rtmp.service=rtmp-service
        - traefik.tcp.services.rtmp-service.loadbalancer.server.port=1935

        - traefik.tcp.routers.rtsp.entrypoints=rtsp
        - traefik.tcp.routers.rtsp.rule=HostSNI(`*`)
        - traefik.tcp.routers.rtsp.service=rtsp-service
        - traefik.tcp.services.rtsp-service.loadbalancer.server.port=8554

        - traefik.tcp.routers.hls.entrypoints=hls
        - traefik.tcp.routers.hls.rule=HostSNI(`*`)
        - traefik.tcp.routers.hls.service=hls-service
        - traefik.tcp.services.hls-service.loadbalancer.server.port=8888


# basic auth middleware
        - traefik.http.middlewares.auth.basicauth.users=admin:<random password>
        - traefik.http.routers.web.middlewares=auth  # adding basic auth to webrtc - just comment this out to disable
        - traefik.http.routers.api.middlewares=auth  # adding basic auth to api - just comment this out to disable
        - traefik.http.middlewares.auth.basicauth.realm=Restricted area
```
