### DISCUSSION TITLE
how to save hls packets on local machine

### DISCUSSION THREAD

**Discussion by Anurag-Raut** [bluenviron/mediamtx#2041] [Questions]
I want to save the hls packets generated by webrtc stream in local machine.

I found this command in docs , but wasn't able to understand what is MTX_PATH and mypath.

`paths:
  mypath:
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts saved_%Y-%m-%d_%H-%M-%S.ts
    runOnReadyRestart: yes`
    
I am running mediamtx server in Docker container.
Can anyone please help?

**Comment by aler9** [comment]
Hello, in MediaMTX streams and configurations are splitted by path. The path is set by the publisher, for instance this command publishes a file to path `mypath`:

```
ffmpeg -re -i myfile.mp4 -c copy -f rtsp rtsp://localhost:8554/mypath
```

The configuration you posted:

```yml
paths:
  mypath:
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts saved_%Y-%m-%d_%H-%M-%S.ts runOnReadyRestart: yes
```

tells the server to start `ffmpeg` every time a publisher starts sending video to the server on path `mypath`. FFmpeg connects to the server and dumps the video on disk. `$MTX_PATH` is a variable that gets replaced with the current path, that is `mypath`. Full documentation on variables and custom commands is in the configuration file:

https://github.com/bluenviron/mediamtx/blob/main/mediamtx.yml

[a comment by an automated account is not shown]
