### DISCUSSION TITLE
Is it possible to serve a simple video file with MediaMTX

### DISCUSSION THREAD

**Discussion by Managor** [bluenviron/mediamtx#2102] [Questions] [answered]
I wish to create a stream, record it to disk and then have the video to be available in a second path. Is this possible within MediaMTX?

**Comment by aler9** [comment, marked as answer]
Hello, save streams to disk as explained in the README:

```yml
paths:
  all:
    runOnReady: >
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH
      -c copy
      -f segment -strftime 1 -segment_time 60 -segment_format mp4 saved_%Y-%m-%d_%H-%M-%S.mp4
    runOnReadyRestart: yes
```

Then serve the folder with an HTTP server:

```
docker run --rm -it -v $PWD:/usr/share/nginx/html:ro -p 8080:80 -nginx
```

Serving recordings as .mp4 files with an HTTP server provides the best experience since it allows seeking, caching and is compatible with every client.

[a comment by an automated account is not shown]
