### DISCUSSION TITLE
RTSP forward to webRTC cloudflare WHIP ingestion URL

### DISCUSSION THREAD

**Discussion by Interop-Dev** [bluenviron/mediamtx#2119] [Questions]
Can mediaMTX push an RTSP feed to a cloudflare WHIP URL?

**Comment by aler9** [comment]
Hello, i added to the README instructions on how to forward streams to another server:

https://github.com/bluenviron/mediamtx#forward-streams-to-another-server

In case of WHIP, configuration is more or less like this:

```yml
paths:
  all:
    runOnReady: >
      gst-launch-1.0 rtspsrc location=rtsp://localhost:$RTSP_PORT/$MTX_PATH
      ! rtph264depay
      ! whipsink whip-endpoint=https://cloudflare-whip-endpoint
    runOnReadyRestart: yes
```

[a comment by an automated account is not shown]
