### DISCUSSION TITLE
Transport to Passive UDP Client

### DISCUSSION THREAD

**Discussion by baassisnos** [bluenviron/mediamtx#2188] [Questions]
I'm testing this Incredible media server, congratulations to the developers.
I have a doubt if it is possible to perform with mediamtx:
I want to stream a video/audio (a format that suits the question) for an RTSP (mediamtx) send PLAY, PAUSE the session created
However, the Client “would not request the streaming”: I want to send the output to a specific HOST and PORT via UDP. Is it possible to perform this feat?

After running the command:
ffmpeg -re -stream_loop -1 -i video3.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:8554/mystream

and capture the section how to perform the play and pause keeping sending to HOST and PORT UDP constant?

**Comment by aler9** [comment]
Hello, use `ffmpeg` inside `runOnReady` to accomplish this:

```yml
paths:
  mystream:
    runOnReady: >
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH
      -c copy
      -f mpegts udp://my-ip:my-port?pkt_size=1316
    runOnReadyRestart: yes
```

Be aware that the stream will be wrapped in MPEG-TS packets (not RTP packets, that are the packets used by RTSP), because MPEG-TS packets support multiple tracks and periodically broadcast the track list, while RTP packets don't.

[a comment by an automated account is not shown]
