### DISCUSSION TITLE
readUser: and readPass: being ignored?

### DISCUSSION THREAD

**Discussion by xevg** [bluenviron/mediamtx#2193] [Questions]
I am running mediamtx 1.0.0 and have the mediamtx.yml file configured with:
```
paths:
  all:
    # Username required to read.
    # SHA256-hashed values can be inserted with the "sha256:" prefix.
    readUser: admin
    # password required to read.
    # SHA256-hashed values can be inserted with the "sha256:" prefix.
    readPass: testpassword
```
However whether I connect with no username/password, or a different one, it still lets me read the stream. Am I doing something wrong in the configuration, or is there some reason it is ignoring that?
