### DISCUSSION TITLE
can i use mediamtx to read a rtmp stream, and repush to remote rtmp address?

### DISCUSSION THREAD

**Discussion by shushenghong** [bluenviron/mediamtx#2206] [Questions] [answered]
like read rtmp://a.com/s1 and repush to rtmp://b.com/s2

**Comment by adriano-peniche** [comment, marked as answer]
One way of doing it might be using something like the mediamtx.yml bellow, using ffmpeg.

```
paths:
  s1:
    runOnReady: ffmpeg -rtsp_transport tcp -i rtsp://127.0.0.1:8554/s1 -c:v copy -c:a copy -f flv rtmp://b.com/s2
    runOnReadyRestart: yes
```
