### DISCUSSION TITLE
ERROR: from element /GstPipeline:pipeline0/GstRTSPClientSink:s: Could not get/set settings from/on resource.

### DISCUSSION THREAD

**Discussion by andrico21** [bluenviron/mediamtx#2215] [Questions]
Hi,

first, amazing job was done - thanks a lot

Just tried to make similar setup with USB audio mixing like one [described in the doc today](https://github.com/bluenviron/mediamtx/pull/1975/commits). But for some reasons it doesn't work (attached log) - cannot get the problem, some input formats issue?
Video output works fine without any issues, but unable to add audio.

Raspberry Pi 4 + latest Pi OS x64 + Raspberry HQ camera, mediamtx 1.0.0
[mediamtx_unable_to_mix_audio.log](https://github.com/bluenviron/mediamtx/files/12363075/mediamtx_unable_to_mix_audio.log)

Config:
```yaml
protocols: [tcp]
paths:
  outdoor:
    source: rpiCamera
    rpiCameraWidth: 1920
    rpiCameraHeight: 1080
    rpiCameraFPS: 30
    rpiCameraBitrate: 2000000
    rpiCameraHFlip: false
    rpiCameraVFlip: false
    rpiCameraAWB: auto
    rpiCameraMetering: centre
    rpiCameraAfMode: auto
    rpiCameraAfSpeed: normal
    rpiCameraTextOverlayEnable: true
    rpiCameraTextOverlay: '%d.%m.%Y %H:%M:%S'
    runOnReady: >
      gst-launch-1.0 rtspclientsink name=s location=rtsp://localhost:8554/outdoor_with_audio rtspsrc location=rtsp://127.0.0.1:8554/outdoor latency=0 ! rtph264depay ! s. alsasrc device=default:CARD=AUGM10 ! opusenc bitrate=16000 ! s. -v
    runOnReadyRestart: yes
  outdoor_with_audio:
rtspAddress: :8554
```
