### DISCUSSION TITLE
capture rtsp camera stream to file and re stream to rtsp

### DISCUSSION THREAD

**Discussion by dasaint80** [bluenviron/mediamtx#2235] [Questions]
we're able to use the proxied option to have multiple rtsp camera streams. we would like to setup each stream to record and restream back to rtsp. 
when we try this we get that an error about publisher because the proxied streams are above the "all" section. 
we do this because we can rename each proxy source to the location of the camera.

we're running this on a windows machine if that matters. 

Thanks,

**Comment by aler9** [comment]
Hello, since v1.1.0 the server provides native recording capabilities, so in order to enable both recording and forwarding it's enough to follow the two dedicated sections in the README:

https://github.com/bluenviron/mediamtx#record-streams-to-disk

https://github.com/bluenviron/mediamtx#forward-streams-to-another-server

By merging all together:

```yml
record: yes

paths:
  cam1:
    source: rtsp://mycam
    record: yes
    runOnReady: >
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH
      -c copy
      -f rtsp rtsp://another-server/another-path
    runOnReadyRestart: yes

  cam2:
    source: rtsp://mycam
    record: yes
    runOnReady: >
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH
      -c copy
      -f rtsp rtsp://another-server/another-path
    runOnReadyRestart: yes

...
```

Settings must be replicated for each incoming stream.

[a comment by an automated account is not shown]
