### DISCUSSION TITLE
RTSP Streaming Configuration Issue with FFmpeg and RTSP Server

### DISCUSSION THREAD

**Discussion by Mr-MeerMoazzam** [bluenviron/mediamtx#2271] [Questions] [answered]
Hi!! @dedeibel @philn @tmatth @ey3ball @Gounlaf 
I am currently facing an issue while trying to stream a video using FFmpeg to an RTSP server. I have set up an RTSP server and I am using FFmpeg to send a video stream to it. However, I am encountering an error related to the configuration of the RTSP path.

Here's what I've done so far:

-> I have an RTSP server running and it's listening on port 8554.

-> I'm using the following FFmpeg command to stream a video:

```
ffmpeg -re -stream_loop -1 -i input_video.mp4 -c copy -f rtsp rtsp://localhost:8554/mystream
```
The input_video.mp4 file exists in the same directory where I'm running the FFmpeg command.

However, I'm getting the following error in the RTSP server logs:

```
2023/08/31 07:52:34 INF [RTSP] [conn 172.17.0.1:34752] opened
2023/08/31 07:52:34 INF [RTSP] [session 28a09640] created by 172.17.0.1:34752
2023/08/31 07:52:34 INF [RTSP] [conn 172.17.0.1:34752] closed (path 'mystream' is not configured)
2023/08/31 07:52:34 INF [RTSP] [session 28a09640] destroyed (not in use)
```

t seems like there might be an issue with the configuration of the RTSP path. I have checked the RTSP server's documentation and ensured that the server is running properly.

Can anyone provide guidance on how to properly configure the RTSP path for streaming using FFmpeg? I would greatly appreciate any insights or suggestions to help resolve this issue.

Thank you in advance for your help!

**Comment by aler9** [comment, marked as answer]
Hello, make sure that there's an entry in the `paths` section of the configuration that corresponds to your path:

```yml
paths:
  mypath:
```

**Reply by Mr-MeerMoazzam** [reply]
Thanks @aler9

**Reply by ericsouza** [reply]
> Hello, make sure that there's an entry in the `paths` section of the configuration that corresponds to your path:
> 
> ```yaml
> paths:
>   mypath:
> ```
hey @aler9 I'm facing a problem where a cannot setup `runOnInit` on defaultPaths and receive rtmp connections for any path. In my case I cannot set specific paths because I am going to receive multple rtmp connections and the path is going to be a random UUID for each streaming

So if I setup mtx with following config I cannot use `runOnInit` 

```yaml
pathDefaults:
  record: yes
  recordPath: ./recordings/%path/%Y-%m-%d_%H-%M-%S-%f
  recordFormat: fmp4
  recordPartDuration: 1s
  recordSegmentDuration: 1h
  recordDeleteAfter: 1d
  runOnRecordSegmentComplete: rclone sync -v --min-age=1ms ./recordings awss3:streaming-videos/recordings
  runOnInit: rclone sync -v ./recordings awss3:streaming-videos/recordings

paths:
  all_others:
```

And if I remove the "paths" section I get the error `closed: path 'myuuid-stream' is not configured
