### DISCUSSION TITLE
Video transformation?

### DISCUSSION THREAD

**Discussion by ignisVeneficus** [bluenviron/mediamtx#2309] [Questions]
Hello!
Is there any method to do soma transformation on the video stream?
I think only the mirror, or rotate (180 degree). I have a camera and I plan to screw it upside-down.

Thanx
Ignis

**Comment by aler9** [comment]
Hello, you can use FFmpeg together with MediaMTX to rotate the video and re-encode it as described in the [README](https://github.com/bluenviron/mediamtx#remuxing-re-encoding-compression):

```yml
paths:
  compressed:
  camera:
    source: rtsp://my-camera
    runOnReady: >
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH
        -vf "transpose=1"
        -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k
        -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/compressed
    runOnReadyRestart: yes
```

Mirrored stream will be available in path `/compressed`.

In order to perform other kind of rotations, refer to the FFmpeg documentation.

[a comment by an automated account is not shown]
