### DISCUSSION TITLE
Mediamtx behind traefik + WebRTC

### DISCUSSION THREAD

**Discussion by ignisVeneficus** [bluenviron/mediamtx#2310] [Questions] [answered]
Hello!
I set up the mediamtx behind taefik (reverse proxy) via docker compose
Everything is working, just the webRTC cant connect:
I got this from chrome console:
```
requesting ICE servers
(index):145 sending offer
(index):176 peer connection state: checking
(index):133 new track: video
(index):133 new track: audio
(index):176 peer connection state: disconnected
```
and I have this from the console:
```
2023/09/06 15:17:31 INF [WebRTC] [session 342fc79c] created by 172.20.0.3:49998
2023/09/06 15:17:41 INF [WebRTC] [session 342fc79c] closed (deadline exceeded while waiting connection)
```
I have the source:
```
2023/09/06 14:53:15 INF MediaMTX v1.0.3
2023/09/06 14:53:15 INF [path cam1] [RTSP source] started
2023/09/06 14:53:15 INF [RTSP] listener opened on :8554 (TCP)
2023/09/06 14:53:15 INF [RTMP] listener opened on :1935
2023/09/06 14:53:15 INF [HLS] listener opened on :8888
2023/09/06 14:53:15 INF [WebRTC] listener opened on :8889 (HTTP)
2023/09/06 14:53:15 INF [SRT] listener opened on :8890 (UDP)
2023/09/06 14:53:16 INF [path cam1] [RTSP source] ready: 2 tracks (H264, G711)
```
everything is worked when i tested without the traefik.
my traefik config:
```
  mediamtx:
    restart: unless-stopped
    image: bluenviron/mediamtx
    container_name: mediamtx
    environment:
      MTX_PROTOCOLS: tcp
    volumes:
     - ${MEDIAMTX_PATH}/data/mediamtx.yml:/mediamtx.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediamtx.rule=Host(`${MEDIAMTX_HOST}`)"
      - "traefik.http.routers.mediamtx.entrypoints=websecure"
      - "traefik.http.routers.mediamtx.tls.certresolver=myresolver"
      - "traefik.http.routers.mediamtx.service=mediamtx"
      - "traefik.http.services.mediamtx.loadBalancer.server.port=8889"
      - "traefik.http.routers.mediamtx.middlewares=deepauth"
```

I think i close some path back to the server, or need open a port.
I'd like to use only to watch my cameras remotely.

Maybe somebody can help.
Thanx
