### DISCUSSION TITLE
The difference between runOnReady and runOnInit

### DISCUSSION THREAD

**Discussion by liusuyi2021** [bluenviron/mediamtx#2318] [Questions]
## Which version are you using?

v1.0.3

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

1. runOnDemand, I understand that this is running ffmpeg on demand
2. I cannot understand when to use runOnReady and runOnInit
Can you provide a detailed introduction to the usage scenarios and differences of the last two

## Did you attach the server logs?

 no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello,

`runOnInit` is run when MediaMTX is started you can use it to populate a path with something that is not natively compatible with MediaMTX:

```yml
paths:
  mypath:
    runOnInit: echo "this will be printed when MediaMTX starts"
```

`runOnReady` is run when a stream in a path is ready to be read, you can use it to trigger something like an alarm or to setup stream forwarding:

```yml
paths:
  mypath:
    runOnReady: echo "this will be printed when someone publishes a stream to this path"
```
