### DISCUSSION TITLE
Reload stream for new readers

### DISCUSSION THREAD

**Discussion by zzzoyd** [bluenviron/mediamtx#2436] [Questions]
Hi!
Is it possible to have such a configuration in which for each new client, the stream (publishing a video file using ffmpeg) will start over?
Thanks!

**Comment by aler9** [comment]
Hello, use this configuration:

```yml
paths:
  all:
    runOnDemand: ffmpeg -re -stream_loop -1 -i file.ts -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnDemandRestart: yes
```

and redirect each client to a random path, for instance by using the current timestamp as the path:

```
rtsp://localhost:8554/1700175763
```

[a comment by an automated account is not shown]
