### DISCUSSION TITLE
WebRTC on domain.

### DISCUSSION THREAD

**Discussion by radimkohout** [bluenviron/mediamtx#2527] [Questions]
### Question

Hi,
I am running mediamtx (native arm64 version) and trying to connect to WebRTC behind NAT. When I do it locally, everything works, but when I try it remotly using domain name, it only blinks black. When I try it using public IP address, everything works, except I can't use SSL certificate. How can I get it to work using domain name? I router, I am routing ports 8189 and 8889 both tcp and udp to the device. 

```
webrtcICEHostNAT1To1IPs: [93.x.x.x]
# any port of choice
webrtcICEUDPMuxAddress: :8189
webrtcICETCPMuxAddress: :8189

webrtcICEServers2:
- url: turn:a.relay.metered.ca:80
  username: <ommited>
  password: <ommited>

```
