### DISCUSSION TITLE
multiple rtsp server with single public ip

### DISCUSSION THREAD

**Discussion by pankajsaini1987** [bluenviron/mediamtx#2598] [Questions]
### Question

i have multiple rtsp server case like

server 1: i have 30 camera connected with rtsp stream and publishing
server 2: i have 40 camera connected with rtsp stream and publishing
server 3: i have 40 camera connected with rtsp stream and publishing

now the case is: on server 3 only i have static ip connected, but i want to view every server ( server 1,2,3) stream to outside network with the static ip bind with server 3 only, 

server 1,2,3 all connected with same network with LAN
can you suggest how can i achieve this.

**Comment by pankajsaini1987** [comment]
can anyone help

**Comment by aler9** [comment]
Hello, there are multiple ways to achieve what you what (exposing 3 servers through a single public IP address, connected to one of the server).

A first method consists in configuring the MediaMTX instance in the public server (server 3) to proxy streams, on-demand, from the other two servers:

```yml
paths:
   server_1_cam1:
    source: rtsp://server1/cam1
    sourceOnDemand: true 

   server_1_cam2:
    source: rtsp://server1/cam2
    sourceOnDemand: true 

   ...x40

   server_2_cam1:
    source: rtsp://server2/cam1
    sourceOnDemand: true 

   server_2_cam2:
    source: rtsp://server2/cam1
    sourceOnDemand: true

    ...x40
```

you can then connect to `rtsp://server3/server_2_cam_1` instead of `rtsp://server2/cam1`.

Another method consists in installing a TCP proxy like [HAProxy](https://www.haproxy.org/) or [traefik](https://github.com/traefik/traefik) on server 3 and use it to proxy requests to the other two servers.

[a comment by an automated account is not shown]
