### DISCUSSION TITLE
Support websockets for server mode

### DISCUSSION THREAD

**Discussion by JiffsMaverick** [bluenviron/mediamtx#268] [Questions]
## Which version are you using?

v0.9.15

## Which operating system are you using?

CentOS 7

## Enhancement request

You developed awesome software, thanks! Can you add support websockets for server mode? Here are examples realisation:

[websocket-relay.js](https://github.com/phoboslab/jsmpeg/blob/master/websocket-relay.js) - it is original implement by JS from jsmpeg library

[jsmpeg-stream-go](https://github.com/mqhack/jsmpeg-stream-go) - it is same but implement by Go

**Comment by aler9** [comment]
Hello, you can edit the configuration to receive a stream and send it back in the format your library expects:
```yml
paths:
  proxied:
    runOnPublish:  ffmpeg -i rtsp://localhost:8554/$RTSP_SERVER_PATH -f mpegts -codec:v mpeg1video -b:v 800k -r 24 -framerate 24  -codec:a mp2 -b:a 128k -muxdelay 0.001 http://localhost:8082/secret
```

Unfortunately the mpegts-via-websocket technique is not standardized, so i prefer not to integrate it into rtsp-simple-server - furthermore the technique supports only H264 and AAC, while rtsp-simple-server must support any codec.

The only supported output is rtsp, but nothing forbids from adding ffmpeg commands to the runOnInit, runOnDemand, runOnPublish, runOnRead options.
