### DISCUSSION TITLE
change resolution

### DISCUSSION THREAD

**Discussion by pythonstuff8** [bluenviron/mediamtx#2682] [Questions]
### Question

how do I change the resolution of the video feed to 1080p which my webcam(logitech c920) supports. I used the generic Webcam section .

**Comment by aler9** [comment]
Hello, FFmpeg has a flag that allows to scale up or down the resolution:

```yml
paths:
  cam:
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -pix_fmt yuv420p -vf "scale=1280:720" -preset ultrafast -b:v 600k -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
```
