### DISCUSSION TITLE
Re-stream to YouTube etc.

### DISCUSSION THREAD

**Discussion by DanielFrankDK** [bluenviron/mediamtx#2709] [Questions]
### Question

Hello!

I'm trying to use MediaMTX to re-stream to YouTube and other services.

Here's my paths:

```
paths:

  test:
    source: publisher
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 10s

    runOnReady: ffmpeg -re -i "rtmp://localhost/stream" -c copy -f flv "rtmp://a.rtmp.youtube.com/live2/SECRET"
    runOnReadyRestart: true

  # Settings under path "all_others" are applied to all paths that
  # do not match another entry.
  all_others:
```

OBS is set up to stream to server: rtmp://localhost/stream
No Stream Key is set in OBS.

However, nothing is being sent to YouTube. What am I doing wrong?

ffmpeg library is placed within the same folder as MediaMTX.

I'm using mediamtx_v1.3.0_windows_amd64
