### DISCUSSION TITLE
About recording file

### DISCUSSION THREAD

**Discussion by PatchaSravani2** [bluenviron/mediamtx#2759] [Questions]
### Question

I want save only the final recording file after ending the stream instead of continuously writing it.
Is it possible? If yes then please let me know.

**Comment by aler9** [comment]
Hello, if you want to disable deletion of old segments, it's enough to set `recordDeleteAfter` to `0s`, as mentioned in the documentation:

```yml
  # Delete segments after this timespan.
  # Set to 0s to disable automatic deletion.
  recordDeleteAfter: 24h
```

**Reply by PatchaSravani2** [reply]
Yeah that's fine, but I want to save the recording only after the stream is stopped instead of writing it continuously. Is this possible?

**Reply by PatchaSravani2** [reply]
And also is it possible to know if any stream is destroyed using APIs or something like that because if I see any log saying destroyed: no one is publishing to path 'mystream/D1123_M1234' then I want to know this D1123_M1234 and send this info D1123_M1234 to my server and my server will send request to an app which is my source and that app will start sending the data for this particular path 'mystream/D1123_M1234' then I want to strat my rtmp stream of path 'mystream/D1123_M1234'. If this is possible then please let me know ASAP.

**Reply by aler9** [reply]
> is it possible to know if any stream is destroyed using APIs or something like

Yes, you can do this by using `runOnNotReady`:

```yml
pathDefaults:
  # Command to run when the stream is not available anymore.
  # Environment variables are the same of runOnReady.
  runOnNotReady: curl http://my-custom-server/webhook?path=$MTX_PATH&source_type=$MTX_SOURCE_TYPE&source_id=$MTX_SOURCE_ID
```

There are a series of hooks that are documented into the README.

[a comment by an automated account is not shown]
