### DISCUSSION TITLE
Bad audio quality when transcoding from AAC to Opus

### DISCUSSION THREAD

**Discussion by AseCoder** [bluenviron/mediamtx#2787] [Questions] [answered]
### Question

I am streaming an OBS output and in order to listen to the stream in a browser using WebRTC the audio codec of the stream must not be AAC. I tried to implement the solution from [this issue](https://github.com/bluenviron/mediamtx/issues/1329). This is my implementation:
```yml
paths:
  fin:
  mystream:
    runOnReady:
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -vcodec copy -c:a libopus -f rtsp rtsp://localhost:$RTSP_PORT/fin
    runOnReadyRestart: yes
```

The results are as follows:
- The stream has audio
- The audio is crackly and distorted
- The console spits out, in yellow text, `Stream #0: not enough frames to estimate rate; consider increasing probesize`

I have tried increasing the probesize. The ffmpeg command now looks like this:
`ffmpeg -probesize 10M -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -vcodec copy -c:a libopus -f rtsp rtsp://localhost:$RTSP_PORT/fin`

When I try running that the console spits out `Non-monotonous DTS in output stream 0:1; previous: 485588, current: 481212; changing to 485589. This may result in incorrect timestamps in the output file.` many times.

I then tried regenerating the DTS with `-fflags +igndts` as suggested by the top answer to [this](https://stackoverflow.com/questions/55914754/how-to-fix-non-monotonous-dts-in-output-stream-01-when-using-ffmpeg). After that the bad audio quality persists and the only warning in the console is `No bit rate set. Defaulting to 96000 bps`.

How in the world do I transcode the audio without it becoming unintelligible?

MediaMTX v1.3.1
ffmpeg version 5.1 essentials
[log.txt](https://github.com/bluenviron/mediamtx/files/13588257/log.txt)

**Comment by AseCoder** [comment]
I just tested that command on a normal video file and it worked fine. It spat out the bitrate warning but the audio quality was fine.

**Comment by aler9** [comment]
Hello, try setting the channel count and the bitrate too:

```yml
paths:
  fin:
  mystream:
    runOnReady:
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -vcodec copy -ac 2 -c:a libopus -b:a 128k -f rtsp rtsp://localhost:$RTSP_PORT/fin
    runOnReadyRestart: yes
```
