### DISCUSSION TITLE
Can't configure two webcams

### DISCUSSION THREAD

**Discussion by mwolfeu** [bluenviron/mediamtx#2809] [Questions]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ x] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I can't configure two webcams.
I'm using the stock config except the following modification to the bottom:

```
paths:
  video2:
    source: publisher
    runOnInit: ffmpeg -pix_fmt yuv420p -i /dev/video2 -s:v 320x240 -r 5 -c:v h264 -preset ultrafast -tune zerolatency -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
  video0:
    source: publisher
    runOnInit: ffmpeg -pix_fmt yuv420p -i /dev/video0 -s:v 320x240 -r 5 -c:v h264 -preset ultrafast -tune zerolatency -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
  # Settings under path "all_others" are applied to all paths that
  # do not match another entry.
  all_others:

```

## Describe how to replicate the issue

1. Use the above config
2. start mediamtx
3. go to video0
4. go to video2

## Did you attach the server logs?

yes

## Did you attach a network dump?

no
[mediamtx_two webcams.log](https://github.com/bluenviron/mediamtx/files/13178874/mediamtx_two.webcams.log)

**Comment by mwolfeu** [comment]
Not fixed but understood.
It all rests on the arbitrariness of USB camera firmware, how much bandwidth it requests from the hub, and the resolutions/fps supported.
I was able to get a 320x240 and 640x480 cam working together but not two of the higher resolution.
To make the problem worse on an RPi 4.  Plugging 4 USB 2.0 devices (including using the USB 3.0 ports) still backhaul all traffic to the the same USB 2 root meaning devices on all four ports would share 480bps.

**Comment by aler9** [comment]
Hello, this is a Raspberry Pi limitation and the server has no role in it. You're performing software encoding on two streams, and this is limited by the maximum speed of the CPU. Since the Raspberry Pi has a H264 hardware encoder too, my advice is to move one of the processes on the hardware encoder:

```yml
paths:
  video2:
    source: publisher
    runOnInit: ffmpeg -pix_fmt yuv420p -i /dev/video2 -s:v 320x240 -r 5 -c:v h264_v4l2m2m -b:v 100k -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
  video0:
    source: publisher
    runOnInit: ffmpeg -pix_fmt yuv420p -i /dev/video0 -s:v 320x240 -r 5 -c:v h264 -preset ultrafast -tune zerolatency -b:v 100k -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
```

[a comment by an automated account is not shown]
