### DISCUSSION TITLE
How to make a proper setup that grab mpeg from http stream local and restream it via ffmpeg to local adress

### DISCUSSION THREAD

**Discussion by wazerstar** [bluenviron/mediamtx#2812] [Questions]
### Question

Server version 1.4.0

edit mediamtx.yml

edited

```
logLevel: debug
logDestinations: [stdout, file]
```

added this to paths

```
paths:
  ondemand:
    runOnDemand: ffmpeg -i http://localIP:port/stream -c:v h264_qsv -b:v 5M -look_ahead 1 -c:a aac -rematrix_maxval 1.0 -ac 2 -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnDemandRestart: yes
```

When I launch it in ffplay or just simply grab the output as a output.mp4 it works fine with ffmpeg fine, but with mediamtx its not working.

`ffmpeg -i http://localIP:port/stream -c:v h264_qsv -b:v 5M -look_ahead 1 -c:a aac -rematrix_maxval 1.0 -ac 2 output.mp4`

also I'm not even sure if rtsp would the perfect solution if anything else should be chosen what should it be and how should it be done?

Log file
[mediamtx.log](https://github.com/bluenviron/mediamtx/files/13685806/mediamtx.log)
