### DISCUSSION TITLE
How to have HLS with external authentication using JWT?

### DISCUSSION THREAD

**Discussion by l-lin** [bluenviron/mediamtx#2813] [Questions] [answered]
### Question

I have configure MediaMTX with external authentication with docker compose like this:

```yaml
services:
  mediamtx:
    image: bluenviron/mediamtx:1.4.0
    ports:
      - 1935:1935
      - 80:80
      - 8080:8080
      - 9121:9121
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9121/metrics"]
      start_period: 1s
      interval: 1s
    environment:
      MTX_RTMP: "true"
      MTX_RTMP_ADDRESS: ":1935"
      MTX_HLS: "true"
      MTX_HLSADDRESS: ":80"
      MTX_API: "false"
      MTX_METRICS: "false"
      MTX_RTSP: "false"
      MTX_WEBRTC: "false"
      MTX_SRT: "false"
      MTX_EXTERNALAUTHENTICATIONURL: "http://mock-auth/auth"
  mock-auth:
    image: node:18.18-slim
    entrypoint: [ "node", "/src/mock-auth.js" ]
    ports:
      - 81:80
    volumes:
      - ./test/mock-auth.js:/src/mock-auth.js
```

`mock-auth` is just a simple http server that responds to HTTP 200 if the token is valid (put in the `password` field in this example):

```js
require("http")
  .createServer(function (req, res) {
    let body = [];
    req
      .on("error", (err) => {
        console.error(err);
      })
      .on("data", (chunk) => {
        body.push(chunk);
      })
      .on("end", () => {
        body = Buffer.concat(body).toString();

        console.log(req.method, req.url, body);

        if (req.url === "/auth") {
          const payload = JSON.parse(body);
          if (payload.user === "foobar" && payload.password === "jwt") {
            res.statusCode = 200;
          } else {
            res.statusCode = 401;
          }
        } else {
          res.statusCode = 404;
        }
        res.end();
      });
  })
  .listen(80, function () {
    console.log("Server started and listening on port 80.");
  });
```

I start a live stream using `ffmpeg`:

```bash
ffmpeg -re \
  -stream_loop -1 \
  -i sample.mp4 \
  -c copy \
  -f flv \
  "rtmp://localhost:1935/sample?user=foobar&pass=jwt"
```

Ingesting video works as expected, however, what about the HLS part?

Accessing to the MediaMTX HLS web page http://localhost/sample, my browser will ask some credentials, which I'm guessing will use a basic authentication.

However, I want to include the player inside an authenticated web application that is already using JWT for authentication, i.e. configuring the player hls.js like this without having the browser asking some credentials:

```js
new Hls({
    xhrSetup: function(xhr) {
        xhr.withCredentials = true; // do send cookies
    }
});
```

For example, I have already some cookie or a header `Authorization: Bearer token`, can I configure MediaMTX to forward some of request headers to the external authentication server?

Thanks.
