### DISCUSSION TITLE
Proxy to multiple cameras?

### DISCUSSION THREAD

**Discussion by mikcatta** [bluenviron/mediamtx#291] [Questions]
## Which version are you using?

v0.12.2

## Which operating system are you using?

 Linux

## Question

Is it.possible to proxy to.multiple sources (cameras)?

**Comment by aler9** [comment]
of course
```yml
paths:
  proxied1:
    source: rtsp://url1

  proxied2:
    source: rtsp://url2
```

[a comment by an automated account is not shown]
