### DISCUSSION TITLE
RTSP to WEbrtc

### DISCUSSION THREAD

**Discussion by sishari** [bluenviron/mediamtx#2923] [Questions]
### Question

Hello,

I would like to read a RTSP H265 stream from a camera and read with a Webbrowser from Server over WEBRTC.

How i must config the MEdiaMTX in yml?
This is my config for H264 from the camera.

I have read for H265 i must transcode with ffmpeg the RTSP H265 to WebRTC H264.
paths:
 cam1:
  sourceOnDemand: true
  source: rtsp://user:pw@192.168.1.67:554/cam/realmonitor?channel=1&subtype=2

**Comment by sishari** [comment]
Can anybod help me?

Thanks

**Comment by aler9** [comment]
Hello, conversion from RTSP to WebRTC is automatic. In order to ingest a RTSP stream into the server, instructions are here:
https://github.com/bluenviron/mediamtx#rtsp-cameras-and-servers

in order to read with WebRTC and a web browser, instructions are here:
https://github.com/bluenviron/mediamtx?tab=readme-ov-file#webrtc

If you want to use H265, you have to convert it to H264. Instructions are here:
https://github.com/bluenviron/mediamtx?tab=readme-ov-file#remuxing-re-encoding-compression

Putting all together:

```yml
paths:
  cam1:
    sourceOnDemand: true
    source: rtsp://user:pw@192.168.1.67:554/cam/realmonitor?channel=1&subtype=2
    runOnReady: >
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH
        -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k
        -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/cam1_compressed
```

Then use `http://localhost:8889/cam1_compressed` instead of `http://localhost:8889/cam1` in order to read.
