### DISCUSSION TITLE
How can I reduce network data usage when no one watch stream thread ?

### DISCUSSION THREAD

**Discussion by ToanJunifer** [bluenviron/mediamtx#293] [Questions]
## Which version are you using?

v0.9.15

## Which operating system are you using?

Ubuntu 16.04.7 LTS

## Question

Assume that: I have a device which pushes stream video to rtsp://IP:PORT/path. But in some cases, no one access on this rtsp link to view. But my device is still stream video and consumes network data. It's very wasted. How can I solve it ?

**Comment by ToanJunifer** [comment]
I find that rtspclientsink(I'm using it to stream video to your rtsp-simple-server) have a property called "do-rtsp-keep-alive". Did it work with your rtsp-simple-server ? If it's working, how can I use it? Thank you so much!

**Comment by aler9** [comment]
Hello, the server can be configured to start a GStreamer pipeline when someone requests a path, and to shut it down if all clients disconnect:

```yml
paths:
  ondemand:
    runOnDemand: gst-launch-1.0 -v ... rtspclientsink location=rtsp://localhost:8554/mystream
    runOnDemandRestart: yes
```

If the pipeline can't be launched from the server side, an alternative consists in launch two instances of rtsp-simple-server, one on the device, and the other one on the server; you make the device publish to the first instance, and configure the second one to receive the first one, but only when someone requests it:

```yml
paths:
  proxied:
    source: rtsp://first-instance
```

The property `do-rtsp-keep-alive` has a completely different purpose.
