### DISCUSSION TITLE
Publish rtsps from file

### DISCUSSION THREAD

**Discussion by sire6** [bluenviron/mediamtx#2947] [Questions]
Hi
Would like to publish a rtsps stream from a video file but can't find how to do it.
Thanks for help

**Comment by aler9** [comment]
Hello, you can enable encryption in the configuration file:

```yml
protocols: [tcp]
encryption: "strict"
serverKey: server.key
serverCert: server.crt
```

Then you can publish the file with FFmpeg:

```
ffmpeg -re -stream_loop -1 -i file.ts -c copy -f rtsp rtsps://localhost:8554/mystream
```

and read it with anything you want:

```
vlc rtsps://localhost:8554/mystream
```

[a comment by an automated account is not shown]
