### DISCUSSION TITLE
Serve HLS with Docker

### DISCUSSION THREAD

**Discussion by moritz157** [bluenviron/mediamtx#299] [Questions] [answered]
## Which version are you using?

v0.15.0

## Question

I currently run rtsp-simple-server using a docker container, as described in the Readme and so far it works perfectly . Now I want to convert the stream to HLS. Therefore I changed the configuration as needed. But how do I access the generated HLS-stream? The Readme suggests to serve the outputted .h3u8 and .ts files using a web server. But what is the best method to do that, if the files are only outputted inside the container? 

I am not really experienced with Docker, so probably there is an obvious solution I missed. 

I would really appreciate any help.

**Comment by aler9** [comment, marked as answer]
Hello, you simply need to build a docker image with
* rtsp-simple-server
* ffmpeg
* nginx

You can do it by saving this into a file called `Dockerfile`

```
FROM aler9/rtsp-simple-server AS rtsp

FROM alpine:3.12
RUN apk add --no-cache ffmpeg nginx

RUN mkdir /run/nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=rtsp /rtsp-simple-server /
COPY rtsp-simple-server.yml /

ENTRYPOINT [ "sh", "-c", "nginx && /rtsp-simple-server" ]
```

save this into `rtsp-simple-server.yml`

```
paths:
  all:
    runOnPublish: cd /var/www && ffmpeg -re -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f hls -hls_time 1 -hls_list_size 3 -hls_flags delete_segments -hls_allow_cache 0 stream.m3u8
    runOnPublishRestart: yes
```

save this into `nginx.conf`

```
server {
        listen 80 default_server;

        location / {
                root /var/www;
        }
}
```

Compile everything into an image

```
docker build . -t myimage
```

Launch the image

```
docker run --rm -it --network=host myimage
```

The published stream will be available on

```
http://localhost/stream.m3u8
```
