### DISCUSSION TITLE
Webrtc closed: deadline exceeded while waiting connection

### DISCUSSION THREAD

**Discussion by d3xt3r01** [bluenviron/mediamtx#3077] [Questions]
### Question

So I have this config:
```
webrtc: yes
webrtcAddress: 192.168.1.2:1989
webrtcLocalUDPAddress: 192.168.1.2:8189
webrtcEncryption: no
webrtcTrustedProxies: [172.16.1.2]
webrtcLocalTCPAddress: ''
webrtcIPsFromInterfaces: yes
webrtcAllowOrigin: 'mypublichostname'
webrtcAdditionalHosts: [mypublichostname, 192.168.1.2]
webrtcICEServers2: [url: stun:stun.l.google.com:19302]
```
I'm running mediamtx in docker like this:
```
docker run --rm -it --userns=host --network=host --mount type=bind,source="$(pwd)"/mediamtx.yml,target=/mediamtx.yml,readonly bluenviron/mediamtx:1.5.1
```

`172.16.1.2` is traefik which forwards requests from `https://mypublichostname/stream/ `to `192.168.1.2:1989/stream/`
I forwarded `udp://wanip:8189`  to `192.168.1.2:8189`

I start a ffmpeg stream ... I can view it just fine in HLS so that should be working fine.

In the browser (even locally directly to 192.168.1.2:1989/stream/ I see:
```
OPTIONS /whep # 204
POST /whep # 201
PATCH somerandomstring # 204
after some time
DELETE somerandomstring # 500
```

What did I miss?

**Comment by d3xt3r01** [comment]
Tried running coturn on the server and published its 3478 port and a range of ports for it to have forwarded. Still no luck.

**Comment by aler9** [comment]
Hello, in your configuration you are mixing `webrtcAdditionalHosts` and `webrtcICEServers2`, which are not supposed to be used together.

If you want to provide your users a fixed UDP or TCP port, which they can connect to, you have to open all firewalls towards that port (that by default is 8189 UDP), start from the default configuration and add `mypublichostname` and `192.168.1.2` to `webrtcAdditionalHosts`:

```yml
webrtcLocalUDPAddress: :8189
# Address of a local TCP listener that will receive connections.
# This is disabled by default since TCP is less efficient than UDP and
# introduces a progressive delay when network is congested.
webrtcLocalTCPAddress: ''
# WebRTC clients need to know the IP of the server.
# Gather IPs from interfaces and send them to clients.
webrtcIPsFromInterfaces: yes
# List of interfaces whose IPs will be sent to clients.
# An empty value means to use all available interfaces.
webrtcIPsFromInterfacesList: []
# List of additional hosts or IPs to send to clients.
webrtcAdditionalHosts: []
```

If instead you want to use the STUN method, in which sets of random ports are chosen from the client side and the server side, and the UDP hole punching technique is used to establish a connection, you have to use `webrtcICEServers2`:

```yml
webrtcICEServers2:
  - url: stun:stun.l.google.com:19302
```

If none of the methods described here and in the README works, use a TURN server. If that still doesn't work, it means that either the server or clients cannot access the single TCP port that is needed for the TURN server to work.

[a comment by an automated account is not shown]
