### DISCUSSION TITLE
can support generate MPEG-DASH?

### DISCUSSION THREAD

**Discussion by seamanm** [bluenviron/mediamtx#308] [Questions]
## Which version are you using?

v0.0.0

## Enhancement request

Description

**Comment by aler9** [comment]
Hello, DASH support can be added in the same way as HLS support can be added, through ffmpeg:

```yml
paths:
  dash:
    runOnPublish: ffmpeg -re -i rtsp://localhost:8554/$RTSP_SERVER_PATH -c copy -f dash dash/stream.mpd
```

[a comment by an automated account is not shown]
