### DISCUSSION TITLE
Store / save published stream on server

### DISCUSSION THREAD

**Discussion by botdot112** [bluenviron/mediamtx#309] [Questions]
## Which version are you using?

v0.14.1

## Question

Is there a way to store/ record all publishing streams on server?

**Comment by aler9** [comment]
Yes, you can use runOnPublish and ffmpeg to do so
```yml
paths:
  all:
    runOnPublish: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f mpegts $(date +'%s').ts 
    runOnPublishRestart: yes
```
