### DISCUSSION TITLE
Source: RTSP Path Issue

### DISCUSSION THREAD

**Discussion by t3therdev** [bluenviron/mediamtx#310] [Questions]
## Which version are you using?

v0.14.1

## Which operating system are you using?

OS

- [ ] Linux
- [X] Windows
- [ ] macOS

Architecture

- [ ] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

We are wanting to pull / proxy a remote stream.

We modify the config like this:
Paths:
   channel:
        source: record

and change to:

Paths:
   channel:
        source: rtsp://username:password@serverip:port/channel (rtsp://user:pass@192.168.1.100/chnnel1 example)

As soon as we save, the server console closes. What is the correct usage/syntax for specifying the remote rtsp URL?

**Comment by aler9** [comment]
Hello, the configuration looks fine to me, as long as it is

```yml
paths:
  channel:
    source: rtsp://username:password@serverip:port/channel
```

You have to find out the error that is causing the server to close and report it in the issue; for instance, you can use a log file

```yml
logDestinations: [file, stdout]

paths:
  channel:
    source: rtsp://username:password@serverip:port/channel
```

[a comment by an automated account is not shown]
