### DISCUSSION TITLE
FLV Video Ingest

### DISCUSSION THREAD

**Discussion by Tabarane** [bluenviron/mediamtx#3119] [General]
Hi, we have faced an issue where the video server is exporting only flv url for the video, is there a way where i can ingest the flv video to Mediamtx and export to rtsp?

**Comment by aler9** [comment]
Hello, yes, use FFmpeg inside `runOnInit`:

```yml
paths:
  mypath:
    runOnInit: ffmpeg -re -i http://my-flv-url -c copy -f rtsp rtsp://localhost:8554/mypath
```

The remuxed stream will be available in `rtsp://localhost:8554/mypath`

[a comment by an automated account is not shown]
