### DISCUSSION TITLE
Configuring DSCP on media streams

### DISCUSSION THREAD

**Discussion by cubisttriangle** [bluenviron/mediamtx#3147] [Questions]
### Question

Is it possible to configure DSCP values on media streams - RTP streams for example? Or does the system try to match DSCP values on incoming streams?

**Comment by aler9** [comment]
Hello, this is currently unimplemented - i've created a feature request here: #3319

In the meanwhile i think you can configure DSCP by using iptables as explained here:
https://serverfault.com/questions/811587/how-to-set-dscp-values-for-outgoing-traffic-from-my-linux-server-to-check-whethe

**Reply by cubisttriangle** [reply]
Thanks! I using mediamtx on windows, but I'm guessing there is a similar thing. I had a look at the config and I didn't see anything about UDP port ranges that would be used for rebroadcasting (I'm just doing RTSP streams).

Where would I find the port range used for RTP streams so I could potentially configure DSCP? I'd also be interested in trying to implement this feature if you have an idea about where/how to do it.

**Reply by aler9** [reply]
> Where would I find the port range used for RTP streams so I could potentially configure DSCP?

Normally they are picked up randomly from available ports, once for each connection, because every connection needs a dedicated pair.

This can be changed if you use the Multicast transport protocol. RTSP supports various underlying transport protocols, they are documented in the README, and there you can also find how to use the multicast transport protocol.

In multicast, these two ports are fixed and are defined in the configuration file:

```yml
# IP range of all UDP-multicast listeners. This is needed only when "multicast" is in protocols.
multicastIPRange: 224.1.0.0/16
# Port of all UDP-multicast/RTP listeners. This is needed only when "multicast" is in protocols.
multicastRTPPort: 8002
# Port of all UDP-multicast/RTCP listeners. This is needed only when "multicast" is in protocols.
multicastRTCPPort: 8003
```

[a comment by an automated account is not shown]
