### DISCUSSION TITLE
Dynamic recording path

### DISCUSSION THREAD

**Discussion by mohankumar-dev-2002** [bluenviron/mediamtx#3152] [Questions]
### Question

I like to know is that possible to divert the recording path for individual cameras ?

For instance, I have mediamtx installed in the central server and there are three different sites where each site have a bunch of cameras, so I want to store the camera recordings in a dir **(~/recordings/sitename/cameraname/)**  . Any response to this is highly apperciated

**Comment by aler9** [comment]
Hello, you customize on a camera-basis any parameter you want by moving parameters from `pathDefaults` to `paths.cameraName`, for instance:

```yml
paths:
  mycamera1:
    recordPath: ./recordings/site1/%path/%Y-%m-%d_%H-%M-%S-%f
  mycamera2:
    recordPath: ./recordings/site2/%path/%Y-%m-%d_%H-%M-%S-%f
```

[a comment by an automated account is not shown]
