### DISCUSSION TITLE
Please advise on firewall port openings

### DISCUSSION THREAD

**Discussion by davidrylance** [bluenviron/mediamtx#3167] [Questions]
### Question

Hi everybody,

Thank you for the amazing project! And great documentation!

The only thing I'm missing is a list of all ports that need to be opened in iptables/nftables (local firewall on a server) and on an external firewall between LANs (assuming the server is on a different LAN than a client connecting the server).

Looking at the documentation and sample https://github.com/bluenviron/mediamtx/blob/main/mediamtx.yml and assuming I didn't change any ports from the default values:

``` yaml
playback: yes # not default
playbackAddress: :9996

rtsp: yes
protocols: [udp, multicast, tcp]
encryption: "no"
rtspAddress: :8554
rtspsAddress: :8322
rtpAddress: :8000
rtcpAddress: :8001
multicastIPRange: 224.1.0.0/16
multicastRTPPort: 8002
multicastRTCPPort: 8003

rtmp: yes
rtmpAddress: :1935
rtmpEncryption: "no"
rtmpsAddress: :1936

hls: yes
hlsAddress: :8888
hlsEncryption: no

webrtc: yes
webrtcAddress: :8889
webrtcEncryption: no
webrtcLocalUDPAddress: :8189

srt: yes
srtAddress: :8890

paths:
# ....
```

These are the ports I think need to be opened:

* tcp: 9996
* tcp: 8554
* udp: 8000
* udp: 8001
* udp: 8002 - only on local firewall on the server
* udp: 8003 - only on local firewall on the server
* tcp: 1935
* tcp: 8888
* tcp: 8889
* udp: 8189
* tcp: 8890
