### DISCUSSION TITLE
Webcam not starting

### DISCUSSION THREAD

**Discussion by francisp2** [bluenviron/mediamtx#3175] [Questions]
### Question

Webcam not starting

## Which version are you using?

v1.6.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Webcam not starting

## Describe how to replicate the issue

1. start the server
/opt/mediamtx# v4l2-ctl --list-devices
USB PHY 2.0: USB CAMERA (usb-0000:07:1b.0-1):
        /dev/video0
        /dev/video1
        /dev/media0

## Did you attach the server logs?

[_mediamtx_logs.txt](https://github.com/bluenviron/mediamtx/files/14793573/_mediamtx_logs.txt)
[mediamtx.yml.txt](https://github.com/bluenviron/mediamtx/files/14793606/mediamtx.yml.txt)
[docker-compose.yaml.txt](https://github.com/bluenviron/mediamtx/files/14793610/docker-compose.yaml.txt)
yes 

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, you are unable to start the cameras because you are using the server inside Docker, and Docker isolates the software from the underlying hardware, including the cameras. If you want to use a camera from a software inside Docker, you have to expose the camera, i think it can be performed with the `--dev` flag, which in docker-compose is equivalent to the `devices` key:

```yml
services:
  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx:latest-ffmpeg
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - $PWD/conf:/conf:ro
    command: /conf/mediamtx.yml
    devices:
      - /dev/video0:/dev/video0
```

I don't know whether this configuration is enough, anyway there are tons of guides on the internet on how to access /dev/video* devices from inside Docker.

[a comment by an automated account is not shown]
