### DISCUSSION TITLE
regex positional variable in server name?

### DISCUSSION THREAD

**Discussion by gfrankliu** [bluenviron/mediamtx#3283] [Questions] [answered]
### Question

In the [examples](https://github.com/bluenviron/mediamtx?tab=readme-ov-file#proxy-requests-to-other-servers) of using regex, the positional variable like `$G1` is only in the target path. Can it be used for the target server name?

Something like:

```yml
paths:
  "~^proxy_([a-z0-9]+)_(.+)$":
    source: rtsp://$G1-server:8554/$G2
    sourceOnDemand: yes
```

All requests addressed to `rtsp://server:8854/proxy_server1_a` will be forwarded to `rtsp://server1-server:8854/a` and so on.
