### DISCUSSION TITLE
Delayed proxy

### DISCUSSION THREAD

**Discussion by sgjava** [bluenviron/mediamtx#332] [Questions]
## Which version are you using?

v0.15.0

## Question

This is a use case for me, I'm using various detection code on a camera substream (mjpeg) and using that to trigger recording a H265+ stream. I'd like a couple seconds of delay on the proxy side to capture what happened to trigger the recording. Is there a setting to create a delayed stream?

**Comment by aler9** [comment]
Hello, you can accomplish this by installing Gstreamer and using this configuration:

```yml
paths:
  mycamera:
    source: rtsp://url
    runOnInit: ffmpeg -re -i gst-launch-1.0 rtspsrc location=rtsp://127.0.0.1:8554/mycamera ! rtpjpegdepay ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 min-threshold-time=5000000000 ! rtspclientsink location=rtsp://127.0.0.1:8554/delayed
    runOnInitRestart: yes
```

Where `5000000000` is 5 secs in nanoseconds. The delayed stream will be available on /delayed.

[a comment by an automated account is not shown]
