### DISCUSSION TITLE
Still image while publisher is not available

### DISCUSSION THREAD

**Discussion by d3xt3r01** [bluenviron/mediamtx#3326] [Questions]
## Describe the feature

I would like a still image to be streamed if a publisher is not available on a specific path.
Currently I start a ffmpeg with a ffmpeg -f image2 -loop 1 -i nosignal.png -vcodec libx264 -f flv ... but that gets interrupted when the actual publisher starts and I have to add code to check if there's a stream in progress every few seconds, if not, start the image... but even then that means there are times when there is no publisher and no image and people have to refresh and that makes for a bad experience.
Also, even so, the stream ends and the player remains in a weird state... Instead of just continuing with the still image.
Is there another easy workaround?

**Comment by aler9** [comment]
Hello, you can use the `runOnNotReady` hook to start ffmpeg whenever there is no publisher:

```yml
paths:
  mypath:
    runOnNotReady: ffmpeg -f image2 -loop 1 -i nosignal.png -vcodec libx264 -f rtsp rtsp://localhost:8554/mypath
```

[a comment by an automated account is not shown]
