### DISCUSSION TITLE
Recording RTSP stream to remote path

### DISCUSSION THREAD

**Discussion by AlexCastroAlex** [bluenviron/mediamtx#3380] [Questions]
### Question

Hello, 

I have troubles trying to record RSTP stream to remote path. 

I tried with ffmpeg like this : 

```
paths:
  # example:
  # cam1hd:
    # source: rtsp://admin:pwd@172.26.1.10/Streaming/Channels/1
  cam1hd:
    source: rtsp://admin:pwd@172.26.1.10/Streaming/Channels/1
    record: yes
    recordPartDuration: 100ms
    recordFormat: fmp4
    runOnReady: >
        ./ffmpeg.exe -rtsp_transport tcp -i rtsp://admin:Abc12345@172.26.1.10/Streaming/Channels/1 -c copy -f segment -segment_time 600 copy \\192.168.10.4\myrecrdpath
    runOnReadyRestart: yes  
```
I don't really know if it is possible and also if my ffmpeg command is ok.

For information, i'm have mediamtx on windows.

Thanks in advance.

Regards
