### DISCUSSION TITLE
Proxy Playback

### DISCUSSION THREAD

**Discussion by whatnowangga** [bluenviron/mediamtx#3405] [Questions]
### Question

Hi,
i have a question about playback RTMP

if i start publish RTMP with key (im using uuid)
is it possible to get playback with different uuid or any other key?
cause i dont want to expose the key

**Comment by aler9** [comment]
Hello, in MediaMTX it's possible to set different credentials for publishers and users through `authInternalUsers`. For instance:

```yml
authInternalUsers:
- user: mypublisher
  pass: mypublisher
  permissions:
  - action: publish

- user: myreader
  pass: myreader
  permissions:
  - action: read
```

In this way readers won't be able to publish.

[a comment by an automated account is not shown]
