### DISCUSSION TITLE
Running mediamtx with WebRTC when offline

### DISCUSSION THREAD

**Discussion by qeroll** [bluenviron/mediamtx#3415] [Questions]
### Question

Hi,

I would like to run mediamtx on my laptop, an Ubuntu 20.04 laptop, in order to serve a WebRTC stream from an RTSP stream.
Can I use mediamtx even if my computer is offline / no even connected to a Network Cable or WiFi?
If so, can I use it on my LAN even if my LAN has no internet connection, so that other computers on the same LAN can view streams from each other?

**Comment by aler9** [comment]
Hello,

> Can I use mediamtx even if my computer is offline / no even connected to a Network Cable or WiFi?

Absolutely yes since #2686 removed the need for an external STUN server, which required internet access. The WebRTC implementation bundled inside MediaMTX can be used in offline networks.

**Reply by yairz-q** [reply]
Hey, 
I'm using the simplest yml i can and i tried using mediamtx webrtc offline (on my laptop, disconnected ethernet and disabled wifi)
I'm using mediamtx v1.3.1 on MacBook Air M2 (OS Version 14.5 (23F79))
here is my yml:
```
logLevel: debug
metrics: true
webrtcAdditionalHosts: [192.168.x.x, localhost, 127.0.0.1, 0.0.0.0]
webrtcLocalTCPAddress: :8189
webrtcLocalUDPAddress: :8190
paths:
  webcam:
    source: rtsp://127.0.0.1:8556/webcam
```

Is there another configuration i need to use?

[a comment by an automated account is not shown]
