### DISCUSSION TITLE
Local IP camera RTSP stream publish to public RTMP server

### DISCUSSION THREAD

**Discussion by foilandwater** [bluenviron/mediamtx#3473] [Questions]
### Question

Hi,

I'm sorry to ask a basic question but I can't seem to find the information anywhere.

I have a small computer running Ubuntu 24 and I've been trying to get a local IP camera stream (RTSP) to a public server which expects an RTMP stream. I have this working using OBS but the stream keeps freezing which is a known error with OBS. The solution is to use VLC input source but after days of struggling to compile VLC myself (to include live555 which isn't native to VLC packages on Ubuntu) I have given up. Admittedly, I have very limited knowledge with this stuff.

Now I have found mediamtx and I'm trying to set it up. I have installed it and added to the end of the .yml file under # Path settings: `source: rtsp://admin:admin12345@192.168.10.82:554//h264Preview_01_main` - the source is 1280x720 @ 10fps 2000kbps.

I'm just not sure where I should add the public RTMP server address within the .yml file? I have found a few posts online and it looks like I need to add some ffmpeg syntax as well - is that right?

Would appreciate any suggestions, thank you.

**Comment by aler9** [comment]
Hello, you are ingesting a RTSP camera, as documented here:

https://github.com/bluenviron/mediamtx?tab=readme-ov-file#rtsp-cameras-and-servers

what you are looking for is stream forwarding, which is documented here:

https://github.com/bluenviron/mediamtx?tab=readme-ov-file#forward-streams-to-other-servers

You just need to merge the two things together:

```yml
paths:
  mycamera:
    source: rtsp://admin:admin12345@192.168.10.82:554//h264Preview_01_main
    runOnReady: >
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH
      -c copy
      -f flv rtmp://my-rtmp-server/rtmp-server-path
    runOnReadyRestart: yes
```

[a comment by an automated account is not shown]
