### DISCUSSION TITLE
Logitech c290 at 1080p 30fps

### DISCUSSION THREAD

**Discussion by coolapso** [bluenviron/mediamtx#3482] [Questions] [answered]
### Question

Hi, apologies if this answer is elsewhere but I can't seem to find it. 

I have a logitech c290 connected to a raspberry pi, and I want to stream the video feed via RTSP. however with [the default example configuration](https://github.com/bluenviron/mediamtx?tab=readme-ov-file#generic-webcam) it only streams at 640x480 30 fps

The camera supports 1080p30fps however the video format needs to be with h.264 or motion-jpeg. when using yuv420p it only goes as far as 1080p5fps. Or at least when using it in OBS those were the only 2 video formats where I could get 1080p30fps. 

How can I set ffmpeg and mediamtx to stream in such format? I have played around with different settings but was not able to find a solution that works?

Thank you.

**Comment by coolapso** [comment, marked as answer]
Guess I found the solution ... leaving it here for others that may want to do the same: 

```
paths:
  cam:
    runOnInit: ffmpeg -f v4l2 -video_size 1920x1080 -input_format h264 -i /dev/video0 -c:v copy -b:v 600k -preset ultrafast -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
```

[a comment by an automated account is not shown]
