### DISCUSSION TITLE
Converting RTSP H.264 to RTSP M-JPEG

### DISCUSSION THREAD

**Discussion by DonGar** [bluenviron/mediamtx#3496] [Questions]
### Question

I'm trying to figure out how to convert RTSP with H.264 encoding to RTSP with M-JPEG encoding. I've been through the docs, and just haven't been able to work it out.

**Comment by aler9** [comment]
Hello, this is what you're looking for:

```yml
paths:
  compressed:
  original:
    source: my-source
    runOnReady: >
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH
        -c:v mjpeg -q:v 3 -f rtsp rtsp://localhost:$RTSP_PORT/compressed
    runOnReadyRestart: yes
```

FFmpeg is in charge of re-encoding things, not MediaMTX, therefore the right place where you can find the configuration is the FFmpeg documentation.

[a comment by an automated account is not shown]
