### DISCUSSION TITLE
Multiple qualities for hls stream with regexp (all) paths

### DISCUSSION THREAD

**Discussion by Satont** [bluenviron/mediamtx#3529] [Questions]
### Question

I have followed file:

```yml
api: yes

authMethod: http
externalAuthenticationURL: http://localhost:1337/streams/auth

hlsPartDuration: 500ms

paths:
  "~^(.+)$":
    runOnReady: sh -c 'while true; do ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -vframes 1 -y /thumbnails/$G1.jpg; sleep 10; done'
    runOnReadyRestart: yes
    runOnNotReady: rm -f /thumbnails/$G1.
 ```
 
My current logic is:
 1. I generating secret uuid key for stream path
 2. Users use this secret key for publish their streams
 3. i read this streams via hls.js, but via my proxied endpoints, so i'm hiding actual secret keys.
 
 What i want is: multiple qualities, so i can configure my frontend clients to choose between them.
 But also might bot good to keep thumbnails feature i used.

**Comment by Satont** [comment]
Which i did is 
```bash
#!/bin/bash

ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH \
  -vf scale=w=640:h=360:force_original_aspect_ratio=decrease \
  -c:v h264 \
  -sc_threshold 0 -g 48 -keyint_min 48 \
  -profile:v main \
  -b:v 800k -maxrate 856k -bufsize 1200k -b:a 96k \
  -max_muxing_queue_size 1024 \
  -f rtsp rtsp://localhost:$RTSP_PORT/360p_$G1 &

ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH \
  -vf scale=w=842:h=480:force_original_aspect_ratio=decrease \
  -c:v h264 \
  -sc_threshold 0 -g 48 -keyint_min 48 \
  -profile:v main \
  -b:v 1400k -maxrate 1498k -bufsize 2100k -b:a 128k \
  -max_muxing_queue_size 1024 \
  -f rtsp rtsp://localhost:$RTSP_PORT/480p_$G1 &

ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH \
  -vf scale=w=1280:h=720:force_original_aspect_ratio=decrease \
  -c:v h264 \
  -sc_threshold 0 -g 48 -keyint_min 48 \
  -profile:v main \
  -b:v 2800k -maxrate 2996k -bufsize 4200k -b:a 128k \
  -max_muxing_queue_size 1024 \
  -f rtsp rtsp://localhost:$RTSP_PORT/720p_$G1
```

```yml
api: yes

authMethod: http
externalAuthenticationURL: http://localhost:1337/streams/auth

hlsPartDuration: 500ms

paths:
  "~^.+p_(.{36})$":
  "~^(.{36})$":
    runOnReady: /opt/mediamtx/scripts/mediamtx-concurrent-compression.sh
    runOnReadyRestart: yes
    runOnNotReady: rm -f /thumbnails/$G1.jpg
```

But i dont know how to compute multiple streams into main `idnex.m3u8`.
