### DISCUSSION TITLE
From OBS to multiple rtmp destinations

### DISCUSSION THREAD

**Discussion by NaushBushi** [bluenviron/mediamtx#3531] [Questions]
### Question

Hi 
I am looking for a solution to stream to multiple rtmp destinations.
I have looked at the documentation but it is not clear if it is possible. 
I have tried to use ffmpeg but it is very unstable and keeps crashing.
Here is an example of what I'm trying to achieve: 
ffmpeg -listen 1 -i rtmp://127.0.0.1:5000/test -c copy -f flv $ODYSEE -c copy -f flv $RUMBLE -c copy -f flv $ENTROPY

**Comment by aler9** [comment]
This is possible by launching multiple FFmpeg instances inside `runOnReady`, as documented in the [README](https://github.com/bluenviron/mediamtx?tab=readme-ov-file#forward-streams-to-other-servers).

Example:

```yml
paths:
  mypath:
    source: rtmp://127.0.0.1:5000/test
    runOnReadyRestart: true
    runOnReady: sh -c "ffmpeg -i rtsp://localhost:8554/$MTX_PATH c copy -f flv rtmp://dest1 & ffmpeg -i rtsp://localhost:8554/$MTX_PATH -c copy -f flv rtmp://dest2 & ffmpeg -i rtsp://localhost:8554/$MTX_PATH -c copy -f flv rtmp://dest3 & wait"
```
