### DISCUSSION TITLE
Take snapshot through URL

### DISCUSSION THREAD

**Discussion by filamonkey** [bluenviron/mediamtx#3536] [General]
I have built a rPi Camera to monitor my 3D printers using mediamtx an rPi zero 2W. For this purpose, it works great. When defining the camera in Mainsail (front end to control the printers) you define both a stream URL (just used IP:8889/mycam) and a snapshot URL so you can do a timelapse with Moonraker (the underlying web server) while the toolhead is parked at a specified point.
I haven't managed to set this up. I have tried this:

`  mycam:
     source: rpiCamera
  snapshot:
    runOnRead: ffmpeg -i rtsp://localhost:8554/cam -frames 1 -y /tmp/out.jpg
    runOnReadRestart: yes
`

I have also tried runOnDemand with no luck.
Is there a way to accomplish this?

**Comment by eprouty** [comment]
So this is a bit hacky... would love to know a better way to do this, but it's working for anyone else that needs this:

Setup ffmpeg to produce a new snapshot jpg by adding the following to your `cam:` definition.  This will update the snapshot every X seconds as defined by the `-r` flag, for this example it's 1 fps:
```
    runOnReady: ffmpeg -i rtsp://localhost:8554/cam -r 1 -update 1 -y /home/eprouty/mainsail/snapshot.jpg
    runOnReadyRestart: yes
```
 
This snapshot gets stored in your `mainsail` directory which Nginx should already be setup to serve files from.  So now if you go to http://your.mainsail.addr/snapshot.jpg, it should serve you the most recent snapshot.  That file will be continually over written in the background so this does require a decent bit of cpu.

Now as long as you tune the `-r` to be frequent enough to always have a new image for you, than you should be able to do timelapses.

**Comment by bs76** [comment]
Here is my take. I use RPI cam module v3 in low light settings without IR. The cam stream is  setup to stream on-demand  

- run ffpmeg to get 30 frames 
- run imagemagick to blend images into single one

```
td=$(mktemp -d)

mkdir -p $td

ffmpeg -i rtsp://localhost:8554/cam -frames 30 -y  $td/snapshot_%02d.jpg
convert $td/snapshot_*.jpg -scale 50% -evaluate-sequence mean $td/snapshot.jpg

mv $td/snapshot.jpg /var/www/html/cam/snapshot.jpg

rm -rf $td

```

**Reply by bs76** [reply]
Update: As I have more cams, incl. 3d printer *and* and I want seemless integration with HomeAssistant I crammed all my cams under go2rtc. It autocamtically provides a 'screenshot' endpoint.

**Comment by edalquist** [comment]
Adding my 2 cents. I'm using mediamtx to expose a rpi camera for Prusa Connect as well as local streaming. To dump a static image for Prusa I'm having it capture key frames, this seems to be the lowest CPU impact on the Raspberry Pi 4

```
paths:
  cam:
    source: rpiCamera
    rpiCameraFPS: 15
    rpiCameraAfRange: macro
    rpiCameraExposure: short
    rpiCameraJPEGQuality: 80
    rpiCameraTextOverlayEnable: true
    rpiCameraTextOverlay: '%Y-%m-%d %H:%M:%S'
    runOnReady: ffmpeg -hwaccel drm -y -i rtsp://localhost:$RTSP_PORT/$MTX_PATH -vf "select='eq(pict_type,I)'" -vsync 0 -f image2 -update 1 /dev/shm/prusa-cam/$MTX_PATH-snapshot.jpg
    runOnReadyRestart: yes
```

This uses about 60% of one core on a rPi 4 and gives me one frame every 3 seconds. I'm writing these to /dev/shm since they don't need to survive a restart and that saves actual file system wear.
