### DISCUSSION TITLE
I am sharing my experience with taking JPG snapshots from mediamtx/rtsp_simple_server.

### DISCUSSION THREAD

**Discussion by jcmichot** [bluenviron/mediamtx#3544] [General]
For several years, I have been using external equipment to trigger 
actions (PIR detectors, contact sensors, etc.).

I have tested various methods to obtain a snapshot from video cameras 
(Reolink and other brands) at a specific moment. Sometimes this was
done with a simple wget on the camera's URL, sometimes by setting
up an RTSP stream and capturing an image with ffmpeg, or by running
ffmpeg continuously to take snapshots every second, etc.

Overall, I was not satisfied with these solutions, as establishing 
an RTSP connection takes time. For example, with a PIR motion
detection, the snapshot would sometimes be taken after the person
had already passed, or significant resources were consumed, such
as running ffmpeg 100% of the time to take snapshots.

I eventually found a solution that requires few resources and is 
very responsive for obtaining one or more snapshots during an event.

I'm sharing it in case it might be useful to others.

1/ I use mediamtx to record the video stream from the cameras.

2/ During an event (PIR detection, opening a gate or door, etc.), 
I trigger a script with ffmpeg to take a snapshot from the last few
seconds of recording.

The basic idea example:

ffmpeg -hide_banner -loglevel quiet -y -sseof -1 /mediamtx/camera/parking_hd.mp4 -frames:v 1 -y -strftime 1 /mediamtx/jpg/parking_snap.jpg

I have a more complete script if anyone is interested, but I believe 
this is the right method as it requires fewer resources compared
to other solutions I have tested and which are frequently mentioned
in this forum.

**Comment by filamonkey** [comment]
Thanks for sharing. I am interested, in fact I had posted earlier this week: https://github.com/bluenviron/mediamtx/discussions/3536
I however need to be able to trigger the capture through an URL so a timelapse script can capture the image at a precise moment.

**Comment by saket424** [comment]
@jcmichot 

I am interested in your more complete script. I'd then like to add self hosted openai API compatible text annotation of the snap to it. Thanks

**Comment by jcmichot** [comment]
@saket424 @filamonkey my script an few explaination. My mediamtx.yml configuration contain:

```
pathDefaults:
  # Record streams to disk.
  record: yes
  # Extension is added automatically.
  # Available variables are %path (path name), %Y %m %d %H %M %S %f %s (time in strftime format)
  recordPath: /motion/24/mp4/%Y%m%d-%H%M%S-%f-%path
  # Format of recorded segments.
  # Available formats are "fmp4" (fragmented MP4) and "mpegts" (MPEG-TS).
  recordFormat: fmp4
  # fMP4 segments are concatenation of small MP4 files (parts), each with this duration.
  # MPEG-TS segments are concatenation of 188-bytes packets, flushed to disk with this period.
  # When a system failure occurs, the last part gets lost.
  # Therefore, the part duration is equal to the RPO (recovery point objective).
  recordPartDuration: 1s
  # Minimum duration of each segment.
  #recordSegmentDuration: 1h
  recordSegmentDuration: 15m
  # Delete segments after this timespan.
  # Set to 0s to disable automatic deletion.
  #recordDeleteAfter: 24h
  recordDeleteAfter: 0s
  # Keep 15 Days => crontab include: 30 20 * * * root (/usr/bin/find /home/camera -type f -mtime +15 -exec rm {} \;)
```

And RTSP camera exemple:

  parking_hd:
    source: rtsp://192.168.78.63:554/1
    sourceProtocol: tcp


The file in my /motion/24/mp4/ directory look like:

-rw-r--r--  1 root  wheel   214M Aug 18 17:51 20240818-175105-738338-parking_hd.mp4
-rw-r--r--  1 root  wheel   148M Aug 18 17:51 20240818-173946-036545-office_hd.mp4
-rw-r--r--  1 root  wheel   120M Aug 18 17:51 20240818-174609-450720-garage_sd.mp4
-rw-r--r--  1 root  wheel   305M Aug 18 17:51 20240818-175100-419329-garden_hd.mp4

The little script from my FreeBSD system (also attached as .TXT)

```
# This is a shell archive.  Save it in a file, remove anything before
# this line, and then unpack it by entering "sh file".  Note, it may
# create directories; files and directories will be owned by you and
# have default permissions.
#
# This archive contains:
#
#       ./snap_from_record.sh
#
echo x - ./snap_from_record.sh
sed 's/^X//' >./snap_from_record.sh << '7a54b5dac9e4a8354ef185c800b83b32'
X#!/bin/sh
X
Xif [ -z "$1" ] || [ -z "$2" ]; then
X  echo "usage error: $ snap_from_record camera filename.jpg"
X  exit 1
Xfi
X
Xecho "% $0 $1 $2"
X
X#set -x
X
X# $1 parking_hd garden_hd etc.
X# $2 /tmp/filename.jpg
X
XCAMERA=$1
XOUTJPG=$2
X
XPAT="`date +"%Y%m%d"`*$CAMERA*"
Xecho "PAT: $PAT";
X
Xlatest_file=$(/bin/ls -1t /motion/24/mp4/$PAT | /usr/bin/head -n 1)
X
Xif [ -z "$latest_file" ] || [ ! -f "$latest_file" ]; then
X  echo "error: no $CAMERA file ?"
X  echo "lastest_file=$latest_file"
X  exit 1
Xfi
X
Xecho "process $CAMERA filename: $latest_file "
X/bin/ls -la $latest_file
X
Xrm -f $OUTJPG
X
X# delay to avoid EOF of image before end of jpg. (sometime the end of jpeg is garbage because EOF of mp4 or data not yet flushed)
X# don't worry delay (later we will request a -1 seconds time)
Xsleep 1
X
X# loop to retry if capture faild
Xfor step in 1 2 3 4 5 10 20 30
Xdo
X
X# ffmpeg -sseof (n) n=nombre de seconde(s) avant la fin du fichier
X#ffmpeg -hide_banner -loglevel quiet -y -sseof -1 -i $latest_file -frames:v 1 -y -strftime 1 $OUTJPG 
X
Xecho "/usr/local/bin/ffmpeg -hide_banner -loglevel quiet -y -sseof -$step -i $latest_file -frames:v 1 -y -strftime 1 $OUTJPG"
X
X/usr/local/bin/ffmpeg -hide_banner -loglevel quiet -y -sseof -$step -i $latest_file -frames:v 1 -y -strftime 1 $OUTJPG 
X
X# something fail, retry in loop otherwise exit 0
X if [ -f "$OUTJPG" ]; then
X       ls -l $OUTJPG
X       exit 0;
X else
X       FFEXIT="$?"
X       echo -n "Err $? =>"
X       ls -l $OUTJPG
X fi
Xdone
X
Xecho "" >>  /tmp/snap_debug.txt
Xdate >> /tmp/snap_debug.txt
Xecho echo "process $CAMERA filename: $latest_file " >> /tmp/snap_debug.txt
Xecho echo "outjpg $OUTJPG " >> /tmp/snap_debug.txt
X/bin/ls -la $latest_file >> /tmp/snap_debug.txt
X/bin/ls -la $OUTJPG  >> /tmp/snap_debug.txt
Xecho "ffmpeg -hide_banner -loglevel quiet -y -sseof -$step -i $latest_file -frames:v 1 -y -strftime 1 $OUTJPG " >> /tmp/snap_debug.txt
Xecho "FFEXIT $FFEXIT" >> /tmp/snap_debug.txt
X
7a54b5dac9e4a8354ef185c800b83b32
exit

```
[snap_from_record.sh.TXT](https://github.com/user-attachments/files/16649902/snap_from_record.sh.TXT)
