### DISCUSSION TITLE
How to configure rpicamera to runOnDemand?

### DISCUSSION THREAD

**Discussion by suomi35** [bluenviron/mediamtx#3562] [Questions] [answered]
### Question

I have a Raspberry Pi zero 2 W setup, running with a camera. It works fine with the following config, taken from the example:
```
paths:
  cam:
    source: rpiCamera
    runOnReady: >
      gst-launch-1.0
      rtspclientsink name=s location=rtsp://localhost:$RTSP_PORT/cam_with_audio
      rtspsrc location=rtsp://127.0.0.1:$RTSP_PORT/$MTX_PATH latency=0 ! rtph264depay ! s.
      alsasrc device=hw:0 ! opusenc bitrate=16000 ! s.
    runOnReadyRestart: yes
  cam_with_audio:
``` 
However, I don't want the camera to stream when not requested. (It heats up the rPi and adds unwanted traffic to my network.)
I have tried to modify the config with variations of sourceOnDemand/runOnDemand, but I get the following error:
```
ERR: 'runOnDemand' and 'runOnUnDemand' can be used only when source is 'publisher'
```
Does anyone have a working on-demand config that works for rpicamera?

**Comment by suomi35** [comment]
I think I may try to solve this via the API; adding/deleting a path on demand...

**Reply by zinahe** [reply]
Hi,

Did you make any progress on this issue? I am also running a Raspberry Pi zero 2W setup, which is running hot 24/7 even when there are no clients connected. It would be ideal if video capture only happens when there is demand for a stream.

Cheers,

**Reply by aler9** [reply]
no API is needed, there's option `sourceOnDemand` that does exactly what you want:

```yml
paths:
  cam:
    source: rpiCamera
    sourceOnDemand: true
```

**Comment by aler9** [comment]
@suomi35 the Raspberry Pi camera can be enabled and disabled on-demand by using `sourceOnDemand: true`, but the problem of your configuration is that `gst-launch-1.0` is constantly reading the video stream in order to add audio, therefore the camera is always in use. Move `gst-launch-1.0` inside the `runOnDemand` section of `cam_with_audio` and enable `sourceOnDemand` inside `cam`:

```yml
paths:
  cam:
    source: rpiCamera
    sourceOnDemand: true

  cam_with_audio:
    runOnDemand: >
      gst-launch-1.0
      rtspclientsink name=s location=rtsp://localhost:$RTSP_PORT/cam_with_audio
      rtspsrc location=rtsp://127.0.0.1:$RTSP_PORT/cam latency=0 ! rtph264depay ! s.
      alsasrc device=hw:0 ! opusenc bitrate=16000 ! s.
    runOnDemandRestart: yes


```

**Reply by suomi35** [reply]
@aler9 thank you for this, however now I get the following error:
`ERR: json: cannot unmarshal bool into Go struct field alias.paths of type string`

**Reply by aler9** [reply]
you didn't paste the indentation properly. For additional information, take a look at the README and into the configuration file, where all parameters are commented.

**Reply by suomi35** [reply]
<img width="824" alt="Screenshot 2024-08-13 at 10 27 56" src="https://github.com/user-attachments/assets/0bd01a8b-b669-48cf-acf7-c4d2d445ab31">
I was initially suspicious of that as well, but I believe the formatting is correct.

**Reply by aler9** [reply, marked as answer]
the second `runOnDemand` must be `runOnDemandRestart`:

```yml
paths:
  cam:
    source: rpiCamera
    sourceOnDemand: true

  cam_with_audio:
    runOnDemand: >
      gst-launch-1.0
      rtspclientsink name=s location=rtsp://localhost:$RTSP_PORT/cam_with_audio
      rtspsrc location=rtsp://127.0.0.1:$RTSP_PORT/cam latency=0 ! rtph264depay ! s.
      alsasrc device=hw:0 ! opusenc bitrate=16000 ! s.
    runOnDemandRestart: yes
```
