### DISCUSSION TITLE
Does MediaMTX already support ESP32 based cameras using by default in M-JPEG over HTTP ?

### DISCUSSION THREAD

**Discussion by ohault** [bluenviron/mediamtx#3575] [Questions]
### Question

By default, most ESP32 based cameras use M-JPEG over HTTP to "stream" video feed.

Such video feed can be accessed from a webpage by using a simple HTML img embed element with a src attribute pointing to the URL of the streaming URL of the camera (over Wifi)

e.g. http://a.b.c.d/stream

Does MediaMTX already support this scenario for input feeds ?

**Comment by aler9** [comment]
you can use FFmpeg inside `runOnInit` to pull these these HTTP-based feeds and ingest them into the server:

```yml
paths:
  esp32:
    runOnInit: ffmpeg -i http://a.b.c.d/stream -c copy -f rtsp rtsp://localhost:8554/esp32

```

[a comment by an automated account is not shown]
