### DISCUSSION TITLE
FPS

### DISCUSSION THREAD

**Discussion by 4noxx** [bluenviron/mediamtx#3579] [Questions]
### Question

how can i increase the fps of my cam?

i use on my PI5 

```
paths:
  cam:
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -pix_fmt yuv420p -preset ultrafast -b:v 600k -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes

```
Output shows:
`Stream #0:0: Video: mpeg4, yuv420p(tv, progressive), 1280x720, q=2-31, 600 kb/s, 10 fps, 90k tbn`

-> 10fps

i had try "-g 30" but dont work

camera is a 
Viewsonic VB-CAM-001

**Comment by aler9** [comment]
Hello, you are missing the `-c:v libx264` flag, hence you are using the MPEG-4 video codec instead of H264.

The suggested FFmpeg command is present inside the README:

```yml
paths:
  cam:
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -c:v libx264 -pix_fmt yuv420p -preset ultrafast -b:v 600k -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
```
