### DISCUSSION TITLE
Save keyframes to files

### DISCUSSION THREAD

**Discussion by reloadman** [bluenviron/mediamtx#3600] [Questions] [answered]
### Question

I want to store all keyframes for the selected RTSP stream in H264 and H265 codecs.
Is there a way to save all keyframes of the selected stream to files?

**Comment by aler9** [comment, marked as answer]
Yes, use ffmpeg inside `runOnReady`:

```yml
paths:
  mypath:
    runOnReady: >
      ffmpeg -skip_frame nokey -i rtsp://localhost:8554/mypath -vsync 0 -r 30 -f image2 thumbnails-%02d.jpeg
```

Command was taken from https://superuser.com/questions/669716/how-to-extract-all-key-frames-from-a-video-clip

[a comment by an automated account is not shown]
