### DISCUSSION TITLE
Nesting of paths?

### DISCUSSION THREAD

**Discussion by Torstein-Eide** [bluenviron/mediamtx#363] [Questions]
Hi
This is exactly what I was looking for. What great tool you guys have made. 

For the `paths`, does it support Nesting for url with "/", or sharing of settings 
````yml
paths:
  SiteA:
     CameraA:
     cameraB:
````
