### DISCUSSION TITLE
How to specify multiple path in the json file?

### DISCUSSION THREAD

**Discussion by vertexgamer** [bluenviron/mediamtx#3716] [Questions]
### Question

using this method for allowing anonymous users to view only 3 paths returns me this error: `ERR: json: cannot unmarshal array into Go struct field alias.authInternalUsers of type string`
```
- user: any
  # Password. Not used in case of 'any' user.
  pass:
  # IPs or networks allowed to use this user. An empty list means any IP.
  ips: []
  # List of permissions.
  permissions:
    # Available actions are: publish, read, playback, api, metrics, pprof.
  - action: read
    # Paths can be set to further restrict access to a specific path.
    # An empty path means any path.
    # Regular expressions can be used by using a tilde as prefix.
    path: ['one', 'two', 'three']
```

**Comment by aler9** [comment]
Use regular expressions:

```yml
- user: any
  # Password. Not used in case of 'any' user.
  pass:
  # IPs or networks allowed to use this user. An empty list means any IP.
  ips: []
  # List of permissions.
  permissions:
    # Available actions are: publish, read, playback, api, metrics, pprof.
  - action: read
    # Paths can be set to further restrict access to a specific path.
    # An empty path means any path.
    # Regular expressions can be used by using a tilde as prefix.
    path: ~(one|two|three)
```
