### DISCUSSION TITLE
How to publish multiple hls streams

### DISCUSSION THREAD

**Discussion by ashishgupta-mca** [bluenviron/mediamtx#373] [Questions]
I want to publish stream0 to playlist.m3u8 and stream1 to playlist1.m3u8. What will be its syntax?

I tried below in yml file but it doesn't work.

paths:
  all:
    runOnPublish: ffmpeg -i rtsp://admin:WeLcome@:8554/stream0 -c:a aac -b:a 64k -c:v libx264 -preset ultrafast -b:v 500k -f hls -hls_time 1 -hls_list_size 3 -hls_flags delete_segments -hls_allow_cache 0 playlist.m3u8
    runOnPublishRestart: yes  
    runOnPublish: ffmpeg -i rtsp://admin:WeLcome@:8554/stream1 -c:a aac -b:a 64k -c:v libx264 -preset ultrafast -b:v 500k -f hls -hls_time 1 -hls_list_size 3 -hls_flags delete_segments -hls_allow_cache 0 playlist1.m3u8

**Comment by aler9** [comment]
Hello, use a `runOnPublish` for each path, in this way

```yml
paths:
  stream0:
   runOnPublish: ffmpeg -i rtsp://admin:WeLcome@:8554/stream0 -c:a aac -b:a 64k -c:v libx264 -preset ultrafast -b:v 500k -f hls -hls_time 1 -hls_list_size 3 -hls_flags delete_segments -hls_allow_cache 0 playlist.m3u8
    runOnPublishRestart: yes

  stream1:
    runOnPublish: ffmpeg -i rtsp://admin:WeLcome@:8554/stream1 -c:a aac -b:a 64k -c:v libx264 -preset ultrafast -b:v 500k -f hls -hls_time 1 -hls_list_size 3 -hls_flags delete_segments -hls_allow_cache 0 playlist1.m3u8
    runOnPublishRestart: yes
```

[a comment by an automated account is not shown]
