### DISCUSSION TITLE
Problem using CUDA under WSL/Ubuntu24.04 - mediamtx(default tag)

### DISCUSSION THREAD

**Discussion by notsuchus** [bluenviron/mediamtx#3810] [Questions]
### Question

There is a Docker Compose application with real-time decoding of video streams as part of its functionality.

In the product environment Ubuntu Server 24.04 LTS is used together with NVIDIA GPU (different boards). Drivers, nvidia-container-toolkit, nvidia-docker2 are installed. Dockerfile based container (below) works fine in this environment.

Dockerfile:
```dockerfile
FROM harbor.eds.loc/chimera-4z1/ffmpeg:4.4-nvidia

WORKDIR /workdir

COPY --from=bluenviron/mediamtx /mediamtx /
COPY --from=bluenviron/mediamtx /mediamtx.yml /

ENTRYPOINT [ “/mediamtx” ]
```
mediamtx.yaml:
```yaml
logLevel: debug
logDestinations: [file]
logFile: /var/log/mediamtx/mediamtx.log

readTimeout: 10s
writeTimeout: 10s
readBufferCount: 512
udpMaxPayloadSize: 1472

externalAuthenticationURL:

api: no
apiAddress: 127.0.0.1:9997

metrics: no
metricsAddress: 127.0.0.1:9998

pprof: no
pprofAddress: 127.0.0.1:9999

runOnConnect:
runOnConnectRestart: no


rtspDisable: no
protocols: [tcp]
encryption: "optional"
rtspAddress: :8554
rtspsAddress: :8322
rtpAddress: :8000
rtcpAddress: :8001
multicastIPRange: 224.1.0.0/16
multicastRTPPort: 8002
multicastRTCPPort: 8003
serverKey: /etc/letsencrypt/dev/dev4z1.key
serverCert: /etc/letsencrypt/dev/dev4z1.crt
authMethods: [basic]


rtmpDisable: yes
rtmpAddress: :1935
rtmpEncryption: "no"
rtmpsAddress: :1936
rtmpServerKey: server.key
rtmpServerCert: server.crt


hlsDisable: yes
hlsAddress: :8888
hlsEncryption: no
hlsServerKey: server.key
hlsServerCert: server.crt
hlsAlwaysRemux: no
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsSegmentMaxSize: 50M
hlsAllowOrigin: '*'
hlsTrustedProxies: []
hlsDirectory: ''


webrtcDisable: yes
webrtcAddress: :8889
webrtcEncryption: no
webrtcServerKey: server.key
webrtcServerCert: server.crt
webrtcAllowOrigin: '*'
webrtcTrustedProxies: []
webrtcICEServers: [stun:stun.l.google.com:19302]
webrtcICEHostNAT1To1IPs: []
webrtcICEUDPMuxAddress:
webrtcICETCPMuxAddress:


paths:
  all:
    source: publisher


    sourceFingerprint:
    sourceOnDemand: no
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 10s


    publishUser:
    publishPass:
    publishIPs: []

    readUser:
    readPass:
    readIPs: []


    disablePublisherOverride: no
    fallback:


    sourceProtocol: automatic
    sourceAnyPortEnable: no
    rtspRangeType:
    rtspRangeStart:


    sourceRedirect:


    rpiCameraCamID: 0
    rpiCameraWidth: 1920
    rpiCameraHeight: 1080
    rpiCameraHFlip: false
    rpiCameraVFlip: false
    rpiCameraBrightness: 0
    rpiCameraContrast: 1
    rpiCameraSaturation: 1
    rpiCameraSharpness: 1
    rpiCameraExposure: normal
    rpiCameraAWB: auto
    rpiCameraDenoise: "off"
    rpiCameraShutter: 0
    rpiCameraMetering: centre
    rpiCameraGain: 0
    rpiCameraEV: 0
    rpiCameraROI:
    rpiCameraTuningFile:
    rpiCameraMode:
    rpiCameraFPS: 30
    rpiCameraIDRPeriod: 60
    rpiCameraBitrate: 1000000
    rpiCameraProfile: main
    rpiCameraLevel: '4.1'
    rpiCameraAfMode: auto
    rpiCameraAfRange: normal
    rpiCameraAfSpeed: normal
    rpiCameraLensPosition: 0.0
    rpiCameraAfWindow:
    rpiCameraTextOverlayEnable: false
    rpiCameraTextOverlay: '%Y-%m-%d %H:%M:%S - MediaMTX'


    runOnInit:
    runOnInitRestart: no

    runOnDemand:
    runOnDemandRestart: no
    runOnDemandStartTimeout: 10s
    runOnDemandCloseAfter: 10s

    runOnReady: docker run --rm --network=host --gpus=all harbor.eds.loc/chimera-4z1/ffmpeg:4.4-nvidia -hide_banner -loglevel panic -hwaccel nvdec -rtsp_transport tcp -i rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH -an -vcodec h264_nvenc -tune ll -f flv rtmp://127.0.0.1/app/$RTSP_PATH
    runOnReadyRestart: no

    runOnRead:
    runOnReadRestart: no
```

The problems start when using this application under WSL with Ubuntu 22.04 LTS.
The output is as follows:

```bash
shas@DESKTOP-ER8B8V2:/opt/chimera_prod$ docker logs mediamtx -f
ffmpeg version 4.4.2 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-avresample --enable-cuda --enable-cuvid --enable-fontconfig --enable-gpl --enable-libaom --enable-libaribb24 --enable-libass --enable-libbluray --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libnpp --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libsrt --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-libzmq --enable-nonfree --enable-nvenc --enable-openssl --enable-postproc --enable-shared --enable-small --enable-version3 --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/' --extra-libs=-ldl --extra-libs=-lpthread --prefix=/opt/ffmpeg
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/group10':
  Metadata:
    title           : No Name
  Duration: N/A, start: 0.067289, bitrate: N/A
  Stream #0:0: Video: hevc, yuv420p(tv), 1920x1080, 90k tbr, 90k tbn, 90k tbc
[AVHWDeviceContext @ 0x55feaee56740] Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x55feaee56740] Could not dynamically load CUDA
Device creation failed: -1313558101.
[hevc @ 0x55feaee5b600] No device available for decoder: device type cuda needed for codec hevc.
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
Device setup failed for decoder on input stream #0:0 : Unknown error occurred
```

What are the options for solving the problem?
