### DISCUSSION TITLE
Storage

### DISCUSSION THREAD

**Discussion by BharadwajManne** [bluenviron/mediamtx#3823] [General]
If I have Cameras 1, 2, 3, 4, and 5, I want to view the live feed from all five but store recordings only from Cameras 2 and 5. Is there a way to stop storage for specific cameras in MediaMTX?

**Comment by RedShift1** [comment]
You can set a `record` parameter per path

**Comment by aler9** [comment]
You can set the record setting individually for each camera:

```yml
paths:
  cam1:
    source: ...
    record: no

  cam2:
    source: ...
    record: yes

  cam3:
    source: ...
    record: no
```
