### DISCUSSION TITLE
Control and Metrics APIs asking for authentication despite not configuring for it

### DISCUSSION THREAD

**Discussion by OIZid** [bluenviron/mediamtx#3841] [Questions]
### Question

I took the default config file, changed only api and metrics to yes, and whenever I try to access them through http://localhost:9997/v3/paths/list or localhost:9998/metrics, it prompts for username and password on a browser, or returns 401 with curl.
What am I doing wrong here?

**Comment by tcamise-gpsw** [comment]
Same question here.

**Comment by aler9** [comment]
By default, access to API and metrics is granted to localhost only. If you are using the server through Docker without the `--network=host` flag, incoming requests are not from localhost but from a different IP. 

A solution consists in using the `--network=host` flag when launching the docker image. This will not work on Windows due to Docker-related limitations.

The alternative solution is to enable access to API and metrics through any IP. Setting a user and password is strongly encouraged:

```yml
authInternalUsers:
- user: any
  pass:
  ips: []
  permissions:
  - action: publish
    path:
  - action: read
    path:
  - action: playback
    path:

- user: myuser
  pass: mypass
  ips: []
  permissions:
  - action: api
  - action: metrics
  - action: pprof
```
