### DISCUSSION TITLE
Single input stream, multiple outputs

### DISCUSSION THREAD

**Discussion by Alfiegerner** [bluenviron/mediamtx#398] [Questions]
Hi,

I have a cam that had limited rtsp support (wyze) that can't really haven't more than 1 connection at a time 

Proxy support is great for this. Now I'm wondering if rtsp-simple-server can output 2 streams:

1. Direct proxy
2. Compressed rencode with lower resolution and 5fps

2 is for frigate object detection.  I think it looks possible but not sure what the config would look like.

Thanks.

**Comment by aler9** [comment]
Yes, of course, as written in the [README](https://github.com/aler9/rtsp-simple-server#remuxing-re-encoding-compression), you can do something like this:

```yml
paths:
  direct:
    source: rtsp://cameraurl

  compressed:
    runOnInit: ffmpeg -i rtsp://localhost:8554/direct -filter:v fps=5 -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/compressed
    runOnInitRestart: yes
```

You can access the original stream with `rtsp://localhost:8554/direct`, and the compressed stream with `rtsp://localhost:8554/compressed`
