### DISCUSSION TITLE
multicast : one address/port per path

### DISCUSSION THREAD

**Discussion by ZeroVital** [bluenviron/mediamtx#3987] [Questions]
### Question

Hello, 
we have 2 stream from 2 gstreamer pipeline that use rtspclientsink, each one has its path
we would like to use these 2 stream, each one with one multicast address and one port
We ve been achieving that with 2 mediamtx, but are scared there are some interference between the two.
Is it possible to achieve what we want with only 1 mediamtx ?
thank you for your support

**Comment by aler9** [comment]
Hello, it's perfectly possible to broadcast two different streams with RTSP/multicast from MediaMTX to any connected reader, and it doesn't require any server-side configuration.

Let's suppose you have two streams:

```yml
paths:
  stream1:
  stream2:
```

If you take a look at the default configuration, you will notice these lines:

```yml
# IP range of all UDP-multicast listeners. This is needed only when "multicast" is in rtspTransports.
multicastIPRange: 224.1.0.0/16
# Port of all UDP-multicast/RTP listeners. This is needed only when "multicast" is in rtspTransports.
multicastRTPPort: 8002
# Port of all UDP-multicast/RTCP listeners. This is needed only when "multicast" is in rtspTransports.
multicastRTCPPort: 8003
```

When a reader wants to read `stream1` and requests the multicast transport protocol, server will start broadcasting it with IP `224.1.0.1` and port 8002/8003.
When a reader wants to read `stream2` and requests the multicast transport protocol, server will start broadcasting it with IP `224.1.0.2` and port 8002/8003.
There is no interference between the two streams.
