### DISCUSSION TITLE
Does MediaMTX has a reconnection feature?

### DISCUSSION THREAD

**Discussion by emre570** [bluenviron/mediamtx#4037] [Questions] [answered]
### Question

Hello, I use 3 TP-Link Tapo C510W cams, with multiple ESP32 Wrover cameras with assigned static IP addresses. I use FFmpeg with CUDA for push the streams of ESP32s to MediaMTX, then I show the stream from MediaMTX in a HTML page. What I want to learn is, does MediaMTX have the ability to reconnect if these cameras are disconnected? Any ideas for how do I implement it? FFmpeg has reconnection feature but I didn't quite get it right. I use MediaMTX 1.9.3 in Ubuntu 22.04. Here is my config file:

```
...

camera3:
    source: rtsp://tapo-3:tapo123@192.168.1.222:554/stream1
    #runOnInit: > 
      #ffmpeg -hwaccel cuda -i rtsp://tapo-3:tapo123@192.168.1.222:554/stream1 -c:v h264_nvenc -reconnect_at_eof 1 -reconnect_delay_max 36000 -preset p2 -f rtsp rtsp://192.168.1.112:8554/camera3
    #runOnInitRestart: yes
    sourceOnDemand: yes

  camera4:
    #source: rtsp://192.168.1.112:8554/camera4
    runOnInit: > 
      ffmpeg -hwaccel cuda -i http://192.168.1.211:81/stream -c:v h264_nvenc -reconnect_at_eof 1 -reconnect_delay_max 36000 -preset p2 -f rtsp rtsp://192.168.1.112:8554/camera4
    runOnInitRestart: yes
    #sourceOnDemand: yes

  camera5:
    #source: rtsp://192.168.1.112:8554/camera5
    runOnInit: > 
      ffmpeg -hwaccel cuda -i http://192.168.1.212:81/stream -c:v h264_nvenc -reconnect_at_eof 1 -reconnect_delay_max 36000 -preset p2 -f rtsp rtsp://192.168.1.112:8554/camera5
    runOnInitRestart: yes
    #sourceOnDemand: yes

...
```
