### DISCUSSION TITLE
How to Set Timezone in Docker Container via Docker-Compose

### DISCUSSION THREAD

**Discussion by piyushpranjal03** [bluenviron/mediamtx#4083] [Questions] [answered]
### Question

Hi everyone,

I am using a docker compose file to run mediamtx image on raspberry-pi 4b. My local pi timezone is `Asia/Kolkata` but the docker default timezone is `UTC` and because of this all videos names are generated according to UTC timezone.

I tried to setup `TZ=Asia/Kolkata` as an enviroment variable in docker compose file but seems like that is not picked up by mediamtx image while running the `docker-compose up -d`.

Here is the `docker-compose` file:
```yaml
version: '3'

services:
  tapo-server:
    image: bluenviron/mediamtx:latest
    container_name: tapo-server
    network_mode: host
    volumes:
      - /home/piyush/tapo:/tapo
      - /home/piyush/tapo/config/mediamtx.yml:/mediamtx.yml
    environment:
      - TZ=Asia/Kolkata
      - PUSH_BULLET_API=XXXX
    restart: unless-stopped

volumes:
  tapo:
    driver: local
```

`mediamtx.yml` file:
```yaml
logLevel: info
logDestinations: [ file ]
logFile: /tapo/logs/cam.log

readTimeout: 10s
writeTimeout: 10s
#writeQueueSize: 8192

rtsp: yes
protocols: [ udp, multicast, tcp ]

record: yes
recordFormat: mpegts
recordPath: /tapo/recordings/%path/%Y-%m-%d_%H-%M-%S-%f
recordSegmentDuration: 5m
recordDeleteAfter: 12h

hlsAlwaysRemux: yes
hlsVariant: fmp4
hlsSegmentCount: 180
hlsSegmentDuration: 10s
hlsPartDuration: 1s
hlsSegmentMaxSize: 50M
hlsDirectory: /tapo/hls/
hlsMuxerCloseAfter: 1800s

metrics: yes


paths:
  cam1:
    source: rtsp://xxx:xxx@192.168.18.101:554/stream1
    sourceProtocol: tcp
    rtspTransport: tcp
  cam2:
    source: rtsp://xxx:xxx@192.168.18.102:554/stream1
    sourceProtocol: tcp
    rtspTransport: tcp
```

Can anyone help me out how can change the container timezone from UTC to Asia/Kolkata.

----

### Another Question:
Also when I was recording my videos in `fmp4` format it is getting recording with 1sec lag. Recorded videos were having 1s lag so I switched to `mpegts` now the recording is perfect but now I can't use the playback feature. I don't want to install any separate video player.

Is there any way to use the playback for `.ts` files?

Thanks in advance!
