### DISCUSSION TITLE
Example of HLS that can be embeded in a webpage

### DISCUSSION THREAD

**Discussion by itsgucci** [bluenviron/mediamtx#410] [Questions]
I have succesfully launched a RTSP with the following in the paths part of the config

```
paths:
  cam:
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
```

Then in my VLC I use 
`Open Network -> rtsp://localhost:8554/cam`
to view it.

I am curious if you can post a configuration to make that so I can view the HLS output so I can embed that in a website?
