### DISCUSSION TITLE
Stream Youtube live camera via mediamtx

### DISCUSSION THREAD

**Discussion by tranzmatt** [bluenviron/mediamtx#4137] [Questions]
### Question

I want to be able to pull a live youtube stream of a traffic camera and push it to a local rtsp server to do some testing on object rec, etc.  I can do this via yt-dlp and ffmpeg from the command line:

fmpeg -re -i "$(yt-dlp -g -f bestvideo https://www.youtube.com/live/mVHTqCXsZB0)"  \
     -c:v libx264 -preset veryfast -tune zerolatency -rtsp_transport tcp   \
     -f rtsp rtsp://my.video.server:8554/livestream_PortHuronMichiganUS

but if i try to make that an entry in mediamtx:

 port_huron_michigan_usa:
    runOnReady: >
      ffmpeg -re -i "$(/usr/local/bin/yt-dlp -g -f bestvideo https://www.youtube.com/live/mVHTqCXsZB0)" \
             -c:v libx264 -preset veryfast -tune zerolatency -rtsp_transport tcp \
             -f rtsp rtsp://my.video.server:8554/livestream_PortHuronMichiganUS
    runOnReadyRestart: yes
    
   it completely skips over the entry, not even fail.  I'm guessing it can't "shell out" to run anything?  If not, is there a way around it?

**Comment by aler9** [comment]
You're using the wrong hook - `runOnReady` is meant to execute something when the stream inside the server is ready, what you need is either `runOnInit` or `runOnDemand`:

```yml
paths:
  port_huron_michigan_usa:
    runOnInit: >
      ffmpeg -re -i "$(/usr/local/bin/yt-dlp -g -f bestvideo https://www.youtube.com/live/mVHTqCXsZB0)"
      -c:v libx264 -preset veryfast -tune zerolatency -rtsp_transport tcp
      -f rtsp rtsp://localhost:8554/port_huron_michigan_usa
    runOnInitRestart: yes
```

**Reply by syreeni** [reply]
I added this to end of mediamtx.yml -file on server. Outside of server command ffplay rtsp://server-ip-address:8554/port_huron_michigan_usa makes error: method DESCRIBE failed: 404 Not Found rtsp://server-ip-address:8554/port_huron_michigan_usa: Server returned 404 Not Found. 

Without this port_huron_michigan_usa, the mediamtx succesfully accepts videostream from outside to server and streams it out. I'm looking for the solution to read Youtube video to mediamtx server and then stream it out. How shoud I do this?

**Comment by julioviegas** [comment]
Just for further reference, I was not able to use the command above. After some minor tweaking, this one worked for me:

```yaml
paths:
  home_beach:
    runOnDemand: >
      bash -c 'ffmpeg -re -i "$(/usr/bin/yt-dlp -g --no-warnings https://www.youtube.com/watch?v=T5U_EzpjCJk)" -c:v libx264 -preset veryfast -tune zerolatency -rtsp_transport tcp -f rtsp rtsp://localhost:8554/home_beach'
    runOnDemandRestart: yes
```
