### DISCUSSION TITLE
Issue: Only the First Stream Works in MediaMTX with Multiple RTSP Sources

### DISCUSSION THREAD

**Discussion by azixcodes** [bluenviron/mediamtx#4159] [Questions]
### Question

Description:
I am using MediaMTX to restream multiple RTSP streams using runOnReady commands. However, only the first stream works regardless of the order of the RTSP sources in the configuration. The second stream fails to initialize.

Current Configuration:

```
paths:
  cam1:
    source: rtsp://my-rtsp-1
    sourceProtocol: automatic
    runOnReady: ffmpeg -re -i rtsp://localhost:5562/cam/realmonitor?channel=1&subtype=0 -c copy -f rtsp rtsp://127.0.0.1:8554/cam1
    runOnReadyRestart: yes
    sourceOnDemand: yes

  cam2:
    source: rtsp://my-rtsp-2
    sourceProtocol: automatic
    runOnReady: ffmpeg -re -i rtsp://localhost:5561/cam/realmonitor?channel=1&subtype=1 -c copy -f rtsp rtsp://127.0.0.1:5562/cam2
    runOnReadyRestart: yes
    sourceOnDemand: yes
```

**Observations:**

- The first stream always works, regardless of whether it is cam1 or cam2.
- The second stream fails to bind or does not produce any output.
- It seems there might be a conflict with ports or runOnReady commands.

**Steps to Reproduce:**
Configure MediaMTX with the above mediamtx.yml.
Start MediaMTX.
Attempt to access both streams:
rtsp://127.0.0.1:8554/cam1
rtsp://127.0.0.1:8555/cam2
Expected Behavior:
Both streams should work simultaneously and restream properly.

Actual Behavior:
Only the first stream is active and restreams successfully.

Additional Details:
Testing locally on Windows.
 
Request:
Please guide me on what might be causing this issue. Are there any additional configurations needed for handling multiple streams with runOnReady commands?

thanks.
