### DISCUSSION TITLE
How can I batch process this?

### DISCUSSION THREAD

**Discussion by naoki66** [bluenviron/mediamtx#4215] [Questions]
### Question

How can I batch process this? 
My Docker host IP is 192.168.3.5, and I’m using bluenviron/mediamtx to forward to the source. 
Currently, I have to manually replace each address, which works for playback, 
It seems like the source is being continuously requested, which causes high CPU usage.

I want to forward rtsp://192.168.3.5:8554/01000000004000000000000000000307 to access rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000307. 
How can I achieve this?
I want to make it so that when accessing rtsp://192.168.3.5:8554/01000000004000000000000000000307,
it only then requests rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000307. 

The rest of the streams should remain idle.

------------------------------------------------------
#mediamtx.yml

logLevel: info
rtsp: yes
rtspTransports: [tcp]
rtspAddress: :8554

paths:
  '01000000004000000000000000000231':
    source: rtsp://123.123.123.123:8089/04000001/01000000004000000000000000000231
  '01000000004000000000000000000295':
    source: rtsp://123.123.123.123:8089/04000001/01000000004000000000000000000295
  '01000000004000000000000000000302':
    source: rtsp://123.123.123.123:8089/04000001/01000000004000000000000000000302
  '01000000004000000000000000000307':
    source: rtsp://123.123.123.123:8089/04000001/01000000004000000000000000000307
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 10s

--------------------------------------
"I tried using
paths:
  "~^(.*)$":
    source: rtsp:/123.123.123.123:8089/04000001/$1
but it tells me that this is not supported."

**Comment by pnthai88** [comment]
try and let me know if works

```
logLevel: info
rtsp: yes
rtspTransports: [tcp]
rtspAddress: :8554

paths:
  # Wildcard to match any incoming RTSP stream
  '0100000000400000000000000000*':
    source: rtsp://123.147.112.17:8089/04000001/{STREAM}
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 10s
```

'0100000000400000000000000000*':

This matches any incoming stream that starts with 0100000000400000000000000000.
For example, accessing rtsp://192.168.3.5:8554/01000000004000000000000000000307 will trigger forwarding.
source: rtsp://123.147.112.17:8089/04000001/{STREAM}:

{STREAM} automatically captures the matched part of the incoming stream and appends it to the source URL.
So, accessing rtsp://192.168.3.5:8554/01000000004000000000000000000307 will forward to rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000307.

**Reply by naoki66** [reply]
ERR: invalid path name '0100000000400000000000000000*': can contain only alphanumeric characters, underscore, dot, tilde, minus or slash

**Reply by aler9** [reply]
you are missing a tilde at the beginning of the path name.

```yml
paths:
  # Wildcard to match any incoming RTSP stream
  '~0100000000400000000000000000*':
    source: rtsp://123.147.112.17:8089/04000001/{STREAM}
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 10s
```
