### DISCUSSION TITLE
Drive Recording Rules

### DISCUSSION THREAD

**Discussion by angelinimattia** [bluenviron/mediamtx#4244] [Questions] [answered]
### Question

Hi all,

I had a very direct question, I possible to specify which incoming stream have to be written on the disk and which one not? Maybe using some Rules?

I have a setting where I receive a video on the mediaMTX router, which I reprocess with GStremer and push back on the same router. But I do not need to store the processed video.

Thanks!

**Comment by aler9** [comment, marked as answer]
Every setting under `pathDefaults` can be moved inside a specific path, therefore:

```yml
paths:
  path_that_i_want_to_record:
    record: true

  path_that_i_do_not_want_to_record:
    record: false
```
