### DISCUSSION TITLE
A little help with simple connection code to react native, im new to this libary and something off..

### DISCUSSION THREAD

**Discussion by aviadkasgardsys** [bluenviron/mediamtx#4274] [Questions]
### Question

Hello im trying to connect my react native code to media mtx which streaming the most simple H264 Video , now i have 2 problems, 
DOCKER-COMPOSE.YML-
```
version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro # Mount our mediamtx.yml config
    ports:
      - '8554:8554' # RTSP
      - '8888:8888' # HLS
      - '8889:8889' # WebRTC
      - '1935:1935' # RTMP (if you enable it)
    networks:
      - mediamtx-net
    restart: unless-stopped

  ffmpeg:
    image: jrottenberg/ffmpeg:4.4-alpine
    container_name: ffmpeg-test-stream
    networks:
      - mediamtx-net
    command: >
      -re -f lavfi -i "testsrc=size=640x480:rate=30"
      -c:v libx264 -preset ultrafast -tune zerolatency
      -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/test1
    restart: unless-stopped

networks:
  mediamtx-net:
    driver: bridge
```
Mediamtx.yml-
```
# mediamtx.yml

logLevel: debug
logDestinations: [stdout]

# RTSP on port 8554
rtspAddress: :8554

# HLS on port 8888
hlsAddress: :8888

# WebRTC on port 8889
webrtcAddress: :8889
webrtcAllowOrigin: '*'
webrtc: true
webrtcAdditionalHosts:
  - '192.168.10.10' # add your local IP if desired
  - '10.0.2.2'
webrtcICEServers2:
  - url: stun:stun.l.google.com:19302

# (Optional) RTMP on port 1935
# rtmpEnable: yes
# rtmpAddress: :1935

# Define your RTSP paths here:
paths:
  test1: {}
  test2: {}
  test3: {}
  test4: {}
```
1. first i try to watch the rtsp connection with vlc , and sometimes its works and sometimes not like its not consistent for example : 
```
ffmpeg-test-stream | ffmpeg version 4.4.5 Copyright (c) 2000-2024 the FFmpeg developers
ffmpeg-test-stream |   built with gcc 10.2.1 (Alpine 10.2.1_pre1) 20201203
ffmpeg-test-stream |   configuration: --disable-debug --disable-doc --disable-ffplay --enable-avresample --enable-fontconfig --enable-gpl --enable-libaom --enable-libaribb24 --enable-libass --enable-libbluray --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libsrt --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzmq --enable-nonfree --enable-openssl --enable-postproc --enable-shared --enable-small --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --extra-libs=-lpthread --prefix=/opt/ffmpeg
ffmpeg-test-stream |   libavutil      56. 70.100 / 56. 70.100
ffmpeg-test-stream |   libavcodec     58.134.100 / 58.134.100
ffmpeg-test-stream |   libavformat    58. 76.100 / 58. 76.100
ffmpeg-test-stream |   libavdevice    58. 13.100 / 58. 13.100
ffmpeg-test-stream |   libavfilter     7.110.100 /  7.110.100
ffmpeg-test-stream |   libavresample   4.  0.  0 /  4.  0.  0
ffmpeg-test-stream |   libswscale      5.  9.100 /  5.  9.100
ffmpeg-test-stream |   libswresample   3.  9.100 /  3.  9.100
ffmpeg-test-stream |   libpostproc    55.  9.100 / 55.  9.100
ffmpeg-test-stream | Input #0, lavfi, from 'testsrc=size=640x480:rate=30':
ffmpeg-test-stream |   Duration: N/A, start: 0.000000, bitrate: N/A
ffmpeg-test-stream |   Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 640x480 [SAR 1:1 DAR 4:3], 30 tbr, 30 tbn, 30 tbc
ffmpeg-test-stream | Stream mapping:
ffmpeg-test-stream |   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
ffmpeg-test-stream | Press [q] to stop, [?] for help
ffmpeg-test-stream | [libx264 @ 0x7f5aebb4db40] using SAR=1/1
ffmpeg-test-stream | [libx264 @ 0x7f5aebb4db40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
ffmpeg-test-stream | [libx264 @ 0x7f5aebb4db40] profile High 4:4:4 Predictive, level 3.0, 4:4:4 8-bit
ffmpeg-test-stream | [libx264 @ 0x7f5aebb4db40] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=6 threads=7 lookahead_threads=7 sliced_threads=1 slices=7 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
ffmpeg-test-stream | Output #0, rtsp, to 'rtsp://mediamtx:8554/test1':
ffmpeg-test-stream |   Metadata:
ffmpeg-test-stream |     encoder         : Lavf58.76.100
ffmpeg-test-stream |   Stream #0:0: Video: h264, yuv444p(tv, progressive), 640x480 [SAR 1:1 DAR 4:3], q=2-31, 30 fps, 90k tbn
ffmpeg-test-stream |     Metadata:
ffmpeg-test-stream |       encoder         : Lavc58.134.100 libx264
ffmpeg-test-stream |     Side data:
ffmpeg-test-stream |       cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
mediamtx | 2025/02/23 15:05:24 INF MediaMTX v1.11.2
mediamtx | 2025/02/23 15:05:24 INF configuration loaded from /mediamtx.yml
mediamtx | 2025/02/23 15:05:24 DEB [path test4] created
mediamtx | 2025/02/23 15:05:24 DEB [path test1] created
mediamtx | 2025/02/23 15:05:24 DEB [path test2] created
mediamtx | 2025/02/23 15:05:24 DEB [path test3] created
mediamtx | 2025/02/23 15:05:24 DEB path manager created
mediamtx | 2025/02/23 15:05:24 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
mediamtx | 2025/02/23 15:05:24 INF [RTMP] listener opened on :1935
mediamtx | 2025/02/23 15:05:24 INF [HLS] listener opened on :8888
mediamtx | 2025/02/23 15:05:24 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
mediamtx | 2025/02/23 15:05:24 INF [SRT] listener opened on :8890 (UDP)
mediamtx | 2025/02/23 15:05:24 INF [RTSP] [conn 172.25.0.2:41082] opened
mediamtx | 2025/02/23 15:05:24 DEB [RTSP] [conn 172.25.0.2:41082] [c->s] OPTIONS rtsp://mediamtx:8554/test1 RTSP/1.0
mediamtx | CSeq: 1
mediamtx | User-Agent: Lavf58.76.100
mediamtx | 
mediamtx | 
mediamtx | 2025/02/23 15:05:24 DEB [RTSP] [conn 172.25.0.2:41082] [s->c] RTSP/1.0 200 OK
mediamtx | CSeq: 1
mediamtx | Public: DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, GET_PARAMETER, TEARDOWN
mediamtx | Server: gortsplib
mediamtx | 
mediamtx | 
mediamtx | 2025/02/23 15:05:24 DEB [RTSP] [conn 172.25.0.2:41082] [c->s] ANNOUNCE rtsp://mediamtx:8554/test1 RTSP/1.0
mediamtx | CSeq: 2
mediamtx | Content-Length: 293
mediamtx | Content-Type: application/sdp
mediamtx | User-Agent: Lavf58.76.100
mediamtx | 
mediamtx | v=0
mediamtx | o=- 0 0 IN IP4 127.0.0.1
mediamtx | s=No Name
mediamtx | c=IN IP4 172.25.0.3
mediamtx | t=0 0
mediamtx | a=tool:libavformat 58.76.100
mediamtx | m=video 0 RTP/AVP 96
mediamtx | a=rtpmap:96 H264/90000
mediamtx | a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z/QAHpGWgKA9sBEAAAMAAQAAAwA8jxYuoA==,aM4PGSA=; profile-level-id=F4001E
mediamtx | a=control:streamid=0
mediamtx | 
mediamtx | 2025/02/23 15:05:24 INF [RTSP] [session f38763b3] created by 172.25.0.2:41082
mediamtx | 2025/02/23 15:05:24 DEB [RTSP] [conn 172.25.0.2:41082] [s->c] RTSP/1.0 200 OK
mediamtx | CSeq: 2
mediamtx | Server: gortsplib
mediamtx | 
mediamtx | 
mediamtx | 2025/02/23 15:05:24 DEB [RTSP] [conn 172.25.0.2:41082] [c->s] SETUP rtsp://mediamtx:8554/test1/streamid=0 RTSP/1.0
mediamtx | CSeq: 3
mediamtx | Transport: RTP/AVP/TCP;unicast;interleaved=0-1;mode=record
mediamtx | User-Agent: Lavf58.76.100
mediamtx | 
mediamtx | 
mediamtx | 2025/02/23 15:05:24 DEB [RTSP] [conn 172.25.0.2:41082] [s->c] RTSP/1.0 200 OK
mediamtx | CSeq: 3
mediamtx | Server: gortsplib
mediamtx | Session: 7c391d19e6714db6a6d60db1f1a508e3
mediamtx | Transport: RTP/AVP/TCP;unicast;interleaved=0-1
mediamtx | 
mediamtx | 
mediamtx | 2025/02/23 15:05:24 DEB [RTSP] [conn 172.25.0.2:41082] [c->s] RECORD rtsp://mediamtx:8554/test1 RTSP/1.0
mediamtx | CSeq: 4
mediamtx | Range: npt=0.000-
mediamtx | Session: 7c391d19e6714db6a6d60db1f1a508e3
mediamtx | User-Agent: Lavf58.76.100
mediamtx | 
mediamtx | 
mediamtx | 2025/02/23 15:05:24 INF [RTSP] [session f38763b3] is publishing to path 'test1', 1 track (H264)
mediamtx | 2025/02/23 15:05:24 DEB [RTSP] [conn 172.25.0.2:41082] [s->c] RTSP/1.0 200 OK
mediamtx | CSeq: 4
mediamtx | Server: gortsplib
mediamtx | Session: 7c391d19e6714db6a6d60db1f1a508e3
mediamtx | 
mediamtx | 
```
then  -
```
2025/02/23 15:08:27 INF [RTSP] [conn 172.25.0.1:45928] opened
2025/02/23 15:08:27 DEB [RTSP] [conn 172.25.0.1:45928] [c->s] SETUP rtsp://localhost:8554/test1 RTSP/1.0
CSeq: 0
Transport: RTP/AVP;unicast;client_port=9146-9147


2025/02/23 15:08:27 INF [RTSP] [session 606a864d] created by 172.25.0.1:45928
2025/02/23 15:08:27 DEB [RTSP] [conn 172.25.0.1:45928] [s->c] RTSP/1.0 400 Bad Request
CSeq: 0
Server: gortsplib


2025/02/23 15:08:27 INF [RTSP] [session 606a864d] destroyed: not in use
2025/02/23 15:08:27 INF [RTSP] [conn 172.25.0.1:45928] closed: invalid SETUP path. This typically happens when VLC fails a request, and then switches to an unsupported RTSP dialect
2025/02/23 15:08:27 INF [RTSP] [conn 172.25.0.1:45932] opened
2025/02/23 15:08:27 DEB [RTSP] [conn 172.25.0.1:45932] [c->s] OPTIONS rtsp://localhost:8554 RTSP/1.0
CSeq: 1
Clientchallenge: 9e26d33f2984236010ef6253fb1887f7
Clientid: Linux_2.4_6.0.9.1235_play32_RN01_EN_586
Companyid: KnKV4M4I/B2FjJ1TToLycw==
Guid: 00000000-0000-0000-0000-000000000000
Playerstarttime: [28/03/2003:22:50:23 00:00]
Regiondata: 0
User-Agent: RealMedia Player Version 6.0.9.1235 (linux-2.0-libc6-i386-gcc2.95)


2025/02/23 15:08:27 DEB [RTSP] [conn 172.25.0.1:45932] [s->c] RTSP/1.0 200 OK
CSeq: 1
Public: DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, GET_PARAMETER, TEARDOWN
Server: gortsplib


2025/02/23 15:08:27 INF [RTSP] [conn 172.25.0.1:45932] closed: EOF
```
can you tell me why its sometimes works sometimes not? im not sure why.. 
i just vlc the 'rtsp://localhost:8554/test1' ..
