### DISCUSSION TITLE
I would like to get some help also if someone have example that works with react-native-webrtc

### DISCUSSION THREAD

**Discussion by aviadkasgardsys** [bluenviron/mediamtx#4275] [Questions]
### Question

like the title i tried to connect it to your libary but again the connection is falling when i setup here is example code and DOCKER-COMPOSE.YML-
```
version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro # Mount our mediamtx.yml config
    ports:
      - '8554:8554' # RTSP
      - '8888:8888' # HLS
      - '8889:8889' # WebRTC
      - '1935:1935' # RTMP (if you enable it)
    networks:
      - mediamtx-net
    restart: unless-stopped

  ffmpeg:
    image: jrottenberg/ffmpeg:4.4-alpine
    container_name: ffmpeg-test-stream
    depends_on:
      - mediamtx
    networks:
      - mediamtx-net
    command: >
      -re -f lavfi -i "testsrc=size=640x480:rate=30"
      -c:v libx264 -preset ultrafast -tune zerolatency
      -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/test1
    restart: unless-stopped

networks:
  mediamtx-net:
    driver: bridge
```
MEDIAMTX.YML
```
# mediamtx.yml

logLevel: debug
logDestinations: [stdout]

# RTSP on port 8554
rtspAddress: :8554

# HLS on port 8888
hlsAddress: :8888

# WebRTC on port 8889
webrtcAddress: :8889
webrtcAllowOrigin: '*'
webrtc: true
webrtcAdditionalHosts:
  - '192.168.10.10' # add your local IP if desired
  - '10.0.2.2'
webrtcICEServers2:
  - url: stun:stun.l.google.com:19302

# (Optional) RTMP on port 1935
# rtmpEnable: yes
# rtmpAddress: :1935

# Define your RTSP paths here:
paths:
  test1: {}
  test2: {}
  test3: {}
  test4: {}
```
App.tsx-
```
import React, {useState, useEffect, useRef} from 'react';
import {SafeAreaView, StyleSheet, View, Text} from 'react-native';
import {
  RTCPeerConnection,
  RTCView,
  RTCSessionDescription,
  MediaStream,
} from 'react-native-webrtc';

const configuration = {
  iceServers: [{urls: 'stun:stun.l.google.com:19302'}],
};

// The MediaMTX play endpoint (adjust host and path as needed)
const MEDIA_MTX_PLAY_URL = 'http://10.0.2.2:8889/test1/whep';

const App: React.FC = () => {
  const [remoteStream, setRemoteStream] = useState<MediaStream | null>(null);
  const [status, setStatus] = useState<string>('Initializing...');
  const pc = useRef<RTCPeerConnection | null>(null);
  // We'll store the candidate patch URL here once we get it from MediaMTX
  const candidatePatchUrl = useRef<string | null>(null);

  useEffect(() => {
    async function startPlay() {
      // 1. Create a new RTCPeerConnection.
      pc.current = new RTCPeerConnection(configuration);

      // 2. Set up the event handler for remote media tracks.
      pc.current.ontrack = (event: any) => {
        console.log('ontrack event received:', event);
        if (event.streams && event.streams[0]) {
          setRemoteStream(event.streams[0]);
          setStatus('Connected');
        }
      };

      // 3. Set up ICE candidate handler to send trickle ICE candidates.
      pc.current.onicecandidate = async (event: any) => {
        if (event.candidate) {
          console.log('Local ICE candidate:', event.candidate);

          pc.current?.addIceCandidate(event.candidate);
        }
      };

      pc.current.onconnectionstatechange = () => {
        console.log('Connection state:', pc.current.connectionState);
      };

      try {
        // 4. Create an SDP offer.
        const offer = await pc.current.createOffer({
          offerToReceiveAudio: true,
          offerToReceiveVideo: true,
        });
        console.log('SDP Offer:', offer.sdp);
        await pc.current.setLocalDescription(offer);
        setStatus('Sending offer to MediaMTX...');

        // 5. Send the SDP offer to MediaMTX using an HTTP POST.
        // Set Content-Type to "application/sdp" and send the raw SDP offer.
        const response = await fetch(MEDIA_MTX_PLAY_URL, {
          method: 'POST',
          headers: {'Content-Type': 'application/sdp'},
          body: offer.sdp,
        });

        if (!response.ok) {
          throw new Error(`HTTP error! Status: ${response.status}`);
        }

        // Retrieve the candidate patch URL from the Location header.
        const locationHeader = response.headers.get('Location');
        if (locationHeader) {
          candidatePatchUrl.current = locationHeader;
          console.log('Candidate patch URL:', candidatePatchUrl.current);
        } else {
          console.warn('No candidate patch URL received.');
        }

        // Parse the response as text (the SDP answer)
        const answerSdp = await response.text();
        console.log('Received SDP answer:', answerSdp);

        // 6. Set the remote description with the received SDP answer.
        const answer = new RTCSessionDescription({
          type: 'answer',
          sdp: answerSdp,
        });
        await pc.current.setRemoteDescription(answer);
        setStatus('Negotiation complete');
      } catch (err) {
        console.error('Error during WebRTC negotiation:', err);
        setStatus('Error: ' + err);
      }
    }

    startPlay();

    // Cleanup on unmount
    return () => {
      if (pc.current) {
        pc.current.close();
      }
    };
  }, []);

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.statusBar}>
        <Text style={styles.statusText}>{status}</Text>
      </View>
      {remoteStream ? (
        <RTCView
          streamURL={remoteStream.toURL()}
          style={styles.video}
          objectFit="cover"
        />
      ) : (
        <Text style={styles.info}>Waiting for remote stream...</Text>
      )}
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: 'black'},
  video: {flex: 1},
  statusBar: {
    position: 'absolute',
    top: 10,
    left: 10,
    zIndex: 1,
  },
  statusText: {color: 'white', fontSize: 16},
  info: {color: 'white', textAlign: 'center', marginTop: 20},
});

export default App;
```
LOGS : 
```
2025/02/23 15:27:46 DEB [WebRTC] [conn 172.28.0.1:36374] [c->s] POST /test1/whep HTTP/1.1
Host: 10.0.2.2:8889
Accept-Encoding: gzip
Connection: Keep-Alive
Content-Length: 4104
Content-Type: application/sdp
User-Agent: okhttp/4.12.0

v=0
o=- 8646541401481894614 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 102 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:tVjR
a=ice-pwd:rAGbpoxjTvxR2f5AlVMJlV6Z
a=ice-options:trickle renomination
a=fingerprint:sha-256 B3:73:DA:74:1F:C2:9D:BA:C6:89:FF:83:CB:D7:11:C5:F7:E7:09:E4:3B:44:99:BA:F8:C0:D2:F3:7B:ED:DB:14
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 103 35 36 37 38 39 40 41 42 104 105 106 43
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:tVjR
a=ice-pwd:rAGbpoxjTvxR2f5AlVMJlV6Z
a=ice-options:trickle renomination
a=fingerprint:sha-256 B3:73:DA:74:1F:C2:9D:BA:C6:89:FF:83:CB:D7:11:C5:F7:E7:09:E4:3B:44:99:BA:F8:C0:D2:F3:7B:ED:DB:14
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP8/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=0
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 VP9/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 profile-id=2
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=127
a=rtpmap:35 VP9/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=fmtp:35 profile-id=1
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:37 VP9/90000
a=rtcp-fb:37 goog-remb
a=rtcp-fb:37 transport-cc
a=rtcp-fb:37 ccm fir
a=rtcp-fb:37 nack
a=rtcp-fb:37 nack pli
a=fmtp:37 profile-id=3
a=rtpmap:38 rtx/90000
a=fmtp:38 apt=37
a=rtpmap:39 AV1/90000
a=rtcp-fb:39 goog-remb
a=rtcp-fb:39 transport-cc
a=rtcp-fb:39 ccm fir
a=rtcp-fb:39 nack
a=rtcp-fb:39 nack pli
a=fmtp:39 level-idx=5;profile=0;tier=0
a=rtpmap:40 rtx/90000
a=fmtp:40 apt=39
a=rtpmap:41 AV1/90000
a=rtcp-fb:41 goog-remb
a=rtcp-fb:41 transport-cc
a=rtcp-fb:41 ccm fir
a=rtcp-fb:41 nack
a=rtcp-fb:41 nack pli
a=fmtp:41 level-idx=5;profile=1;tier=0
a=rtpmap:42 rtx/90000
a=fmtp:42 apt=41
a=rtpmap:104 red/90000
a=rtpmap:105 rtx/90000
a=fmtp:105 apt=104
a=rtpmap:106 ulpfec/90000
a=rtpmap:43 flexfec-03/90000
a=rtcp-fb:43 goog-remb
a=rtcp-fb:43 transport-cc
a=fmtp:43 repair-window=10000000

2025/02/23 15:27:46 INF [WebRTC] [session 7edfe700] created by 172.28.0.1:36374
2025/02/23 15:27:46 DEB [WebRTC] [session 7edfe700] peer connection state: connecting
2025/02/23 15:27:46 DEB [WebRTC] [conn 172.28.0.1:36374] [s->c] HTTP/1.1 201 Created
Accept-Patch: application/trickle-ice-sdpfrag
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, ID, Accept-Patch, Link, Location
Content-Type: application/sdp
Etag: *
Id: 7edfe700-fc28-4f03-8bd0-b61fecd80b1b
Link: <stun:stun.l.google.com:19302>; rel="ice-server"
Location: /test1/whep/492cb82c-2e40-4af0-80d5-65e7029704bc
Server: mediamtx

(body of 2235 bytes)
2025/02/23 15:27:56 DEB [WebRTC] [session 7edfe700] peer connection state: closed
2025/02/23 15:27:56 INF [WebRTC] [session 7edfe700] closed: deadline exceeded while waiting connection
```
can you explain me what is the cause for the applcation to crash?
OPERATION SYSTEM : WINDOWS 10
DOCKER,
ANDROID EMULATOR.
**Also i forgot to mention if someone have example for me using react-native-webrtc and mediamtx its will be good for me too**
