### DISCUSSION TITLE
Chaining runOnDemands

### DISCUSSION THREAD

**Discussion by kelly-slate** [bluenviron/mediamtx#4344] [Questions]
### Question

hello - 

is it possible to chain runOnDemand commands with something like:
```
  raw:
    runOnDemand: gst-launch-1.0 v4l2src device=/dev/video1 ! video/x-raw ! rtspclientsink location=rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnDemandRestart: yes

  h264:
    runOnDemand: gst-launch-1.0 rtspsrc location=rtsp://localhost:$RTSP_PORT/raw ! video/x-raw ! x264enc ! h264parse ! rtspclientsink location=rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnDemandRestart: yes

  mjpg:
    runOnDemand: gst-launch-1.0 rtspsrc location=rtsp://localhost:$RTSP_PORT/raw ! video/x-raw ! jpegenc ! jpegparse ! rtspclientsink location=rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnDemandRestart: yes
```

ideally, i would like to have a high-res h264/5, a low-res h264/5, and an mjpg path that could all source the same raw video. and when no clients are requesting, the camera stops streaming the raw path and its children.

i tried using the method in the MediaMTX README, but this assumes the input is an external rtsp source, not a v4l2src or another path within mediamtx:
```
compressed:
  original:
    runOnReady: >
      ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH
        -c:v libx264 -pix_fmt yuv420p -preset ultrafast -b:v 600k
        -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/compressed
    runOnReadyRestart: yes
```

any suggestions would be greatly appreciated, thank you
