### DISCUSSION TITLE
Frame rate

### DISCUSSION THREAD

**Discussion by roycw** [bluenviron/mediamtx#4393] [Questions]
### Question

Guysm i have an ffmpeg seperatly streaming to MediMtx (not via the config file) im consuming the feed on the frontend , is there any way to send parameters like frame rate to the media mtx server ? what would be a good way to solve it.?

**Comment by aler9** [comment]
Hello, you can move FFmpeg inside `runOnReady`:

```yml
paths:
  mypath:
    runOnReady: ffmpeg -i rtsp://localhost:8554/mypath ... -r FRAMERATE
```

and then use the MediaMTX API to dynamically change runOnReady and consequently the FFmpeg frame rate.
