### DISCUSSION TITLE
Disable authentication for prometheus metrics?

### DISCUSSION THREAD

**Discussion by llamafilm** [bluenviron/mediamtx#4407] [Questions]
### Question

When I try to scrape prometheus metrics at `http://mediamtx:9998/metrics` I get 401 Unauthorized.  Can this be configured to work without authentication?  I have left all the authentication settings at their default, which appears to be wide open.
If I scrape this endpoint at localhost then it works fine.  But my prometheus agent is running on another instance.

**Comment by aler9** [comment]
Hello, default authentication is not "wide open" but restricts usage of API, metrics and pprof to localhost only. You can change this in the configuration file, in particular this room:

```yml
# Internal authentication.
# list of users.
authInternalUsers:

  # Default administrator.
  # This allows to use API, metrics and PPROF without authentication,
  # if the IP is localhost.
- user: any
  pass:
  ips: ['127.0.0.1', '::1']
  permissions:
  - action: api
  - action: metrics
  - action: pprof
```
