### DISCUSSION TITLE
Error i/o timeout between 2 Docker container

### DISCUSSION THREAD

**Discussion by mister-good-deal** [bluenviron/mediamtx#444] [Questions]
## Which version are you using?

v0.16.0

## Which operating system are you using?

Ubuntu 20.04 LTS

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

The RTMP server does not recieve frames from other Docker container.

The server is starting with `docker-compose up stream` and gives the following output.

```
rom1@msi-p100:~/Projects/video-extractor$ docker-compose up stream
Starting video-extractor-stream ... done
Attaching to video-extractor-stream
video-extractor-stream | 2021/06/15 09:41:30 I [0/0] rtsp-simple-server v0.16.0
video-extractor-stream | 2021/06/15 09:41:30 I [0/0] [RTSP] TCP listener opened on :8554
video-extractor-stream | 2021/06/15 09:41:30 I [0/0] [RTMP] listener opened on :1935
video-extractor-stream | 2021/06/15 09:45:48 I [0/0] [RTMP] [conn 172.20.0.2:60012] opened
video-extractor-stream | 2021/06/15 09:45:58 I [0/0] [RTMP] [conn 172.20.0.2:60012] ERR: read tcp 172.20.0.4:1935->172.20.0.2:60012: i/o timeout
video-extractor-stream | 2021/06/15 09:45:58 I [0/0] [RTMP] [conn 172.20.0.2:60012] closed
```

In the client Docker container pushing the H264 frames, the handshake seems to work well with `avio_open(&formatContext->pb, formatContext->url, AVIO_FLAG_WRITE)` and `avformat_write_header(formatContext, nullptr)` resulting in `video-extractor-stream | 2021/06/15 09:45:48 I [0/0] [RTMP] [conn 172.20.0.2:60012] opened` on the server.

Then, the client pushes H264 frames with `av_write_frame(formatContext, &packet)` and `av_write_frame(formatContext, nullptr)` but it seems like none of the frames are received from the server, resulting in `video-extractor-stream | 2021/06/15 09:45:58 I [0/0] [RTMP] [conn 172.20.0.2:60012] ERR: read tcp 172.20.0.4:1935->172.20.0.2:60012: i/o timeout`. The `av_write_frame` calls are successful.

I did not open client port on my `docker-compose.yaml` as the containers inside the same network should be able to talk with each others. Here is the Docker network config :

**docker-compose.yaml**

```yaml
version: "3.9"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"

services:
  dev:
    image: video-extractor/cuda-10.2:latest
    container_name: video-extractor-dev
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "2222:22"       # SSH binding port for host IDE integration
      - "1234:1234"     # Remote GDB binding port for host IDE integration
    networks:
      net:
        ipv4_address: 172.20.0.2
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    command: >
      sh -c "service ssh start &&
             while true
             do
                /usr/local/bin/gdbserver :1234 /app/build/run /app/resources/videos/720P.mp4
             done"

  stream:
    image: aler9/rtsp-simple-server:latest-amd64
    container_name: video-extractor-stream
    volumes:
      - ./rtsp-simple-server.yml:/rtsp-simple-server.yml
    ports:
      - "1935:1935"       # exposing the RTMP port
    networks:
      net:
        ipv4_address: 172.20.0.4

```

**Comment by dorinclisu** [comment]
It looks like you have a pretty complicated docker networking setup which is most likely to blame for the problem.
I for one don't see why you have to define the network explicitly and hardcode ip's.

What compose version are you running? On 1.29.0 it says your compose config is invalid, cannot start containers: `ERROR: Pool overlaps with other one on this address space`

**Comment by mister-good-deal** [comment]
I defined hardcoded IPs to setup network configuration in my code with well known IP and not docker hostname internal resolution.

I didn't know defining 2 IP addresses in compose file was a pretty complicated setup, do you suggest using Docker internal hostname resolution and not IP addresses should fix the problem ?

**docker-compose -v** `docker-compose version 1.29.0, build unknown`

**docker -v** `Docker version 20.10.7, build f0df350`

**/etc/docker/daemon.json**

```json
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "features": {
        "buildkit": true
    }
}
```

**Comment by dorinclisu** [comment]
Why don't you try with this config:
```yaml
version: "3.9"

services:
  dev:
    image: video-extractor/cuda-10.2:latest
    container_name: video-extractor-dev
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "2222:22"       # SSH binding port for host IDE integration
      - "1234:1234"     # Remote GDB binding port for host IDE integration
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    command: >
      sh -c "service ssh start &&
             while true
             do
                /usr/local/bin/gdbserver :1234 /app/build/run /app/resources/videos/720P.mp4
             done"

  stream:
    image: aler9/rtsp-simple-server:latest-amd64
    container_name: video-extractor-stream
    volumes:
      - ./rtsp-simple-server.yml:/rtsp-simple-server.yml
    ports:
      - "1935:1935"       # exposing the RTMP port
```

Also be aware that `docker-compose up stream` only runs the stream container, if you wanna start both you have to do `docker-compose up`.

In any case I am not able to replicate since your extractor image is private, and also you did not share the server config yml.

**Comment by mister-good-deal** [comment]
Ok so I just tried this config :

**docker-compose.yaml**

```yaml
version: "3.9"

services:
  dev:
    image: video-extractor/cuda-10.2:latest
    container_name: video-extractor-dev
    hostname: video-extractor-dev
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "2222:22"       # SSH binding port for host IDE integration
      - "1234:1234"     # Remote GDB binding port for host IDE integration
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    command: >
      sh -c "service ssh start &&
             while true
             do
                /usr/local/bin/gdbserver :1234 /app/build/run /app/resources/videos/720P.mp4
             done"

  stream:
    image: aler9/rtsp-simple-server:latest-amd64
    container_name: video-extractor-stream
    hostname: video-extractor-stream
    volumes:
      - ./rtsp-simple-server.yml:/rtsp-simple-server.yml
    ports:
#      - "8554:8554"       # exposing the RTSP port
#      - "8000:8000/udp"   # exposing the RTP port
#      - "8001:8001/udp"   # exposing the RTCP port
      - "1935:1935"       # exposing the RTMP port
```

**docker network inspect video-extractor_default**

```json
[
    {
        "Name": "video-extractor_default",
        "Id": "21fa30311acf4feab8ec3a28aabe4ebef7b4317035519767b7cc59d0c5a17047",
        "Created": "2021-06-17T16:55:18.277503986+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.20.0.0/16",
                    "Gateway": "172.20.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "ad56001245cc0b7e0a2c25128d8e6071757414fee10a9aa72525c31feda79cb7": {
                "Name": "video-extractor-stream",
                "EndpointID": "bec652a42c730b4a141f733543eea45e293a49ae48dd4070050cfae9479409aa",
                "MacAddress": "02:42:ac:14:00:02",
                "IPv4Address": "172.20.0.2/16",
                "IPv6Address": ""
            },
            "dd564fbf36fe2a346d49a4f1062ea5b3eb4b65e1a72fbf55e6e9da65fe320a41": {
                "Name": "video-extractor-dev",
                "EndpointID": "f20d7ff63703bab2354b8d3a1479f57bdbc66fb1df623c3c8d5f87fdfd0e264d",
                "MacAddress": "02:42:ac:14:00:03",
                "IPv4Address": "172.20.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "video-extractor",
            "com.docker.compose.version": "1.29.0"
        }
    }
]
```

**server container output**

```
Starting video-extractor-stream ... done
Attaching to video-extractor-stream
video-extractor-stream | 2021/06/17 15:02:34 I [0/0] rtsp-simple-server v0.16.0
video-extractor-stream | 2021/06/17 15:02:34 I [0/0] [RTSP] TCP listener opened on :8554
video-extractor-stream | 2021/06/17 15:02:34 I [0/0] [RTMP] listener opened on :1935
video-extractor-stream | 2021/06/17 15:02:51 I [0/0] [RTMP] [conn 172.20.0.3:33984] opened
video-extractor-stream | 2021/06/17 15:03:01 I [0/0] [RTMP] [conn 172.20.0.3:33984] ERR: read tcp 172.20.0.2:1935->172.20.0.3:33984: i/o timeout
video-extractor-stream | 2021/06/17 15:03:01 I [0/0] [RTMP] [conn 172.20.0.3:33984] closed
```

**frames feeder container**

```
Recreating video-extractor-dev ... done
Attaching to video-extractor-dev
video-extractor-dev |  * Starting OpenBSD Secure Shell server sshd
video-extractor-dev |    ...done.
video-extractor-dev | Process /app/build/run created; pid = 22
video-extractor-dev | Listening on port 1234
video-extractor-dev | Remote debugging from host 172.20.0.1, port 40440
video-extractor-dev | [mov,mp4,m4a,3gp,3g2,mj2 @ 0x5557e5306f40] st: 0 edit list: 1 Missing key frame while searching for timestamp: 0
video-extractor-dev | [mov,mp4,m4a,3gp,3g2,mj2 @ 0x5557e5306f40] st: 0 edit list 1 Cannot find an index entry before timestamp: 0.
video-extractor-dev | Streaming protocol: rtmp
video-extractor-dev | Could not deduce output format from file extension: using MPEG
video-extractor-dev | Streaming destination: rtmp://video-extractor-stream:1935
video-extractor-dev | [NULL @ 0x5557e588ff80] Requested output format 'rtmp' is not a suitable output format
video-extractor-dev | Session Initialization Time: 8 ms 
video-extractor-dev | pts: 0 , pts_time: 0
video-extractor-dev | dts: 0, dts_time: 0
video-extractor-dev | duration: 0, duration_time: 0
video-extractor-dev | stream_index: 0
video-extractor-dev | pts: 3000 , pts_time: 0.0333333
video-extractor-dev | dts: 3000, dts_time: 0.0333333
video-extractor-dev | duration: 0, duration_time: 0
video-extractor-dev | stream_index: 0
video-extractor-dev | pts: 6000 , pts_time: 0.0666667
video-extractor-dev | dts: 6000, dts_time: 0.0666667
video-extractor-dev | duration: 0, duration_time: 0
video-extractor-dev | stream_index: 0
...
```

So i'm now connecting to the RTMP server with `rtmp://video-extractor-stream:1935` URL and the hostname resolution is working but I still have this `ERR: read tcp 172.20.0.2:1935->172.20.0.3:33984: i/o timeout` error.
