### DISCUSSION TITLE
Is it possible to use runOnDemand and ffmpeg in docker?

### DISCUSSION THREAD

**Discussion by alealex** [bluenviron/mediamtx#450] [Questions]
Hello,
I am using rtsp-simple-server v0.16.4 as a docker container aler9/rtsp-simple-server
and my config has

```
paths:
  all: 
  stream_file1:
    runOnDemand: ffmpeg -i filename -c copy -f rtsp -rtsp_transport tcp rtsp://rtsp-server:8554/stream_file1
```

it works with such config on Windows host (not in docker) but doesn't work in docker container on linux.
Is it possible to run ffmpeg in docker?

moreover when I try to run any command like
`docker exec -it <docker_container_id> sh`
result is 
`OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "sh": executable file not found in $PATH: unknown`

Thanks in advance for any ideas!
