### DISCUSSION TITLE
[Docker] How to put recordings in a specific folder?

### DISCUSSION THREAD

**Discussion by ntn888** [bluenviron/mediamtx#4500] [Questions] [answered]
### Question

Hi I'm running docker. Currently the recordings go into the container's root directory.
Is there a way to specifiy to put them into a folder on the host? Perhaps with `docker-compose.yml`?

**Comment by dan-nicholls** [comment, marked as answer]
if you want to specify a directory inside the container to place the recordings in you can [set the `recordPath` in your configuration file](https://github.com/bluenviron/mediamtx?tab=readme-ov-file#record-streams-to-disk).

If you want to get the access to the files on the host you need to specify a volume on your container:
```yaml
version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx
      volumes:
        - /path/on/host:/path/in/container
      ports:
         - "8080:80"
```
