### DISCUSSION TITLE
Memory not getting released when running as RSTP Proxy

### DISCUSSION THREAD

**Discussion by gs4l** [bluenviron/mediamtx#4502] [Questions]
### Question

Hello,

Mediamtx version: v1.11.3
I am running a mediamtx pod with path configured as RTSP proxy. I executed a load test with 200 RTSP streams concurrently and observed the CPU and Memory utilization percentage metrics. The CPU utilization % spikes up and goes down as expected but the memory utilization % is not reducing after the load is removed.

I am using the below configuration of the mediamtx server:
```
logLevel: info
logDestinations: [stdout]
readTimeout: 10s
writeTimeout: 10s
writeQueueSize: 512
udpMaxPayloadSize: 1472
api: yes
apiAddress: :9997
apiEncryption: no
apiAllowOrigin: '*'
rtsp: yes
rtspTransports: [tcp]
rtspEncryption: "no"
rtspAddress: :8554
rtmp: no
hls: no
webrtc: no
srt: no
paths:
  "~^e61b3647-7891-4e05-99b2-a0f90d653f5d/(.+)$":
    source: rtsp://<rtsp_source_server_domain_name>/$G1,
    sourceOnDemand: true,
    sourceProtocol: tcp
```

The pod resources are mentioned below:
```
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

The CPU and memory utilization trends I observed is in the image below. As observed for the 2 load tests, the cpu utilization goes up and down, but the memory is only increased and not reduced. This is quite unexpected behaviour.
<img width="1000" alt="Screenshot 2025-05-07 at 6 36 05 PM" src="https://github.com/user-attachments/assets/7f925877-56b5-4dd7-b68e-3070a0c15b56" />

Please help if anyone has seen this senario or running the mediamtx as RTSP Proxy without issues or I might be missing something.

Thanks,
