### DISCUSSION TITLE
ERR: payload size greater than maximum allowed (10000 vs 2048)

### DISCUSSION THREAD

**Discussion by mattheys** [bluenviron/mediamtx#454] [Questions] [answered]
I keep getting the below on two of my cameras TP-Link Tapo C200's, they worked on 13.1 and I was still getting that message, I upgraded to 16.4 and now they don't.

I thought the readBufferSize might fix it so I'm not sure if I've put that in the wrong place or if I need to open this as a bug maybe?

`2021/07/07 13:22:55 I [0/4] [path back] [rtsp source] ERR: payload size greater than maximum allowed (10000 vs 2048)`

```yaml
paths:
  all:
    sourceOnDemand: no

  back:
    source: rtsp://192.168.4.3/stream1
    sourceProtocol: tcp
    readBufferSize: 10000
```

**Comment by aler9** [comment, marked as answer]
`readBufferSize` must be put on the root of the configuration file:

```yml
readBufferSize: 10000

paths:
  all:
    sourceOnDemand: no

  back:
    source: rtsp://192.168.4.3/stream1
    sourceProtocol: tcp
```

[a comment by an automated account is not shown]
