### DISCUSSION TITLE
Stream at max speed

### DISCUSSION THREAD

**Discussion by davideberra** [bluenviron/mediamtx#4540] [Questions]
### Question

Hi! I have one path on mediamtx that runs an ffmpeg, streaming a very big video file to mediamtx rtsp endpoint

```
paths:
  video:
    runOnDemand: ffmpeg -i veryfatvideofile.mp4 -rtsp_transport tcp -c:v copy -c:a aac -b:a 128k -f rtsp rtsp://localhost:${RTSP_PORT}/${MTX_PATH}
    runOnDemandRestart: no
```

_veryfatvideofile.mp4_ has **15 minutes** duration but ffmpeg can convert it and stream it to internal rtsp endpoint in **few seconds**. 
Then mediamtx streams the video to the client respecting to original PTS, so it takes 15 minutes to stream it all. 

Is it possible to stream it to the client at the maximum speed regardless the original PTS?

Thank you
