### DISCUSSION TITLE
no one is publishing to path 'compressed'

### DISCUSSION THREAD

**Discussion by jaemjaem** [bluenviron/mediamtx#457] [Questions]
If you run rtsp simple server and ffmpeg, I can see it at rtsp://localhost:8554/compressed in vlc.

```
./rtsp-simple-server
ffmpeg -i rtsp://localhost:8554/original -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:8554/compressed
```

But, 

```
paths:
  all:
  original:
    runOnPublish: ffmpeg -i rtsp://localhost:8554/original -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:8554/compressed
    runOnPublishRestart: yes

```

this doesn't work. (not docker, in local)
please tell me what is the difference. :(
