### DISCUSSION TITLE
Can I host an RTSP stream of my Windows desktop in realtime with this?

### DISCUSSION THREAD

**Discussion by ghost** [bluenviron/mediamtx#465] [Questions]
I'm trying to host an RTSP stream of my Windows desktop, is it possible with rtsp-simple-server?

**Comment by aler9** [comment]
Yes, you need to

1. Download a ffmpeg build for windows https://ffmpeg.org/download.html
2. Download the server
3. Edit the server configuration:

```yml

paths:
  desktop:
    runOnInit: ./path-to-ffmpeg/ffmpeg.exe -f gdigrab -framerate 10 -i desktop -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/desktop
    
```

4. Launch the server

[a comment by an automated account is not shown]
