### DISCUSSION TITLE
Does WHEP handshake failure trigger fallback to RTSP source?

### DISCUSSION THREAD

**Discussion by CheSauRie** [bluenviron/mediamtx#4666] [Questions]
### Question

Hi MediaMTX team and community,

I'm setting up a fallback in MediaMTX where the primary path uses a WHEP source, and the fallback is an RTSP stream. Here's my config:

```yaml
paths:
  mainstream:
    source: whep://camera/main/whep
    fallback: rtsp://camera-backup/stream
```
My question is:

- If the WHEP connection fails (e.g. handshake timeout or ICE connectivity issues), will MediaMTX automatically switch to the RTSP fallback?
- Are there any Gotchas specific to WHEP where the server won't detect handshake failure and thus won't trigger fallback?
- I know fallback works with RTSP->RTSP scenarios, but I couldn't find confirmation for WHEP->RTSP behavior.

Thanks for any insights or tests!
