### DISCUSSION TITLE
How to stream to youtube?

### DISCUSSION THREAD

**Discussion by m1000z** [bluenviron/mediamtx#481] [Questions]
I've been able to successfully "import" a stream from my camera with the rtsp-simple-server.  But I'm wondering what kind of configuration should I put in to stream the same contents to youtube?

**Comment by aler9** [comment]
You need to use `runOnPublish`:

```yml
paths:
  mypath:
    runOnPublish: ffmpeg -re -i rtsp://localhost:8554/mypath -c copy -f flv rtmp://rtmp-url-provided-by-youtube
```

[a comment by an automated account is not shown]
