### DISCUSSION TITLE
RTSP proxying not working with password that includes a #

### DISCUSSION THREAD

**Discussion by Afrostie** [bluenviron/mediamtx#559] [Questions]
## Which version are you using?

v0.17.2

## Which operating system are you using?

OS

- [ ] Linux
- [x] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

I have a camera that requires use of symbols in the password, so it has a # in the password. I am trying to setup a RTSP proxy for the camera however I can not include the authentication in the RTSP stream url as that is not valid. I assumed that I could set the password using the sourceUser and sourcePass options, however looking at the Wireshark trace the camera is returning a 401 but the server is not including any authentication. 
The camera with the same username and password works with VLC (using the authentication prompt) and in gstreamer using rtspsrc user-id=xxx and user-pw=xxx.

The configuration I was using:
``` yaml
paths:
  proxied:
    source: rtsp://192.168.16.114:554/AVStream1_1
    sourceUser: ...
    sourcePass: ...
```

I also see the following output from the server:
```
2021/09/07 08:50:48 D [0/0] [path proxied] [rtsp source] s->c RTSP/1.0 401 Unauthorized
2021/09/07 08:50:08 I [0/0] [path proxied] [rtsp source] ERR: invalid status code: 401 (Unauthorized)
```

If there is any other way to do the authentication or if you need any more information let me know.
Thanks
## Describe how to replicate the issue

1. start the server
2. Set a cameras password to include a # symbol
3. Setup proxying with a similar config as above
4. Check the console output for 401 Unauthorized responses

## Did you attach a network dump?

yes (I had to zip the .pcap otherwise github wouldn't let me upload it)
[capture.zip](https://github.com/aler9/rtsp-simple-server/files/7119859/capture.zip)

**Comment by aler9** [comment]
Hello, try using percent encoding in the password (replace # with %23) and let me know if it works:

```yml
paths:
  mypath:
    source: rtsp://myuser:my%23pass@192.168.16.114:554/AVStream1_1
```
