### DISCUSSION TITLE
New conf to publish a webcam with ZERO Latency on Windows

### DISCUSSION THREAD

**Discussion by fabriciorsf** [bluenviron/mediamtx#572] [General]
**New conf** to publish a **webcam** with **'ZERO' Latency** on **Windows**

```yml
paths:
  cam:
    runOnInit: ffmpeg -f dshow -i video="Integrated Webcam" -preset ultrafast -c:v libx264 -tune zerolatency -b:v 900k -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
```
