### DISCUSSION TITLE
"source:" apparently not working

### DISCUSSION THREAD

**Discussion by rmwiseman** [bluenviron/mediamtx#630] [Questions]
I've got a really simple setup, something like this:
```
paths:
  path1:
    readUser: username
    readPass: password
    runOnDemand: ffmpeg ... etc. ...
    runOnDemandRestart: yes
    runOnDemandStartTimeout: 30s
    runOnDemandCloseAfter: 30s
  path2:
    source: rtsp://username:password@hostname:8554/path1
```
I can view `rtsp://username:password@hostname:8554/path1` in VLC so I know that works.  But when I try to view `rtsp://hostname:8554/path2` it fails immediately with the corresponding server error `ERR: no one is publishing to path 'path2'` and also says `ERR: path must end with a slash (path2)`.

Am I missing something...?

-----

**UPDATE 1:**

It seems that, although the configuration is automatically reloaded when I change and save it, sometimes it is not properly applied and I actually have to restart the server.  If I don't, it appears that none of my paths work!

-----

**UPDATE 2:**

Since I can't now comment on this discussion, I'll add a comment here!  I have realised that what I've described in this discussion is actually a symptom of something else, and I've added an issue about that: https://github.com/aler9/rtsp-simple-server/issues/637
