### DISCUSSION TITLE
Server acting as a publisher to a remote address.

### DISCUSSION THREAD

**Discussion by migvel** [bluenviron/mediamtx#713] [Questions] [answered]
Hello,

I have two servers one local and another remote, readers can subscribe to either to the local one inside a LAN, or to the remote WAN.

Is there any way of tell to the local server to act as a publisher to the remote address for a given stream? 

Regards.

**Comment by migvel** [comment]
As it is pointed in another reply it can be done with FFMPEG, ie: ffmpeg -re -i rtsp://user:password@192.168.50.15:554/ -c copy -f rtsp rtsp://user:password@DOMAINNAME:8554/path

**Comment by aler9** [comment, marked as answer]
You can forward all streams from the local server to the remote server by using this configuration on the local server:

```yml
paths:
  all:
    runOnPublish: ffmpeg -re -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f rtsp rtsp://remote-ip/$RTSP_PATH
```

[a comment by an automated account is not shown]
