### DISCUSSION TITLE
RTSP Proxy + OnDemand Single Frame Capture  + HLS?

### DISCUSSION THREAD

**Discussion by calebcoverdale** [bluenviron/mediamtx#738] [Questions]
Hey there! 

I want to see if I can make this my dream program to help me sleep better at night! Just need a little bit of help. 

Here's what I am trying to do:
1. On Demand RTSP feeds - got this working with:
```
  example-path:
    source: rtsp://username:password@ipaddressofcamera:554/Streaming/Channels/102
    sourceOnDemand: yes
    sourceProtocol: tcp
    sourceOnDemandCloseAfter: 20s
```
2. HLS streams that someone can initiate (just visit the typical http://IPaddress:8888/example-path <-- works well! )

Now where I need help: 
3. Run FFMPEG to capture a screenshot every time that the HLS stream initiates after sourceOnDemand gets called and the status of the stream goes from "state="notReady" to Ready.

What this is going to do is just save the image to a docker volume with NGINX serving the images. I wish there was a way I could get this file via API calls, but I know it's just a dream at this point. 

Wondering if there was a proper way to run step 3 via docker and this image... I was so close to getting away with not using FFMPEG if it wasn't for needing an image endpoint... 

Thanks!
