### DISCUSSION TITLE
Running Bash Script before activate RunOnDemand for Ambarella Streaming Devices

### DISCUSSION THREAD

**Discussion by Tabarane** [bluenviron/mediamtx#836] [Questions]
Hello everyone,

so i have a camera which includes inside it a Ambarella Streaming unit which need to get commands via NC or Telnet on Port 7878 in order to activate the RTSP Stream, only then RTSP SIMPLE Server can connect to.

i have created Bash Script which activate the RTSP server inside the camera to enable the stream, question is:
how we can issue command from RTSP SIMPLE SERVER so that the script is activated first then start the re-streaming process with RTSP SIMPLE server

**Comment by aler9** [comment]
```yml
paths:
  mycamera:
    runOnInit: sh -c 'echo mycommand | nc 7878 && ffmpeg -re -i rtsp://camera-url -c copy -f rtsp rtsp://localhost:8554/mycamera'
```

[a comment by an automated account is not shown]
