### DISCUSSION TITLE
Forcing TCP doesn't quite seem to work

### DISCUSSION THREAD

**Discussion by rmwiseman** [bluenviron/mediamtx#860] [Questions] [answered]
Hi,

I've got some particular cameras I'm trying to proxy via RTSP Simple Server.  They're all the same model (I'm pretty sure) and those connected via a cable rather than radio link work fine.  However, those connected wirelessly (in the link from the camera to the router) seem more problematic.

I've found I can happily view them directly using `vlc --rtsp-tcp rtsp://camera_ip/path` but if I omit the `--rtsp-tcp` switch, it fails to display an image but counts the seconds.

If I proxy the stream, however, VLC can't even play it.

The relevant bits of the YAML file are:

```
logLevel: debug

protocols: [tcp]

paths:
  all:
    publishUser: myUsername
    publishPass: myPassword
    sourceProtocol: tcp

  full/theCameraID:
    readUser: theUsername
    readPass: thePassword
    source: rtsp://camera_ip/path
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 30s
    sourceOnDemandCloseAfter: 30s
```

I think that's all I can do to make it use TCP, and I would expect this stream to work in VLC just as the direct camera stream does.  (But as I said, it doesn't: VLC can't play it.)

I've also used `ffmpeg` to grab 30 seconds of video, first direct from the camera (which looks fine, regardless of whether I re-encode the stream or use `-vcodec copy`) but if I try to grab 30s of the proxied stream (using `-vcodec copy`), the video ends up with a very messy picture (lots of green, very little definition).  I used the same `ffmpeg` command for each, again attempting to force TCP:

```
ffmpeg -rtsp_transport tcp -rtsp_flags prefer_tcp -t 30 -i theRtspUrl -an -vcodec copy thirty.mp4
```

Here's an example frame from the messy (proxied) version:

![vlcsnap-2022-03-01-16h25m59s916](https://user-images.githubusercontent.com/10866705/156208144-454e9426-ef60-483e-a75b-b2ec62fd85a2.png)

Am I wrong to expect the stream simply to be proxied and to work the same as the direct camera stream?  Have I missed something important in the configuration?

Thanks!

**Comment by aler9** [comment, marked as answer]
You need to add `sourceProtocol` to `full/theCameraID` too:

```yml
logLevel: debug

protocols: [tcp]

paths:
  all:
    publishUser: myUsername
    publishPass: myPassword
    sourceProtocol: tcp

  full/theCameraID:
    readUser: theUsername
    readPass: thePassword
    source: rtsp://camera_ip/path
    sourceProtocol: tcp
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 30s
    sourceOnDemandCloseAfter: 30s
```

I agree that UDP streaming is not particularly reliable, but a lot is being done to improve it in the near future, starting from NACKs and packet reordering.
