### DISCUSSION TITLE
Unable to record pathes in => second path depth (/path1/path2)

### DISCUSSION THREAD

**Discussion by DonKingMat** [bluenviron/mediamtx#869] [Questions]
Dears.

Did anyone of you guys succeed in recording a nested or sub path so far?

For example if I run a publish to `rtmp://domain.fancy.my/demo?user=user&pass=pass` and having in .yml:

```
paths:
  demo:
    publishUser: user
    publishPass: pass
    readUser: public
    readPass: public
    runOnReady: /usr/bin/ffmpeg -i rtsp://public:public@localhost:8554/demo -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 mp4/fly_%Y-%m-%d_%H-%M-%S.mp4
    runOnReadyRestart: yes
```

then it will recored that ffmpeg stream as expected.

But if I am starting to publish to For example if I run a publish to `rtmp://domain.fancy.my/demo/special?user=user&pass=pass` this will start as publishing with `is publishing to path 'demo/special', 2 tracks` but I am unable to trigger the `runOnReady:` ffmpeg here.
The path-logic (`readUser:`, `ReadPass:` ...) will be grabbed from that specific path declaration `demo:` but not that `runOnReady:`.

I also was trying to did some RegEx but does not succeed.

By the [general specification of RTSP](https://datatracker.ietf.org/doc/html/rfc2326#section-3.2) it is everything allowed and some (iOS)-App builder does not allow single path URI and force me to use a sub-path like /demo/special for publishing RTSP ... 

I did not find my fault. I appreciate any of your comments.

**Comment by aler9** [comment]
Path parameters aren't inherited in any way from a path to another, even if they share a common prefix.

Parameters under path `demo` are applied only on streams that are published to `rtmp://domain.fancy.my/demo?user=user&pass=pass`, not `rtmp://domain.fancy.my/demo/special?user=user&pass=pass`.

If you want to use the path `demo/special`, just use it in the configuration file:

```yml
paths:
  'demo/special':
    publishUser: user
    publishPass: pass
    readUser: public
    readPass: public
    runOnReady: /usr/bin/ffmpeg -i rtsp://public:public@localhost:8554/demo -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 mp4/fly_%Y-%m-%d_%H-%M-%S.mp4
    runOnReadyRestart: yes

```

[a comment by an automated account is not shown]
