### DISCUSSION TITLE
Merge streams

### DISCUSSION THREAD

**Discussion by Wheemer** [bluenviron/mediamtx#893] [Questions]
I have four cameras running through simple, it would be nice to have a 2x2 grid view of the feeds combined. I currently am using OBS to accomplish this via rtmp publishing to simple. However OBS frequently has a frozen feed on one of the cameras. That's why I was wondering if simple can accomplish this without the need for OBS.

Thanks a lot!

**Comment by aler9** [comment]
Hello, you can do this with ffmpeg; use this configuration file:

```yml
paths:
  camera1:
    source: rtsp://...

  camera2:
    source: rtsp://...

  camera3:
    source: rtsp://...

  camera4:
    source: rtsp://...

  merged:
    runOnInitRestart: yes
    runOnInit: >
      ffmpeg -i rtsp://localhost:8554/camera1 -i rtsp://localhost:8554/camera2 -i rtsp://localhost:8554/camera3 -i rtsp://localhost:8554/camera4
      -filter_complex "[0:v][1:v]hstack=inputs=2[top]; [2:v][3:v]hstack=inputs=2[bottom]; [top][bottom]vstack=inputs=2[v]"
      -map "[v]" -c:v libx264 -preset ultrafast -b:v 1000k
      -f rtsp rtsp://localhost:8554/merged
```

Replace `camera1`, `camera2`, etc with the names of your cameras. Then start the server, wait some seconds and read from `rtsp://localhost:8554/merged`.
