### DISCUSSION TITLE
Help needed: webcam (rtsp) to youtube with fallback

### DISCUSSION THREAD

**Discussion by MrCoala** [bluenviron/mediamtx#894] [Questions]
Hello,

i got an rtsp webcam which i want to publish to youtube. The (animal) webcam is powered by solar panels so i have a fallback image/mp4 which i want to be streamed when the camera is not available.

I tried to set it up like that:

```
paths:
  main:
    source: rtsp://url:port/path
    sourceProtocol: automatic
    fallback: rtsp://localhost:8554/fallbackpath

  fallbackpath:
    runOnInit: ffmpeg -re -stream_loop -1 -i /home/rtsp/animalcam/out.mp4 -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
```

It doesnt seem to work. Any idea on how i could achieve my goal with rtsp simple server?
