### DISCUSSION TITLE
runOnInit command exited with code 0

### DISCUSSION THREAD

**Discussion by promd** [bluenviron/mediamtx#908] [Questions]
Hi,
1st off: Thanks for the project! I ended up here after trying ffmpeg commands for days.

scenario:
I need to re-size the rstp stream from a webcam, because the recipient is very picky on resolution. (And the cam is very inflexible).
I did see a variation to the below here in the discussions, but somehow, it does not work. I always get this message:

`[path unifi42n] runOnInit command exited with code 0`

[EDIT]
The FFMPEG command works in a shell if I run it directly on the stream from the Cam and publish that to the server. - So the syntax and parameters are ok.

Any ideas what I am doing wrong ?

```
paths:
  unifi:
    source: rtsp://192.168.000.000:7447/HZ36G8j2FE6OaM3p
  unifi42n:
    # This command works in a shell:
    #         ./ffmpeg -i rtsp://192.168.000.000:7447/HZ36G8j2FE6OaM3p -acodec copy 
    #        -c:v libx264 -vf scale=640x480 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 
    #        -f rtsp rtsp://localhost:8554/test
    # Newlines added for readability!
    runOnInit: ffmpeg -i rtsp://localhost:$RTSP_PORT/unifi -acodec copy 
                   -c:v libx264 -vf scale=640x480 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 
                   -f rtsp rtsp://localhost:$RTSP_PORT/unifi42n
    # Restart the command if it exits suddenly.
    runOnInitRestart: yes
```
