### DISCUSSION TITLE
How to correctly convert RTSP H265 (hevc) stream to H264 to be transcoded to HLS?

### DISCUSSION THREAD

**Discussion by swayok** [bluenviron/mediamtx#915] [Questions] [answered]
Hi.
I have a pool of webcams that produce RTSP streams using H265 (hexvc) codec. Unfortunately I cannot recofigure them because CCTV soft installed in that building for security office somehow reconfigures cameras back to H265. 

The task is to proxy and transcode RTSP screams from webacms to HLS streams.

I need to recode streams to H264 so that streams can be transcoded to HLS. 
I have installed ffmpeg an I have tried that cjnfiguration from Readme and could not get it working - there are almost no information about how exactly it works =(
```
paths:
  all:
  original:
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/compressed
    runOnReadyRestart: yes
```

My config looks like this:
```
paths:
  test:
    source: "rtsp://255.255.255.255:41150/profile2"
    sourceOnDemand: yes
  nl12_1:
    source: "rtsp://255.255.255.255:41005/profile3"
    sourceOnDemand: no
  nl12_2:
    source: "rtsp://255.255.255.255:41006/profile2"
    sourceOnDemand: yes
  nl12_3:
    source: "rtsp://255.255.255.255:41008/profile2"
    sourceOnDemand: no
  nl12_4:
    source: "rtsp://255.255.255.255:41011/profile2"
    sourceOnDemand: yes
  nl14_1:
    source: "rtsp://255.255.255.255:41001/profile2"
    sourceOnDemand: yes
  nl14_2:
    source: "rtsp://255.255.255.255:41002/profile2"
    sourceOnDemand: yes
  nl14_3:
    source: "rtsp://255.255.255.255:41003/profile2"
    sourceOnDemand: yes
  nl14_4:
    source: "rtsp://255.255.255.255:41004/profile2"
    sourceOnDemand: yes
  nl14_5:
    source: "rtsp://255.255.255.255:41007/profile2"
    sourceOnDemand: yes
  nl14_6:
    source: "rtsp://255.255.255.255:41009/profile2"
    sourceOnDemand: yes
  nl14_7:
    source: "rtsp://255.255.255.255:41010/profile2"
    sourceOnDemand: yes
```

Can you help me understand what should I do?

**Comment by swayok** [comment]
Ok. It seems I have found possible solution in other discussions:

```
nl12_2:
    runOnDemand: ffmpeg -i rtsp://255.255.255.255:41006/profile2 -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnDemandRestart: yes
```

Unfortunately I receive an error from FFMPEG: 
`[rtsp @ 0x7744800] method SETUP failed: 453 Not Enough Bandwidth`

Using something like this is not working either:
```
recoded:
    runOnDemand: ffmpeg -i rtsp://localhost:$RTSP_PORT/nl12_1 -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnDemandRestart: yes
  nl12_1:
    source: "rtsp://255.255.255.255:41005/profile3"
    sourceOnDemand: no
```
It tries to do something but after 2 ffmpeg runs it drops connection

```
2022/04/14 20:22:42 INF [RTSP] [conn 127.0.0.1:58398] opened
2022/04/14 20:22:42 INF [RTSP] [session 604574089] opened by 127.0.0.1:58398
2022/04/14 20:22:42 INF [RTSP] [session 604574089] is reading from path 'nl12_1', 2 tracks with UDP
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://localhost:8554/nl12_1':
  Metadata:
    title           : Stream
  Duration: N/A, start: 0.028178, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 704x576, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (pcm_alaw (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x627d440] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0x627d440] profile Constrained Baseline, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x627d440] 264 - core 164 r3094 bfc87b7 - H.264/MPEG-4 AVC codec - Copyleft 2003-2022 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=abr mbtree=0 bitrate=500 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
2022/04/14 20:22:52 INF [path recoded] runOnDemand command stopped
2022/04/14 20:22:52 INF [HLS] [muxer recoded] closed (source of path 'recoded' has timed out)
Finishing stream 0:1 without any data written to it.
[aac @ 0x6266180] Too many bits 8832.000000 > 6144 per frame requested, clamping to max
2022/04/14 20:22:52 INF [RTSP] [conn 127.0.0.1:60348] opened
2022/04/14 20:22:52 INF [RTSP] [session 273550245] opened by 127.0.0.1:60348
2022/04/14 20:22:52 INF [RTSP] [session 273550245] is publishing to path 'recoded', 2 tracks with UDP
Output #0, rtsp, to 'rtsp://localhost:8554/recoded':
  Metadata:
    title           : Stream
    encoder         : Lavf59.16.100
  Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 704x576, q=2-31, 500 kb/s, 25 fps, 90k tbn
    Metadata:
      encoder         : Lavc59.18.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/500000 buffer size: 0 vbv_delay: N/A
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp, 48 kb/s
    Metadata:
      encoder         : Lavc59.18.100 aac
2022/04/14 20:22:52 INF [RTSP] [session 273550245] closed (teared down by 127.0.0.1:60348)
2022/04/14 20:22:52 INF [RTSP] [conn 127.0.0.1:60348] closed (read tcp 127.0.0.1:8554->127.0.0.1:60348: read: connection reset by peer)
frame=  247 fps= 73 q=28.0 Lsize=N/A time=00:00:09.84 bitrate=N/A dup=32 drop=0 speed=2.89x    
video:545kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libx264 @ 0x627d440] frame I:1     Avg QP:39.00  size: 32747
[libx264 @ 0x627d440] frame P:246   Avg QP:31.61  size:  2133
[libx264 @ 0x627d440] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0x627d440] mb P  I16..4:  0.5%  0.0%  0.0%  P16..4: 14.2%  0.0%  0.0%  0.0%  0.0%    skip:85.3%
[libx264 @ 0x627d440] final ratefactor: 35.34
[libx264 @ 0x627d440] coded y,uvDC,uvAC intra: 65.4% 21.9% 7.9% inter: 6.2% 1.4% 0.1%
[libx264 @ 0x627d440] i16 v,h,dc,p: 35% 14% 36% 14%
[libx264 @ 0x627d440] i8c dc,h,v,p: 63% 10% 23%  4%
[libx264 @ 0x627d440] kb/s:451.40
[aac @ 0x6266180] Qavg: nan
2022/04/14 20:22:52 INF [RTSP] [session 604574089] closed (teared down by 127.0.0.1:58398)
2022/04/14 20:22:52 INF [RTSP] [conn 127.0.0.1:58398] closed (read tcp 127.0.0.1:8554->127.0.0.1:58398: read: connection reset by peer)
Exiting normally, received signal 2.
```

Any ideas?

**Comment by aler9** [comment, marked as answer]
Hello, 

```
[aac @ 0x6266180] Too many bits 8832.000000 > 6144 per frame requested, clamping to max
```

There's something wrong with the audio track, try converting only the video track by editing the ffmpeg command in this way:

```yml
recoded:
    runOnDemand: ffmpeg -i rtsp://localhost:$RTSP_PORT/nl12_1 -map 0:v:0 -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnDemandRestart: yes

  nl12_1:
    source: "rtsp://255.255.255.255:41005/profile3"
    sourceOnDemand: no

```
