### DISCUSSION TITLE
Adding docker-compose usage example in README?

### DISCUSSION THREAD

**Discussion by aggo15** [bluenviron/mediamtx#925] [General]
Hi @aler9 ,

Regarding your comment [here](https://github.com/aler9/rtsp-simple-server/discussions/679#discussioncomment-2609218). May I suggest to add one small section in the README for docker-compose example usage? As an additional option for Raspberry Pi users to get up to speed more quickly.

Here is the Dockerfile for `picamcapture:1.0` that use balenalib/raspberry-pi image with ffmpeg installed.
```
# Reference to balenalib image, you can use latest buster-run image as well
FROM balenalib/raspberry-pi:buster-run-20210929
# Install ffmpeg package
RUN install_packages ffmpeg
```

Here is the docker-compose I used to link everything together.
```
version: "2.4"
services:
  rtmpserver:
    image: aler9/rtsp-simple-server
    ports:
    - "8554:8554"
    - "1935:1935"
    - "8888:8888"
    - "9997:9997"
    environment:
    - RTSP_PROTOCOLS=tcp
    - RTSP_API=yes
    - RTSP_APIADDRESS=0.0.0.0:9997
    networks:
      camnet:
        ipv4_address: 10.10.5.2
  picam:
    image: picamcapture:1.0
    devices:
    - "/dev/vchiq:/dev/vchiq"
    - "/dev/vcsm-cma:/dev/vcsm-cma"
    networks:
      camnet:
        ipv4_address: 10.10.5.3
    depends_on:
    - rtmpserver
    entrypoint: sh
    command: [ "-c",
    "raspivid -n -fl -t 0 -rot 270 -w 1280 -h 720 -fps 15 -fw -l -b 500000 -g 5 -o - | ffmpeg -re -i - -c:v copy -strict experimental -f flv rtmp://10.10.5.2/app/stream" ]
networks:
  camnet:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      - subnet: 10.10.5.0/24
        gateway: 10.10.5.1
```

I haven't actually work on open source project before, but if you're ok with it, I can help to modify the README file via pull request. Let me know what is your thought. 

Thank you.

[a comment by an automated account is not shown]
