### DISCUSSION TITLE
RTMP stream converted to MPEG-2

### DISCUSSION THREAD

**Discussion by Killers0992** [bluenviron/mediamtx#931] [Questions]
Can someone help with converting rtmp stream to MPEG-2 with audio + video? Like I have existing stream running on rtmp and i want  to convert that one to new stream which will contain mpeg-2 stream, if someone can provide some ffmpeg example or even rtsp-simple-server config?

**Comment by aler9** [comment]
```yml
paths:
  mypath:
    runOnReady: ffmpeg -i rtsp://localhost:8554/$RTSP_PATH -codec:v mpeg2video -qscale:v 2 -codec:a mp2 -b:a 192k -f rtsp rtsp://localhost:8554/mpeg2
    runOnReadyRestart: yes
  mpeg2:
```

You can publish to `rtmp://localhost/mypath` with any codec you like, and read from `rtsp://localhost/mpeg2` with MPEG2. Please be aware that at the moment the server doesn't support reading a MPEG2 track with RTMP, therefore, you have to read with RTSP.

[a comment by an automated account is not shown]
