### DISCUSSION TITLE
get empty username password during external authentication

### DISCUSSION THREAD

**Discussion by sun0620** [bluenviron/mediamtx#936] [Questions]
Im using raspberry pi for hosting rtsp-simple-server:v0.18.2 by using docker, and receive empty username and password during external authentication

### Config
```yml
paths:
  mystream:
    runOnInit: ffmpeg -rtsp_transport tcp -i rtsp://xxxx:xxxx@x.x.x.x:xxxx/cam -c copy -rtsp_transport tcp -f rtsp rtsp://localhost:8554/mystream
    runOnInitRestart: yes
externalAuthenticationURL: http://xx.xx.xx.xx:3000/
```

### Command for connect rasp-simple-server
```
ffmpeg -i "rtsp://lala:lala@xx.xx.xx.xx:xxxx/mystream" -c copy output.mp4
```

### Body
```json
{
  ip: 'xx.xx.xx.xx',
  user: '',
  password: '',
  path: 'mystream',
  action: 'read',
  query: ''
}
```
