### DISCUSSION TITLE
RTSP source to RTMP destination

### DISCUSSION THREAD

**Discussion by JCFontoura** [bluenviron/mediamtx#971] [Questions] [answered]
Hi.
I have a RTSP camera in my network, and I would like to get this stream and send to a RTMP server that I have on the cloud.
With purely ffmpeg I use:
`ffmpeg -rtsp_transport tcp -i rtsp://<my_camera_ip_port> -c copy -f flv -flvflags no_duration_filesize rtmp://<my_cloud_ip_port>
`But eventually I get some ffmpeg error or it freezes in some frame, and stops sending them (usually these problems happens when the network is unstable). But I would like something reliable, i.e. when the network is stable again, it resumes sending the rtsp stream to the rtmp destination. 

Can rtsp-simple-server get a source rtsp and send to a rtmp destination?

**Comment by aler9** [comment, marked as answer]
yes, of course:

```yml
paths:
  mystream:
    source: rtsp://my-camera-rtsp-url
    runOnReady: ffmpeg -i rtsp://localhost:8554/mystream -c copy -f flv -flvflags no_duration_filesize rtmp://my-cloud-ip-port
    runOnReadyRestart: yes
```

[a comment by an automated account is not shown]
