### DISCUSSION TITLE
Proxy other server strp. Read with HSL 404 not found

### DISCUSSION THREAD

**Discussion by kirning** [bluenviron/mediamtx#983] [Questions]
I proxy other server strp. But i use html to read. 404

My config
```yml
paths:
  proxied:
    source: rtsp://xxx/h264/ch3/main/av_stream
```

My html:

```html
    <iframe src="http://localhost:8888/proxied" scrolling="no"></iframe>

    <video src="http://localhost:8888/proxied/index.m3u8"></video>
```

error:

![image](https://user-images.githubusercontent.com/7327933/172849029-ac93a2b4-c56e-40af-af17-e37b304d0c5d.png)
