### DISCUSSION TITLE
Authentication not work

### DISCUSSION THREAD

**Discussion by FunUser-2022** [bluenviron/mediamtx#992] [Questions]
Hi,
i have inserted the following lines in the "rtsp-simple-server.yml" configuration file :
```
paths:
  all:
    publishUser: myuser
    publishPass: mypass

    readUser: user
    readPass: userpass
```
But authentication doesn't work.
It is possible to see even without the credentials.
Why?

How to set username and password for streaming?

I use version v0.19.1 on armv6.

Thank you!

[a comment by an automated account is not shown]
