### DISCUSSION TITLE
RTSP server from JPEG source

### DISCUSSION THREAD

**Discussion by SirLouen** [bluenviron/mediamtx#996] [Questions]
I have an HTTP source that publish a still JPEG image in an URL
Is it possible to use such source to create a RTSP stream server with RTSP Simple Server?

**Comment by aler9** [comment]
Yes, you have to convert it from JPEG to RTSP with ffmpeg:

```yml
paths:
  mystream:
    runOnInit: ffmpeg -i http://myurl/myimage.jpeg -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
```

I don't know if this command will work on your specific source, anyway you have to play with ffmpeg until it can read your source. Then you can convert it into H264 and publish it with RTSP.

[a comment by an automated account is not shown]
