### ISSUE TITLE
Support proxying multiple HLS resolutions

### ISSUE THREAD

**Issue by ChronoBrake** [bluenviron/mediamtx#1272]
## Describe the feature
Hey Sir, any news about #431?
Description
How to do it when i wanna proxing something?
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=763904,RESOLUTION=854x480,NAME="480p"
hls-480p-127f2.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1327104,RESOLUTION=1280x720,NAME="720p"
hls-720p-51ffc.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2760704,RESOLUTION=1920x1080,NAME="1080p"
hls-1080p-915de.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=423936,RESOLUTION=640x360,NAME="360p"
hls-360p-be7ff.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=155648,RESOLUTION=444x250,NAME="250p"
hls-250p-6c02c.m3u8
```

config:
paths:
```
  proxied:
    source: sourcelink
```

Regards

**Comment by torbenraab** [comment]
Hi there,
I think this feature would be a big improvement!
With this kind of functionality you would have a real alternative to a stream on YouTube.
Is there anything we could do to push this feature up the list? Unfortunately I'm not experienced in Go.
Thanks in advance!

**Comment by aler9** [comment]
This is unrelated from #431 but surely it would be an improvement to proxy all variants of an existing HLS stream, or at least giving users the ability to pick the variants they want to proxy.

The problem with proxying all available variants is that the resulting stream is huge in terms of bandwidth and i don't think most user wants it. Therefore, we could give users a choice like:


```yml
paths:
  proxied:
    source: http://existing
    sourceVariants: [1920x1080, 854x480]
```

**Comment by aler9** [comment]
This feature won't be developed since it's already possible to proxy a HLS variant or all available HLS variants at once by using the variant URL.

Let's suppose we have this playlist (multivariant playlist):

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=763904,RESOLUTION=854x480,NAME="480p"
hls-480p-127f2.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1327104,RESOLUTION=1280x720,NAME="720p"
hls-720p-51ffc.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2760704,RESOLUTION=1920x1080,NAME="1080p"
hls-1080p-915de.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=423936,RESOLUTION=640x360,NAME="360p"
hls-360p-be7ff.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=155648,RESOLUTION=444x250,NAME="250p"
hls-250p-6c02c.m3u8
```

let's also suppose that this multivariant playlist is available at

```
https://example.com/hls/stream.m3u8
```

If you want to proxy the `854x480` variant, append its path to the folder of the multivariant playlist:

```yml
paths:
  proxied:
    source: https://example.com/hls/hls-480p-127f2.m3u8
```

If you want to proxy all available variants, create a path for each variant:

```yml
paths:
  proxied1:
    source: https://example.com/hls/hls-480p-127f2.m3u8
  proxied2:
    source: https://example.com/hls/hls-1080p-915de.m3u8
...
```
