### ISSUE TITLE
Cert-File not found after migration from RTSP-Simple-Server Docker to MediaMTX

### ISSUE THREAD

**Issue by BOFH90** [bluenviron/mediamtx#1980]
## Which version are you using?

v0.23.6 (latest) from DockerHUB

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I´ve mounted the certificate folder (/root/acme.sh/) in RTSP-Simple-Server Container and the new MediaMTX Container with this command:
`-v /root/.acme.sh/:/root/.acme.sh/ `

In the configuration i entered:
```
encryption: "optional"
serverKey: /root/.acme.sh/domain.example/domain.example.key
serverCert: /root/.acme.sh/domain.example/fullchain.cer
```

This works with RTSP-Simple-Server for months, even if I recreate it completely from scratch, but not with MediaMTX.
MediaMTX starts up and stops directly with this in the logs:

`2023/06/23 04:46:47 ERR open /root/.acme.sh/domain.example/fullchain.cer: no such file or directory
`
As i cannot attach to the container, with no binarys on it. I cannot verify if the path is readable. But it is with the exact same configuration an path with the previous one, before it got renamend.

Describe how to replicate the issue

## Describe how to replicate the issue

Rename the rtsp-simple-server.yml to mediamtx.yml and create the new container with the same Volumes as the old one.

## Did you attach the server logs?

`2023/06/23 04:46:47 ERR open /root/.acme.sh/domain.example/fullchain.cer: no such file or directory
`
no

## Did you attach a network dump?

no

**Comment by BOFH90** [comment]
sure :) i just replaced my domain-name with "example". rtsp-simple-server runs flawless with the same cert-file and its location and permissions.

`docker run -d --name=MediaMTX --network=host -v /opt/mediamtx/mediamtx.yml:/mediamtx.yml -v /root/.acme.sh/:/root/.acme.sh/ bluenviron/mediamtx`

```
/root/.acme.sh/ipc.example.de_ecc/:
insgesamt 36
drwxr-xr-x 2 root root 4096 22. Jun 13:08 backup
-rw-r--r-- 1 root root 3751 22. Jun 13:08 ca.cer
-rw-r--r-- 1 root root 5288 22. Jun 13:08 fullchain.cer
-rw-r--r-- 1 root root 1537 22. Jun 13:08 ipc.example.de.cer
-rw-r--r-- 1 root root  793 22. Jun 13:08 ipc.example.de.conf
-rw-r--r-- 1 root root  558 22. Jun 13:08 ipc.example.de.csr
-rw-r--r-- 1 root root  190 22. Jun 13:08 ipc.example.de.csr.conf
-rw------- 1 root root  288 22. Jun 13:08 ipc.example.de.key
```

```
~/ cat /opt/mediamtx/mediamtx.yml

###############################################
# General parameters

# sets the verbosity of the program; available values are "error", "warn", "info", "debug".
logLevel: info
# destinations of log messages; available values are "stdout", "file" and "syslog".
logDestinations: [stdout]
# if "file" is in logDestinations, this is the file which will receive the logs.
logFile: rtsp-simple-server.log

# timeout of read operations.
readTimeout: 10s
# timeout of write operations.
writeTimeout: 10s
# number of read buffers.
# a higher number allows a higher throughput,
# a lower number allows to save RAM.
readBufferCount: 512

# enable the HTTP API.
api: no
# address of the API listener.
apiAddress: 127.0.0.1:9997

# enable Prometheus-compatible metrics.
metrics: no
# address of the metrics listener.
metricsAddress: 127.0.0.1:9998

# enable pprof-compatible endpoint to monitor performances.
pprof: no
# address of the pprof listener.
pprofAddress: 127.0.0.1:9999

# command to run when a client connects to the server.
# this is terminated with SIGINT when a client disconnects from the server.
# the server port is available in the RTSP_PORT variable.
runOnConnect:
# the restart parameter allows to restart the command if it exits suddenly.
runOnConnectRestart: no

###############################################
# RTSP parameters

# disable support for the RTSP protocol.
rtspDisable: no
# supported RTSP transport protocols.
# UDP is the most performant, but doesn't work when there's a NAT/firewall between
# server and clients, and doesn't support encryption.
# UDP-multicast allows to save bandwidth when clients are all in the same LAN.
# TCP is the most versatile, and does support encryption.
# The handshake is always performed with TCP.
protocols: [tcp]
# encrypt handshake and TCP streams with TLS (RTSPS).
# available values are "no", "strict", "optional".
encryption: "optional"
# address of the TCP/RTSP listener. This is needed only when encryption is "no" or "optional".
rtspAddress: :8554
# address of the TCP/TLS/RTSPS listener. This is needed only when encryption is "strict" or "optional".
rtspsAddress: :8555
# address of the UDP/RTP listener. This is needed only when "udp" is in protocols.
rtpAddress: :8000
# address of the UDP/RTCP listener. This is needed only when "udp" is in protocols.
rtcpAddress: :8001
# IP range of all UDP-multicast listeners. This is needed only when "multicast" is in protocols.
multicastIPRange: 224.1.0.0/16
# port of all UDP-multicast/RTP listeners. This is needed only when "multicast" is in protocols.
multicastRTPPort: 8002
# port of all UDP-multicast/RTCP listeners. This is needed only when "multicast" is in protocols.
multicastRTCPPort: 8003
# path to the server key. This is needed only when encryption is "strict" or "optional".
# this can be generated with:
# openssl genrsa -out server.key 2048
# openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650
serverKey: /root/.acme.sh/ipc.example.de_ecc/ipc.example.de.key
# path to the server certificate. This is needed only when encryption is "strict" or "optional".
serverCert: /root/.acme.sh/ipc.example.de_ecc/fullchain.cer
# authentication methods.
authMethods: [basic, digest]

###############################################
# RTMP parameters

# disable support for the RTMP protocol.
rtmpDisable: no
# address of the RTMP listener.
rtmpAddress: :1935

###############################################
# HLS parameters

# disable support for the HLS protocol.
hlsDisable: no
# address of the HLS listener.
hlsAddress: :8888
# by default, HLS is generated only when requested by a user;
# this option allows to generate it always, avoiding an initial delay.
hlsAlwaysRemux: no
# number of HLS segments to generate.
# increasing segments allows more buffering,
# decreasing segments decreases latency.
hlsSegmentCount: 3
# minimum duration of each segment.
# the final segment duration is also influenced by the interval between IDR frames,
# since the server changes the segment duration to include at least a IDR frame in each one.
hlsSegmentDuration: 1s
# value of the Access-Control-Allow-Origin header provided in every HTTP response.
# This allows to play the HLS stream from an external website.
hlsAllowOrigin: '*'

###############################################
# Path parameters

# these settings are path-dependent.
# it's possible to use regular expressions by using a tilde as prefix.
# for example, "~^(test1|test2)$" will match both "test1" and "test2".
# for example, "~^prefix" will match all paths that start with "prefix".
# the settings under the path "all" are applied to all paths that do not match
# another entry.
paths:
  haustuer:
    source: rtsp://172.26.1.5:554/s1
    readUser: example
    readPass: example
  hof1:
    source: rtsp://172.26.1.3:554/s1
    readUser: example
    readPass: example
  hof2:
    source: rtsp://172.26.1.2:554/s1
    readUser: example
    readPass: example
  strasse:
    source: rtsp://172.26.1.6:554/s1
    readUser: example
    readPass: example
  garten1:
    source: rtsp://172.26.1.1:554/s1
    readUser: example
    readPass: example
  garten2:
    source: rtsp://172.26.1.7:554/s1
    readUser: example
    readPass: example
  garten3:
    source: rtsp://michael:example@172.26.1.9:554/Streaming/Channels/102
    readUser: example
    readPass: example
  vorgarten:
    source: rtsp://172.26.1.8:554/s1
    readUser: example
    readPass: example
  nebeneingang:
    source: rtsp://172.26.3.2:554/h264_stream
    readUser: example
    readPass: example
  eingang:
    source: rtsp://172.26.3.1:554/h264_stream
    readUser: example
    readPass: example
  vogelkaefig:
    source: rtsp://michael:example@172.26.1.10:554/Streaming/Channels/102
    readUser: example
    readPass: example
```

**Comment by aler9** [comment]
I'm unable to replicate the issue. These are the steps i followed and everything worked flawlessly:

```
sudo mkdir -p /root/.acme.sh/ipc.example.de_ecc
```

```
sudo openssl genrsa -out /root/.acme.sh/ipc.example.de_ecc/ipc.example.de.key 2048
sudo openssl req -new -x509 -sha256 -key /root/.acme.sh/ipc.example.de_ecc/ipc.example.de.key -out /root/.acme.sh/ipc.example.de_ecc/fullchain.cer -days 3650
```

```
sudo mkdir -p /opt/mediamtx
sudo tee /opt/mediamtx/mediamtx.yml << EOF

###############################################
# General parameters

# sets the verbosity of the program; available values are "error", "warn", "info", "debug".
logLevel: info
# destinations of log messages; available values are "stdout", "file" and "syslog".
logDestinations: [stdout]
# if "file" is in logDestinations, this is the file which will receive the logs.
logFile: rtsp-simple-server.log

# timeout of read operations.
readTimeout: 10s
# timeout of write operations.
writeTimeout: 10s
# number of read buffers.
# a higher number allows a higher throughput,
# a lower number allows to save RAM.
readBufferCount: 512

# enable the HTTP API.
api: no
# address of the API listener.
apiAddress: 127.0.0.1:9997

# enable Prometheus-compatible metrics.
metrics: no
# address of the metrics listener.
metricsAddress: 127.0.0.1:9998

# enable pprof-compatible endpoint to monitor performances.
pprof: no
# address of the pprof listener.
pprofAddress: 127.0.0.1:9999

# command to run when a client connects to the server.
# this is terminated with SIGINT when a client disconnects from the server.
# the server port is available in the RTSP_PORT variable.
runOnConnect:
# the restart parameter allows to restart the command if it exits suddenly.
runOnConnectRestart: no

###############################################
# RTSP parameters

# disable support for the RTSP protocol.
rtspDisable: no
# supported RTSP transport protocols.
# UDP is the most performant, but doesn't work when there's a NAT/firewall between
# server and clients, and doesn't support encryption.
# UDP-multicast allows to save bandwidth when clients are all in the same LAN.
# TCP is the most versatile, and does support encryption.
# The handshake is always performed with TCP.
protocols: [tcp]
# encrypt handshake and TCP streams with TLS (RTSPS).
# available values are "no", "strict", "optional".
encryption: "optional"
# address of the TCP/RTSP listener. This is needed only when encryption is "no" or "optional".
rtspAddress: :8554
# address of the TCP/TLS/RTSPS listener. This is needed only when encryption is "strict" or "optional".
rtspsAddress: :8555
# address of the UDP/RTP listener. This is needed only when "udp" is in protocols.
rtpAddress: :8000
# address of the UDP/RTCP listener. This is needed only when "udp" is in protocols.
rtcpAddress: :8001
# IP range of all UDP-multicast listeners. This is needed only when "multicast" is in protocols.
multicastIPRange: 224.1.0.0/16
# port of all UDP-multicast/RTP listeners. This is needed only when "multicast" is in protocols.
multicastRTPPort: 8002
# port of all UDP-multicast/RTCP listeners. This is needed only when "multicast" is in protocols.
multicastRTCPPort: 8003
# path to the server key. This is needed only when encryption is "strict" or "optional".
# this can be generated with:
# openssl genrsa -out server.key 2048
# openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650
serverKey: /root/.acme.sh/ipc.example.de_ecc/ipc.example.de.key
# path to the server certificate. This is needed only when encryption is "strict" or "optional".
serverCert: /root/.acme.sh/ipc.example.de_ecc/fullchain.cer
# authentication methods.
authMethods: [basic, digest]

###############################################
# RTMP parameters

# disable support for the RTMP protocol.
rtmpDisable: no
# address of the RTMP listener.
rtmpAddress: :1935

###############################################
# HLS parameters

# disable support for the HLS protocol.
hlsDisable: no
# address of the HLS listener.
hlsAddress: :8888
# by default, HLS is generated only when requested by a user;
# this option allows to generate it always, avoiding an initial delay.
hlsAlwaysRemux: no
# number of HLS segments to generate.
# increasing segments allows more buffering,
# decreasing segments decreases latency.
hlsSegmentCount: 3
# minimum duration of each segment.
# the final segment duration is also influenced by the interval between IDR frames,
# since the server changes the segment duration to include at least a IDR frame in each one.
hlsSegmentDuration: 1s
# value of the Access-Control-Allow-Origin header provided in every HTTP response.
# This allows to play the HLS stream from an external website.
hlsAllowOrigin: '*'

###############################################
# Path parameters

# these settings are path-dependent.
# it's possible to use regular expressions by using a tilde as prefix.
# for example, "~^(test1|test2)$" will match both "test1" and "test2".
# for example, "~^prefix" will match all paths that start with "prefix".
# the settings under the path "all" are applied to all paths that do not match
# another entry.
paths:
  haustuer:
    source: rtsp://172.26.1.5:554/s1
    readUser: example
    readPass: example
  hof1:
    source: rtsp://172.26.1.3:554/s1
    readUser: example
    readPass: example
  hof2:
    source: rtsp://172.26.1.2:554/s1
    readUser: example
    readPass: example
  strasse:
    source: rtsp://172.26.1.6:554/s1
    readUser: example
    readPass: example
  garten1:
    source: rtsp://172.26.1.1:554/s1
    readUser: example
    readPass: example
  garten2:
    source: rtsp://172.26.1.7:554/s1
    readUser: example
    readPass: example
  garten3:
    source: rtsp://michael:example@172.26.1.9:554/Streaming/Channels/102
    readUser: example
    readPass: example
  vorgarten:
    source: rtsp://172.26.1.8:554/s1
    readUser: example
    readPass: example
  nebeneingang:
    source: rtsp://172.26.3.2:554/h264_stream
    readUser: example
    readPass: example
  eingang:
    source: rtsp://172.26.3.1:554/h264_stream
    readUser: example
    readPass: example
  vogelkaefig:
    source: rtsp://michael:example@172.26.1.10:554/Streaming/Channels/102
    readUser: example
    readPass: example

EOF
```

```
docker run --rm -it --name=MediaMTX --network=host -v /opt/mediamtx/mediamtx.yml:/mediamtx.yml -v /root/.acme.sh/:/root/.acme.sh/ bluenviron/mediamtx:0.23.6
```

Since the error is very specific ("file not found") make sure that the certificate folder exists and the certificate exists.

If you want to check which files are available in the container, you can build a custom image that includes both the server and linux utilities:

```
docker build -t temp - << EOF
FROM bluenviron/mediamtx:0.23.6 AS server
FROM alpine:3.18
COPY --from=server /mediamtx /mediamtx.yml /
CMD [ "/mediamtx" ]
EOF
```

You can use it to start the server:

```
docker run --rm -it --name=MediaMTX --network=host -v /opt/mediamtx/mediamtx.yml:/mediamtx.yml -v /root/.acme.sh/:/root/.acme.sh/ temp
```

or check for available files:

```
docker run --rm -it --name=MediaMTX --network=host -v /opt/mediamtx/mediamtx.yml:/mediamtx.yml -v /root/.acme.sh/:/root/.acme.sh/ temp ls -lR /root/.acme.sh
```
