### ISSUE TITLE
Prefix logs with path

### ISSUE THREAD

**Issue by RobertoUa** [bluenviron/mediamtx#2034]
## Describe the feature

Description

For `runOnReady` add an option to prefix each log line with path.
I need to implement some log parsing for FFmpeg logs but there's no way to know which path ffmpeg is processing if multiple are running concurrently. And it's not just for log parsing. Debugging will be easier.
For instance with config
```
paths:
  ondemand:
    runOnDemand: ffmpeg -re -stream_loop -1 -i file.ts -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnDemandRestart: yes
```
I want to see something like this
`[ondemand] frame=  238 fps= 36 q=22.0 size=N/A time=00:00:08.01 bitrate=N/A speed=1.21x`
