### ISSUE TITLE
maxReaders

### ISSUE THREAD

**Issue by pikachu937** [bluenviron/mediamtx#2180]
## Which version are you using?

v1.0.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] Other (LXC)

## Describe the issue

Crashes with an error when starting the server

## Describe how to replicate the issue

1. start the server
2. view in console message "ERR: json: unknown field "maxReaders""

## Did you attach the server logs?

yes / **no**

## Did you attach a network dump?

yes / **no**

**Comment by aler9** [comment]
? check that your configuration follows the template. In particular, maxReaders has to be placed under `path`

**Comment by aler9** [comment]
i replied here: https://github.com/bluenviron/mediamtx/issues/2181#issuecomment-1669645692

**Comment by pikachu937** [comment]
my paths
```
  path1:
    source: rtsp://192.168.0.10:8554/path1
    sourceProtocol: tcp
    maxReaders: 0

  path2:
    source: rtsp://192.168.0.10:8554/path2
    sourceProtocol: tcp
    maxReaders: 0

```
