### ISSUE TITLE
No autofocus with rpiCamera source and rpiCameraAfMode: auto

### ISSUE THREAD

**Issue by Ataman** [bluenviron/mediamtx#2326]
## Which version are you using?

v1.0.3

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [x] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Autofocus mode ```auto``` with `rpiCamera` source doesn't seem to work i.e.: setting `rpiCameraAfMode` to `auto` doesn't achieve focus. I'm using a Raspberry Camera Module 3 connected to a RPi Zero W. Setting `rpiCameraAfWindow` to something like `0.25,0.25,0.5,0.5` didn't change anything. Using manual focus and setting the lens position works however and so does the ```continuous``` setting.
Server logs don't show anything suspicious.
Versions: 
OS: `Raspbian GNU/Linux 11 (bullseye)`
libcamera: `v0.0.5+83-bde9b04f`
libfreetype6: `2.10.4+dfsg-1+deb11u1`

## Describe how to replicate the issue

1. Start server with the following configs:

```yaml
logLevel: debug
logDestinations: [syslog]
rtsp: yes
protocols: [tcp]
rtspAddress: :554
rtmp: no
hls: no
webrtc: no
srt: no

paths:
  live:
    source: rpiCamera
    rpiCameraCamID: 0
    rpiCameraWidth: 1280
    rpiCameraHeight: 720
    rpiCameraHFlip: False
    rpiCameraVFlip: False
    rpiCameraBrightness: 0.0
    rpiCameraContrast: 1
    rpiCameraSaturation: 1
    rpiCameraSharpness: 0
    rpiCameraExposure: auto
    rpiCameraAWB: auto
    rpiCameraDenoise: "cdn_off"
    rpiCameraShutter: 0
    rpiCameraMetering: centre
    rpiCameraGain: 0
    rpiCameraEV: 0
    rpiCameraHDR: false
    rpiCameraFPS: 30
    rpiCameraIDRPeriod: 60
    rpiCameraBitrate: 2000000
    rpiCameraProfile: main
    rpiCameraLevel: '4.1'
    rpiCameraAfMode: auto
    rpiCameraAfRange: normal
    rpiCameraAfSpeed: normal
    rpiCameraLensPosition: 0
```

2. Connect with VLC to `rtsp://<SERVER_IP>:554/live`

## Did you attach the server logs?

no

## Did you attach a network dump?

no
