### ISSUE TITLE
native recording 

### ISSUE THREAD

**Issue by pikachu937** [bluenviron/mediamtx#2358]
## Describe the feature

Hello. I think that I will express my general gratitude to you for implementing the stream recording function, but I would like to ask you to expand the functionality.

**Add record options**
- [ ] recordFormat - mpegts
- [ ] disable audio track recording
- [ ] balance recording between drives

```yaml
    # record format: mpegts, fmp4
    recordFormat: mpegts
    # enable or disable audio track
    disableaudio: false
    # list mount point 
    drivers: /mnt/rec1, /mnt/rec2…/mnt/recN
```
