### ISSUE TITLE
Native recording is controlled through API

### ISSUE THREAD

**Issue by klk2** [bluenviron/mediamtx#2364]
## Describe the feature

[2255 ](https://github.com/bluenviron/mediamtx/pull/2255)
[record commit](73ddb21e63fc908d191d57378d0759d68f044427)

Thanks Mediamtx team for their work and efforts！

The current recording implementation is global recording and cannot control the recording of a single path.
In some businesses, the browser client may control recording.
Is it possible to control the recording of a single path through the API?

**Comment by klk2** [comment]
The current recording does not support recording of external rtmp/rtsp service streams

**Comment by pikachu937** [comment]
> ## Describe the feature
> [2255 ](https://github.com/bluenviron/mediamtx/pull/2255) [record commit](73ddb21e63fc908d191d57378d0759d68f044427)
> 
> Thanks Mediamtx team for their work and efforts！
> 
> The current recording implementation is global recording and cannot control the recording of a single path. In some businesses, the browser client may control recording. Is it possible to control the recording of a single path through the API?

Hello. if your path is higher than the global(***all***)path, then you can set the record value equal to no for your specific path, in which case no recording will be made on your specific path. For example:

```yaml
# Record streams to disk.
record: yes
# Path of recording segments.
# Extension is added automatically.
# Available variables are %path (path name), %Y %m %d %H %M %S %f (time in strftime format)
recordPath: ./recordings/%path/%Y-%m-%d_%H-%M-%S-%f
# Format of recorded segments.
# Currently the only available format is fmp4 (fragmented MP4).
recordFormat: fmp4
# fMP4 files are concatenation of small MP4 files (parts), each with this duration.
# When a system failure occurs, the last part gets lost.
# Therefore, the part duration is equal to the RPO (recovery point objective).
recordPartDuration: 100ms
# Minimum duration of each segment.
recordSegmentDuration: 1h
# Delete segments after this timespan.
# Set to 0s to disable automatic deletion.
recordDeleteAfter: 24h

paths:
  test1:
    source: rtsp://url/path
    record: no
  all:
    source: publisher
    record: yes
```
