### ISSUE TITLE
Feature request: Support recording to FTP / SFTP remote storage

### ISSUE THREAD

**Issue by Sunvas** [bluenviron/mediamtx#2404]
## Describe the feature

It should be possible to store recording on remote storages via FTP / SFTP. In combinations with storage for back ups service, available in most hosting companies, it would be possible to store recordings in a reliable place.

**Comment by aler9** [comment]
Hello, i thought a little about this feature, in my opinion the best way to upload recordings to remote locations with FTP, S3, SFTP, SMB and a lot more is to allow [rclone](https://rclone.org/) to work together with the server.

In #2428 added a hook called `runOnRecordSegmentDone`, that allows to run commands when a recording segment is ready, and i also added instructions on how to use it with rclone.

**Comment by Sunvas** [comment]
_rclone_  is a little not what I need, because it is used to upload stored locally recordings. I'm using mediamtx on the router running OpenWRT where there is not much free space. So I need a solution for direct upload recordings without storing them locally.

**Comment by aler9** [comment]
Recording directly to the cloud is generally not possible since a significant portion of remote storage solutions, like S3, don't allow to write continuously to the cloud but only support uploading complete files, and that's why they are called object storage systems. The same can be said for FTP and FTPS, even though these allow overriding remote files.
The only kind of remote storage that supports continuous writing is block storage (NFS / SMB), but it's not a good idea to use them with a bandwidth-intensive application like video streaming, due to network fluctuations. It's also a bad idea because such system would not be tolerant to disconnections.

You have to store files locally, upload and delete them. In this way, the system is robust against disconnections, since recording still takes place, and segments are uploaded as soon as the connection is restored.

If you still want to pursue the block storage solution, you can mount nfs / smb on a local directory and use that as a destination for recordings.

**Comment by pikachu937** [comment]
Hello. This improvement can only be used for rclone or can you run an sql query to add file metadata to the database or move the completed file to another directory (drive, ftp/s3 directory) or something else?

**Comment by aler9** [comment]
> Hello. This improvement can only be used for rclone or can you run an sql query to add file metadata to the database or move the completed file to another directory (drive, ftp/s3 directory) or something else?

Since it's a hook that is run after a segment is complete, you can use it for everything.

**Comment by Sunvas** [comment]
@aler9 
> You have to store files locally, upload and delete them
How to delete files after rsync finished its work?

**Comment by aler9** [comment]
> How to delete files after rsync finished its work?

If you mean rclone, replace `rclone sync` with `rclone move`:

```yml
   record: yes

   paths:
     mypath:
       # this is needed to sync segments after a crash.
       # replace myconfig with the name of the rclone config.
       runOnInit: rclone -v move ./recordings myconfig:/my-path/recordings

       # this is called when a segment has been finalized.
       # replace myconfig with the name of the rclone config.
       runOnRecordSegmentComplete: rclone -v --min-age=1ms move ./recordings myconfig:/my-path/recordings
```
