### ISSUE TITLE
Stream Thumbnail via WebRequest

### ISSUE THREAD

**Issue by itsyoshio** [bluenviron/mediamtx#2427]
## Describe the feature

I'm running mediamtx on a pi zero, with an arducam attached (rpicamera.go is used).
What i'd really like is to get the rtsp stream simultaneously to a sporadic image.

ideally, for my stream `localhost:8554/cam` i'd like to make a webrequest to something along the lines of `localhost:8554/thumbnails/cam` to see a recent snapshot of the stream (from the last 60s, 30s, or 10s).

i've tried https://github.com/bluenviron/mediamtx/issues/119 but that doesn't since Publish is not used (rpicamera) and the preview should always be relatively recent whenever mediamtx is running.

**Comment by aler9** [comment]
Hello, replace `runOnPublish` with `runOnReady` and wrap ffmpeg inside a loop:

```yml
paths:
  rpicamera:
    source: rpicamera
    runOnReady: sh -c 'while true; do ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -vframes 1 -y thumbnail.jpg; sleep 10; done'
    runOnReadyRestart: yes
```

This has to be done through external hooks since the server doesn't decode the video for performance and legal reasons.
