### ISSUE TITLE
RaspberryPI zero 2 W Raspbian 64bit error symbol lookup and wrong libcamera references

### ISSUE THREAD

**Issue by kanehekili** [bluenviron/mediamtx#2442]
## Which version are you using?

MediaMTX v1.1.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Using Pi 2w zero with RPICamera Model 3. 
RTMP via libcamera-vid & ffmpeg works against Youtube.

config (path section)
```
paths:
   cam: 
     source: rpiCamera

    # ID of the camera
     rpiCameraCamID: 0
    # width of frames
     rpiCameraWidth: 1920
    # height of frames
     rpiCameraHeight: 1080
    # flip horizontally
     rpiCameraHFlip: false
    # flip vertically
     rpiCameraVFlip: false

```
When starting the first time, it did not find the libcamera modules. Could be fixed with linking both libcamera.so.0.0 and libcamera-base.so to the correct versions (currently 0.0.4)

After linking the camera seemed to be found, then:
```
[1:12:12.966755669] [1145]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
[1:12:13.127106954] [1149]  INFO RPI raspberrypi.cpp:1476 Registered camera /base/soc/i2c0mux/i2c@1/imx708@1a to Unicam device /dev/media3 and ISP device /dev/media1
/dev/shm/rtspss-embeddedexe-1696100886793147684: symbol lookup error: /dev/shm/rtspss-embeddedexe-1696100886793147684: undefined symbol: _ZN9libcamera6Camera21generateConfigurationENS_4SpanIKNS_10StreamRoleELm18446744073709551615EEE
2023/09/30 21:08:07 ERR [path cam] [RPI Camera source] process exited unexpectedly
```

Furthermore all other rpiCamera entries not included in the above description were not accepted (e.g. rpiCameraBrightness). Message:
`ERR: yaml: line 306: did not find expected key`

## Describe how to replicate the issue
After fixing the library names and changed the config file this can be reproduced by simply calling the executable
(I have worked as root)
`:/mediamtx`

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

yes 

## Did you attach a network dump?

 not the problem (yet) - didn't come that far....
