### ISSUE TITLE
Some recordings have wrong duration

### ISSUE THREAD

**Issue by 0ip** [bluenviron/mediamtx#2477]
## Which version are you using?

v1.1.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Some recordings of my security camera have a wrong or absurdly high length duration instead of the actually set 10 seconds. While this problem doesn't show up in VLC (duration is said to be 10 s) and the videos play fine there, ffmpeg and chrome report the wrong durations:

ffprobe of a video that is affected by this bug:
![image](https://github.com/bluenviron/mediamtx/assets/757230/70c91c06-f88b-40d9-861e-4c6bf2253afe)

ffprobe of a normal video:
![image](https://github.com/bluenviron/mediamtx/assets/757230/a82f3764-1a15-4154-9e1d-0410ade6b379)

relevant config parts:
```
record: yes
recordPath: /dev/shm/recordings/%path/%Y-%m-%d_%H-%M-%S-%f
recordFormat: fmp4
recordPartDuration: 100ms
recordSegmentDuration: 10s
recordDeleteAfter: 4m
...
writeQueueSize: 1024

rtspAddress: :8554
protocols: [tcp]
...
paths:
  64/high:
    source: rtsp://x:y@192.168.1.64:554/Streaming/Channels/101
    sourceOnDemand: no
    sourceProtocol: tcp
    record: yes
```

I can forward you the files via email if desired.

## Describe how to replicate the issue

1. start the server
2. publish rtsp stream
3. record
4. some recordings have a wrong duration, some are normal as expected

## Did you attach the server logs?

no

## Did you attach a network dump?

no
