### ISSUE TITLE
HTTP MPEG-TS & SRT custom port caller and custom port Play

### ISSUE THREAD

**Issue by cmigb** [bluenviron/mediamtx#2509]
## HTTP MPEG-TS & SRT custom port caller and custom port Play

I appreciate the recent updates. I have a couple of feature requests in mind:

1. **HTTP MPEG-TS Playback:** It would be fantastic if you could introduce the capability to play HTTP MPEG-TS streams. This feature would enhance the versatility of the system.
http://localhost/streamname.ts or something (hope mpeg2 supported)

2. **SRT Publishing Without Stream Name:** It would be convenient if we could publish SRT streams without specifying a stream name, just by using the format `srt://ip:port`. Additionally, it would be great if we could define custom ports for SRT playback, for example, `srt://ip:custom_port`. These enhancements would make working with SRT more flexible.
To add a section for predefined SRT streams with custom ports for publishing and playing in a `mediamtx.yaml` configuration file, you can modify the YAML file as follows:

```yaml
# Existing configuration ...

srt_streams:
  - name: "SRT Channel 1"
    publish_url: "srt://localhost:2001"
    play_url: "srt://localhost:3001"

  - name: "SRT Channel 2"
    publish_url: "srt://localhost:2002"
    play_url: "srt://localhost:3002"

# Existing configuration ...
```

In this configuration:

- We've added a `srt_streams` section, which is a list of predefined SRT streams.
- Each stream is defined with a `name` (a descriptive name for the stream), `publish_url` (the SRT URL for publishing), and `play_url` (the SRT URL for playing).

Thank you for considering these suggestions!
