### ISSUE TITLE
Problems configuring two webcams

### ISSUE THREAD

**Issue by mwolfeu** [bluenviron/mediamtx#2565]
## Which version are you using?

v1.2.0

## Which operating system are you using?
Raspbian Bullseye 11

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ x] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I can't configure two webcams.  

Description

Using the stock config except I've modified the bottom of my config like this:
```
paths:
  video2:
    source: publisher
    runOnInit: ffmpeg -pix_fmt yuv420p -i /dev/video2 -s:v 320x240 -r 5 -c:v h264 -preset ultrafast -tune zerolatency -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
  video0:
    source: publisher
    runOnInit: ffmpeg -pix_fmt yuv420p -i /dev/video0 -s:v 320x240 -r 5 -c:v h264 -preset ultrafast -tune zerolatency -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
  # Settings under path "all_others" are applied to all paths that
  # do not match another entry.
  all_others:
```
Running a ps, I see both ffmpegs running.
Going to video0 works. 
Going to video2 never even starts the spinner. (see output)

## Did you attach the server logs?

yes 

## Did you attach a network dump?

 no
