### ISSUE TITLE
WebRTC on domain

### ISSUE THREAD

**Issue by radimkohout** [bluenviron/mediamtx#2578]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [x] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
I think, that it is probably bug, so transfering it from discussions to here.

### Discussed in https://github.com/bluenviron/mediamtx/discussions/2527

<div type='discussions-op-text'>

<sup>Originally posted by **radimkohout** October 19, 2023</sup>
### Question

Hi,
I am running mediamtx (native arm64 version) and trying to connect to WebRTC behind NAT. When I do it locally, everything works, but when I try it remotly using domain name, it only blinks black. When I try it using public IP address, everything works, except I can't use SSL certificate. How can I get it to work using domain name? I router, I am routing ports 8189 and 8889 both tcp and udp to the device. 

```
webrtcICEHostNAT1To1IPs: [93.x.x.x]
# any port of choice
webrtcICEUDPMuxAddress: :8189
webrtcICETCPMuxAddress: :8189

webrtcICEServers2:
- url: turn:a.relay.metered.ca:80
  username: <ommited>
  password: <ommited>

```
</div>

## Describe how to replicate the issue

1. Use the configuration from desciption
2. Try to access using IP, works
3. Try to access using domain, doesn't work.

## Did you attach the server logs?
no, nothing interresting here.

## Did you attach a network dump?
no
