### ISSUE TITLE
Incompatibility with libcamera 0.1.0 and Raspberry Pi 5

### ISSUE THREAD

**Issue by neutralvibes** [bluenviron/mediamtx#2581]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [x] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description
 mediamtx fails to work after `apt-get upgrade`

Libcamera: v0.1.0+52-a858d20b

## Describe how to replicate the issue

sudo apt-get update && sudo apt-get upgrade-y

## Did you attach the server logs?

~~~
/dev/shm/rtspss-embeddedexe-1698423452247192666: error while loading shared libraries: libcamera.so.0.0: cannot open shared object file: No such file or directory
~~~

yes 

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, the server is compatible with only a version of libcamera at the time, and the current compatible version is 0.0.5.

It seems like Raspberry Pi maintainers are starting to unroll 0.1.0 on some OS-hardware combinations, but not on everyone.

Anyway, the majority of OSs currently runs 0.0.5, so we can't perform the upgrade right now, but i'll keep this issue open in order to track the situation.

**Comment by neutralvibes** [comment]
I reported a bump in version a while ago that you thankfully were able to resolve quickly. I cannot remember how I previously got the version. Just in case I have somehow provided an incorrect version this time I thought I should provide info on how it was obtained.

~~~
$libcamera-hello --version
libcamera-apps build: 7e4d3d71867f 22-08-2023 (10:57:38)
libcamera build: v0.1.0+52-a858d20b
~~~

Thanks for your help.

**Comment by aler9** [comment]
We could quickly solve this issue too, but the problem is that i just checked the latest libcamera version on my Raspberry Pi, and it's still 0.0.5, so a full switch to 0.1.0 would cause problems to most users.

**Comment by neutralvibes** [comment]
I will use docker in meantime.

**Comment by Topper69** [comment]
Hi,
Raspbian OS has pushed libcamera 0.1.0+99-4a23664b version which brake the compatibility.

Extract of error logs : 
```Nov 07 21:23:08 baby mediamtx[6996]: [0:04:27.916109998] [6996]  INFO Camera camera_manager.cpp:284 libcamera v0.1.0+99-4a23664b
Nov 07 21:23:08 baby mediamtx[6996]: [0:04:27.972403420] [6998]  WARN RPiSdn sdn.cpp:39 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
Nov 07 21:23:08 baby mediamtx[6996]: [0:04:27.978540965] [6998]  INFO RPI vc4.cpp:444 Registered camera /base/soc/i2c0mux/i2c@1/ov5647@36 to Unicam device /dev/media0 and ISP device /dev/media1
Nov 07 21:23:08 baby mediamtx[6996]: [0:04:27.980189092] [6996] ERROR RPI pipeline_base.cpp:166 Invalid sensor configuration request
Nov 07 21:23:08 baby mediamtx[6996]: [0:04:27.981955922] [6998] ERROR Camera camera.cpp:585 Removing camera while still in use
Nov 07 21:23:08 baby mediamtx[459]: 2023/11/07 21:23:08 ERR [path cam] [RPI Camera source] camera_create(): StreamConfiguration.validate() failed```

**Comment by aler9** [comment]
Unfortunately libcamera version is still 0.0.5 on Raspberry Bullseye. If you need a server version that is compatible with libcamera 0.1.0, compile it from source by following instructions in the README, or use the Dockerized version, which is independent from libcamera.

**Comment by Topper69** [comment]
I have fix the issue with the following code in camera.cpp line 192:

```
conf->transform = Transform::Identity;
if (params->h_flip) {
    conf->transform = Transform::HFlip; 
}
if (params->v_flip) {
    conf->transform = Transform::VFlip;
}
if  (params->v_flip && params->h_flip) {
     conf->transform = Transform::Rot180Transpose;
}
```

**Comment by neutralvibes** [comment]
Bookworm is the latest Raspberry distro. That may explain the issue.

**Comment by kanehekili** [comment]
In 1.2.1 I had to create library links in bookworm to get it running:
`/lib/aarch64-linux-gnu # :
   ln -s libcamera.so.0.1 libcamera.so.0.0
   ln -s libcamera-base.so.0.1 libcamera-base.so.0.0`

**Comment by lolorc** [comment]
new libcamera changes related to transform pushed to bookworm ;-)

**Comment by suosuo6** [comment]
raspberry  pi5 bookworm docker docker run --rm -it --network=host --privileged --tmpfs /dev/shm:exec -v /run/udev:/run/udev:ro -e MTX_PATHS_CAM_SOURCE=rpiCamera bluenviron/mediamtx:latest-rpi
2023/11/28 13:39:58 INF MediaMTX v1.3.1
2023/11/28 13:39:58 INF configuration loaded from /mediamtx.yml
2023/11/28 13:39:58 INF [path cam] [RPI Camera source] started
2023/11/28 13:39:58 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/11/28 13:39:58 INF [RTMP] listener opened on :1935
2023/11/28 13:39:58 INF [HLS] listener opened on :8888
2023/11/28 13:39:58 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
2023/11/28 13:39:58 INF [SRT] listener opened on :8890 (UDP)
[0:32:34.424405642] [13]  INFO Camera camera_manager.cpp:297 libcamera v0.0.5+83-bde9b04f
2023/11/28 13:39:59 ERR [path cam] [RPI Camera source] camera_create(): selected camera is not available
[0:32:39.569273539] [19]  INFO Camera camera_manager.cpp:297 libcamera v0.0.5+83-bde9b04f
2023/11/28 13:40:04 ERR [path cam] [RPI Camera source] camera_create(): selected camera is not available

**Comment by masipcat** [comment]
Now I was trying something like this:

```yaml
paths:
  # example:
  cam:
    runOnInit: bash -c 'libcamera-vid -t 0 --codec yuv420 --width 1280 --height 720 --inline --listen -o - | ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 1280x720 -i /dev/stdin -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH'
    runOnInitRestart: yes
```

It works, but I observe 2-3 seconds delay and frequent freezes... Do you think switching to GStreamer would improve performance?

**Comment by Topper69** [comment]
> Now I was trying something like this:
> 
> ```yaml
> paths:
>   # example:
>   cam:
>     runOnInit: bash -c 'libcamera-vid -t 0 --codec yuv420 --width 1280 --height 720 --inline --listen -o - | ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 1280x720 -i /dev/stdin -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH'
>     runOnInitRestart: yes
> ```
> 
> It works, but I observe 2-3 seconds delay and frequent freezes... Do you think switching to GStreamer would improve performance?
> 
> EDIT:
> 
> I tried using gstreamer and it's worse than using ffmpeg. Maybe I'm configuring something wrong?
> 
> ```yaml
>     runOnInit: gst-launch-1.0 -v libcamerasrc ! "video/x-raw,width=1280,height=720,framerate=2/1" ! videoconvert ! x264enc speed-preset=ultrafast tune=zerolatency byte-stream=true bitrate=3000 threads=2 ! rtspclientsink location=rtsp://localhost:$RTSP_PORT/$MTX_PATH
> ```

Worse for the delay ?

**Comment by masipcat** [comment]
> Worse for the delay ?

Yes, for the delay and freezes

**Comment by aler9** [comment]
>  the Raspberry Pi 5 does not have a hardware video encoder

Thanks for reporting this news since it changes a lot of things. Performing a linear bump of libcamera is not enough anymore and a little reasoning is needed before improving the server in order to deal with the issue.

There are two separate problems, a technical one and a legal one.

The technical problem can be solved by embedding a software encoder into the server and using it as failback. Raspberry Pi employees wrote that they recommend performing software encoding on the new Pi, even though it consumes at least an entire core. Let's do like they say, even though it sounds particularly inadequate in the era of 8k videos.

Unfortunately embedding an H264 software encoder has legal implications, since H264 is covered by patents. Hardware encoders don't have this problem since the legal responsibility is on the hardware manufacturers, and that is why, for instance, Chrome supports H265 decoding if and only if there's an available hardware decoder, and the same applies to MediaMTX in case of H264 encoding.

My idea is to change the video codec of the RPI camera from H264 to AV1, which is royalty free, and embed an AV1 software encoder into the server. AV1 is supported by most browsers and by a relevant fraction of mobile devices, although the compatibility level is not the same as the one of H264. I can't imagine any other way.

**Comment by Tdougherty350** [comment]
> > the Raspberry Pi 5 does not have a hardware video encoder
> 
> Thanks for reporting this news since it changes a lot of things. Performing a linear bump of libcamera is not enough anymore and a little reasoning is needed before improving the server in order to deal with the issue.
> 
> There are two separate problems, a technical one and a legal one.
> 
> The technical problem can be solved by embedding a software encoder into the server and using it as failback. Raspberry Pi employees wrote that they recommend performing software encoding on the new Pi, even though it consumes at least an entire core. Let's do like they say, even though it sounds particularly inadequate in the era of 8k videos.
> 
> Unfortunately embedding an H264 software encoder has legal implications, since H264 is covered by patents. Hardware encoders don't have this problem since the legal responsibility is on the hardware manufacturers, and that is why, for instance, Chrome supports H265 decoding if and only if there's an available hardware decoder, and the same applies to MediaMTX in case of H264 encoding.
> 
> My idea is to change the video codec of the RPI camera from H264 to AV1, which is royalty free, and embed an AV1 software encoder into the server. AV1 is supported by most browsers and by a relevant fraction of mobile devices, although the compatibility level is not the same as the one of H264. I can't imagine any other way.

Hello, Just my two sense. With the Lite version of Bookworm, the video encoders are not included. You either have to use the full desktop version of rasbian bookworm, or compile rpicam-aps to get the h264 encoders. Reference: https://forums.raspberrypi.com/viewtopic.php?t=361268

**Comment by IgorWolkov** [comment]
@masipcat, I tried your solution 

```
paths:
  # example:
  cam:
    runOnInit: bash -c 'libcamera-vid -t 0 --codec yuv420 --width 1280 --height 720 --inline --listen -o - | ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 1280x720 -i /dev/stdin -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH'
    runOnInitRestart: yes
```    
and it works for my Raspberry Pi 5 (Raspberry Pi OS (64-bit)). It takes up to 5 seconds to start the stream, then it streams with a subsecond delay to my laptop over wifi. It even works for two cameras.

My script with tiny improvements:
 ```
paths:
  cam1:
    runOnInit: bash -c 'rpicam-vid -t 0 --camera 0 --nopreview --codec yuv420 --width 1280 --height 720 --inline --listen -o - | ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 1280x720 -i /dev/stdin -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH'
    runOnInitRestart: yes
  cam2:
    runOnInit: bash -c 'rpicam-vid -t 0 --camera 1 --nopreview --codec yuv420 --width 1280 --height 720 --inline --listen -o - | ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 1280x720 -i /dev/stdin -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH'
    runOnInitRestart: yes
```
