### ISSUE TITLE
[WebRTC] WHEPS sourceFingerprint not working

### ISSUE THREAD

**Issue by tbnguyen1407** [bluenviron/mediamtx#2618]
## Which version are you using?

v0.2.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

sourceFingerprint is not used to validate the cert when ingesting with WHEPS, throwing error:

```
tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Ingesting using other encrypted protocols, e.g RTSPS, is working as intended.

## Describe how to replicate the issue

Replicate by ingesting WHEP output of mediamtx in another path.

```
~ mediamtx.yml ~
## rtsps
protocols: [tcp]
encryption: "optional"
serverKey: key.pem
serverCert: cert.pem

## webrtc
webrtcEncryption: yes
webrtcServerKey: key.pem
webrtcServerCert: cert.pem

paths:
  path1:
    source: "rtsp://x.x.x.x:554/"
  ## proxy path1 using rtsps - working
  path2:
    source: "rtsps://127.0.0.1:8322/path1"
    sourceFingerprint: "41A231120E5DFD75A333EED014B7A79F2E216BC53288FF102EB8FC5CD527E9E1"
  ## proxy path1 using webrtc - not working
  path3:
    source: "wheps://127.0.0.1:8889/path1/whep"
    sourceFingerprint: "41A231120E5DFD75A333EED014B7A79F2E216BC53288FF102EB8FC5CD527E9E1"

```

1. start the server
2. see logs for error

## Did you attach the server logs?

no

## Did you attach a network dump?

no
