### ISSUE TITLE
WebRTC does not work when container in TCP mode

### ISSUE THREAD

**Issue by huntson** [bluenviron/mediamtx#2625]
## Which version are you using?

v1.2.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I am using a lot of the default config settings other than passing the argument to run the entire thing in TCP mode via compose. Inside the YAML I have also setup a RTSP stream to pull. I can use VLC to play back that stream however when the container is in TCP mode, I constantly get the following when attempting WebRTC sessions:

2023/11/02 01:09:17 INF [WebRTC] [session bb07928b] created by 10.96.50.17:21971

2023/11/02 01:09:27 INF [WebRTC] [session bb07928b] closed: deadline exceeded while waiting connection

## Describe how to replicate the issue

1. start the server in TCP mode:
```
`version: '3.3'
services:
    mediamtx:
        stdin_open: true
        tty: true
        environment:
            - MTX_PROTOCOLS=tcp
        ports:
            - '8554:8554'
            - '1935:1935'
            - '8888:8888'
            - '8889:8889'
            - '8890:8890/udp'
        volumes:
            - '/var/lib/docker/volumes/mediamtx/mediamtx.yml:/mediamtx.yml'
        restart: always

        image: bluenviron/mediamtx`
```

3. publish with rtsp
4. read with Webrtc

## Did you attach the server logs?

yes 

## Did you attach a network dump?

 no
