### ISSUE TITLE
Configuration options to serve external files for HLS/WebRTC playing, root path and aux files

### ISSUE THREAD

**Issue by rse** [bluenviron/mediamtx#2649]
## Describe the feature

MediaMTX currently has a built-in HTTP server and web pages for playing streams with HLS and WebRTC. Unfortunately, the code of the playing pages is directly built into the MediaMTX binary and cannot be changed. As a result, one has to put a (potentially latency introducing, but at least complexity introducing) reverse proxy in front of MediaMTX just to serve alternative playing code. Additionally, the root URL path ("/") on MediaMTX does not show anything reasonable.

It would be great if there would be six configuration options: for both the WebRTC and HLS services allow one to serve the URL paths "/", "/<stream>" and "/.internal/*" from an external file. The root path is for serving an overview page, the stream path is for playing the stream and the "/.internal/*" paths allow one to serve an own version of HLS.js, extra libs like Plyr.js, custom CSS files, etc.

So, I would enjoy to use for instance something like (based on a first-match semantic):

```yaml
hlsHTTPServe:
    - url: "/"
      file: /somewhere/index.html
    - url: "/.internal/"
      file: /somewhere/
    - url: "/*"
      file: /somewhere/player.html
webrtcHTTPServe:
    - url: "/"
      file: /somewhere/index.html
    - url: "/.internal/"
      file: /somewhere/
    - url: "/*"
      file: /somewhere/player.html
```
