### ISSUE TITLE
RTSP does not extract user and password when using external auth server

### ISSUE THREAD

**Issue by jonra1993** [bluenviron/mediamtx#2700]
## Which version are you using?

latest

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [x] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

RTSP does not extract user and password when using an external auth server. I have set up the external server and mediamtx does not send in the payload the user and passwords. I test with rtmp and it works.

This is how I am publishing streams

```
 ffmpeg -f avfoundation -video_size 640x480 -i "0" -c:v h264 -f rtsp -rtsp_transport tcp "rtsp://myuser:mypass@localhost:8554/mystream?user=myuser&pass=mypass"
```

This is what my auth server receives. user and Password are empty but I have included them in the URL both in. normal and also as query but it does not work.

## Describe how to replicate the issue

1. start the server in a container way and setup an external auth server

```
version: '3'
services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    ports:
      - "8554:8554"
      - "8002:8000"
      - "8001:8001"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
    environment:
      #- MTX_PROTOCOLS="udp, multicast, tcp"
      - MTX_API=yes      
```
2. publish with .
```
 ffmpeg -f avfoundation -video_size 640x480 -i "0" -c:v h264 -f rtsp -rtsp_transport tcp "rtsp://myuser:mypass@localhost:8554/mystream?user=myuser&pass=mypass"
```
4. print payload in auth server

## Did you attach the server logs?

yes / no

<img width="439" alt="image" src="https://github.com/bluenviron/mediamtx/assets/23468720/9b993771-a6c2-4a64-bcb0-25570f7f8551">
