### ISSUE TITLE
Error getting rtsp stream: [RTSP source] invalid SDP: sdp: invalid syntax `o=Channel1 3910280086 3910366486 IN IP4`

### ISSUE THREAD

**Issue by v1ct0rv** [bluenviron/mediamtx#2762]
## Which version are you using?

MediaMTX v1.3.1

## Which operating system are you using?
Linux, using docker image bluenviron/mediamtx:latest-ffmpeg

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [x] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

1. Create docker compose file:
``` yaml
services:
  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx:latest-ffmpeg
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - $PWD/mediamtx.yml:/mediamtx.yml
```
2. create mediamtx.yml:
``` yaml
# Enable the HTTP API.
api: yes
# Address of the API listener.
apiAddress: 0.0.0.0:9997

# Settings in "pathDefaults" are applied anywhere,
# unless they are overridden in "paths".
pathDefaults:
  ###############################################
  # Default path settings -> Authentication

  # Username required to publish.
  # SHA256-hashed values can be inserted with the "sha256:" prefix.
  publishUser:
  # Password required to publish.
  # SHA256-hashed values can be inserted with the "sha256:" prefix.
  # echo -n "userpass" | openssl dgst -binary -sha256 | openssl base64
  publishPass:
  # IPs or networks (x.x.x.x/24) allowed to publish.
  publishIPs: []

  # Username required to read.
  # SHA256-hashed values can be inserted with the "sha256:" prefix.
  readUser:
  # password required to read.
  # SHA256-hashed values can be inserted with the "sha256:" prefix.
  readPass:
  # IPs or networks (x.x.x.x/24) allowed to read.
  readIPs: []

###############################################
# Path settings

# Settings in "paths" are applied to specific paths, and the map key
# is the name of the path.
# Any setting in "pathDefaults" can be overridden here.
# It's possible to use regular expressions by using a tilde as prefix,
# for example "~^(test1|test2)$" will match both "test1" and "test2",
# for example "~^prefix" will match all paths that start with "prefix".
paths:
  vvs-local-simulator-1/ch00/1:
    # Path to the source stream.
    source: rtsp://Admin:11111111@192.168.81.150/ch00/1/live.3gp
    sourceOnDemand: yes
    sourceProtocol: tcp
  # Settings under path "all_others" are applied to all paths that
  # do not match another entry.
  all_others:

```
3. Start the server `docker compose -up`.
4. Try to get the video `http://localhost:8889/vvs-local-simulator-1/ch00/1/`

## Did you attach the server logs?

yes
[mediamtx.log](https://github.com/bluenviron/mediamtx/files/13505429/mediamtx.log)

## Did you attach a network dump?

yes
[network.zip](https://github.com/bluenviron/mediamtx/files/13505430/network.zip)
