### ISSUE TITLE
Hot reloading with docker compose does not work

### ISSUE THREAD

**Issue by v1ct0rv** [bluenviron/mediamtx#2803]
## Which version are you using?

v1.4.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I'm on ubuntu-22, this is my `docker-compose.yml`:
``` yaml
services:
  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx:latest-ffmpeg
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - $PWD/conf:/conf:ro
    command: /conf/mediamtx.yml
```

Hot reload is not working.

## Describe how to replicate the issue

1. start the server
2. add this to the config paths:
``` yaml
  ~^vvs-local-simulator-3/(.*): # all paths starting with vvs-simulator-3
    source: rtsp://xxx:yyy@192.168.81.150/$G1
    sourceOnDemand: yes
    sourceProtocol: tcp
```
4. try to play:  `ffplay -rtsp_transport tcp -i rtsp://localhost:8554/vvs-local-simulator-3/ch00/0/live.3gp`
5. Restart the server and the stream starts working.

## Did you attach the server logs?

yes

```
➜ docker compose up
[+] Running 1/0
 ✔ Container mediamtx  Created                                                                                                                    0.0s 
Attaching to mediamtx
mediamtx  | 2023/12/12 15:29:58 INF MediaMTX v1.4.0
mediamtx  | 2023/12/12 15:29:58 INF configuration loaded from /conf/mediamtx.yml
mediamtx  | 2023/12/12 15:29:58 DEB path manager created
mediamtx  | 2023/12/12 15:29:58 INF [RTSP] listener opened on :8554 (TCP)
mediamtx  | 2023/12/12 15:29:58 INF [RTSPS] listener opened on :8322 (TCP)
mediamtx  | 2023/12/12 15:29:58 INF [RTMP] listener opened on :1935
mediamtx  | 2023/12/12 15:29:58 INF [HLS] listener opened on :8888
mediamtx  | 2023/12/12 15:29:58 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
mediamtx  | 2023/12/12 15:29:58 INF [SRT] listener opened on :8890 (UDP)
mediamtx  | 2023/12/12 15:29:58 INF [API] listener opened on 0.0.0.0:9997
mediamtx  | 2023/12/12 15:32:18 INF [RTSP] [conn [::1]:59582] opened
mediamtx  | 2023/12/12 15:32:18 DEB [RTSP] [conn [::1]:59582] [c->s] OPTIONS rtsp://localhost:8554/vvs-local-simulator-3/ch00/0/live.3gp RTSP/1.0      
mediamtx  | CSeq: 1
mediamtx  | User-Agent: Lavf60.16.100
mediamtx  |
mediamtx  |
mediamtx  | 2023/12/12 15:32:18 DEB [RTSP] [conn [::1]:59582] [s->c] RTSP/1.0 200 OK
mediamtx  | CSeq: 1
mediamtx  | Public: DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, GET_PARAMETER, TEARDOWN
mediamtx  | Server: gortsplib
mediamtx  |
mediamtx  |
mediamtx  | 2023/12/12 15:32:18 DEB [RTSP] [conn [::1]:59582] [c->s] DESCRIBE rtsp://localhost:8554/vvs-local-simulator-3/ch00/0/live.3gp RTSP/1.0     
mediamtx  | Accept: application/sdp
mediamtx  | CSeq: 2
mediamtx  | User-Agent: Lavf60.16.100
mediamtx  |
mediamtx  |
mediamtx  | 2023/12/12 15:32:18 DEB [path vvs-local-simulator-3/ch00/0/live.3gp] created
mediamtx  | 2023/12/12 15:32:18 DEB [RTSP] [conn [::1]:59582] [s->c] RTSP/1.0 404 Not Found
mediamtx  | CSeq: 2
mediamtx  | Server: gortsplib
mediamtx  |
mediamtx  |
mediamtx  | 2023/12/12 15:32:18 DEB [path vvs-local-simulator-3/ch00/0/live.3gp] destroyed: not in use
mediamtx  | 2023/12/12 15:32:18 INF [RTSP] [conn [::1]:59582] closed: no one is publishing to path 'vvs-local-simulator-3/ch00/0/live.3gp'
```

## Did you attach a network dump?

no
