### ISSUE TITLE
Proxy RTSP stream to SRT?

### ISSUE THREAD

**Issue by RogerDavenport** [bluenviron/mediamtx#2854]
## Describe the feature

I would like to proxy a stream from an RTSP IP camera to SRT.

For example, I have a RTSP IP camera (hanwha.local), attached to an ARM linux board (camera001) published like so:
```
#[ YML on camera001 running mediamtx 1.4.1]
paths:
  client-stream:
    source: "rtsp://hanwha.local/camera"
    sourceOnDemand: yes

```
I would like to pull that stream on demand:
```
#[ YML on server running mediamtx 1.4.1, where I pull the WebRTC stream ]
paths:
  camera001:
    source: "srt://camera001.local:8890?streamid=read:client-stream&pkt_size=1316"
    sourceOnDemand: yes
```

Currently I get an empty stream when I attempt to do this from a WebRTC client, so I am thinking this is a new feature.

Architecture is roughly like so:
**[Hanwha_Camera]** -- RTSP --> **[ARM camera001]** -- SRT --> **[Server]** -- WebRTC --> **[Chrome Browser]**
