### ISSUE TITLE
Allow to specify runOnReady / runOnReadyRestart multiple times per path

### ISSUE THREAD

**Issue by Abdull** [bluenviron/mediamtx#3032]
## Describe the feature

In my mediamtx installation, I have set up a `paths:` path which includes a `runOnReady:` configuration.

That `runOnReady:` configuration uses ffmpeg to forward/relay the path's video stream to a remote HLS/RTMP endpoint.

Now I would like to add an additional `runOnReady:` configuration which forwards/relays to yet another HLS/RTMP endpoint.

Maybe this is already possible with mediamtx v1.5.1?

**Comment by Abdull** [comment]
# Workaround

Here is my current workaround. It isn't as efficient, as it delegates to a Bash script which, in the case any of the (two) ffmpeg HLS streams fails, will kill *both* ffmpeg HLS streams and start over again (via the `runOnReadyRestart: yes` setting):

## `mediamtx.yml` snippet
```yml
# ...

paths:
  # my setup: 192.168.0.60 is an IP camera serving an RTSP stream at rtsp://192.168.0.60/stream=0 .
  # that RTSP stream has an h265-encoded 2K video channel and a G.711 A-law audio channel.
  ipcamera:
    # runOnInit explanation:
    #   "ffmpeg":
    #     I use ffmpeg to convert the IP camera source RTSP stream to my liking,
    #     and also because the IP camera is even weaker than the mediamtx home server for multi stream access scenarios.
    #   "-loglevel warning":
    #     ffmpeg is too chatty on the default "info" loglevel, hence I lower the logging level to "warning". 
    #   "-i rtsp://192.168.0.60/stream=0"":
    #     on the local home server, I consume my IP camera's RTSP stream with mediamtx.
    #   "-c:v copy":
    #     copy the h.265 video channel as-is ...
    #   "-c:a libopus -b:a 32k":
    #     ... but convert the audio channel from G.711 A-law to libopus/Opus, as this is the audio codec compatible with most output formats,
    #     WebRTC being the exception (see tables in https://github.com/bluenviron/mediamtx/blob/main/README.md ).
    #   with this setup, the h.265/Opus stream will be available on rtsp://localhost:8554/ipcamera ( rtsp://localhost:$RTSP_PORT/$MTX_PATH ) .
    runOnInit: ffmpeg -loglevel warning -i rtsp://192.168.0.60/stream=0 -c:v copy -c:a libopus -b:a 32k -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
    #
    # runOnReady explanation:
    #   once mediamtx initialized the "ipcamera" stream as set up per "runOnInit : ...", execute "concurrent-youtube-streams.sh".
    #   using "runOnReadyRestart: yes", should "concurrent-youtube-streams.sh" exit for any reason, execute "concurrent-youtube-streams.sh" again, and so on.
    #   this goes on until mediamtx exits.
    runOnReady: /opt/mediamtx/scripts/concurrent-youtube-streams.sh
    runOnReadyRestart: yes

# ...
```

## `concurrent-youtube-streams.sh`
```bash
#!/bin/bash

# concurrent-youtube-streams
# via https://unix.stackexchange.com/a/336447/20230
# run streams in parallel/concurrently in the background with "... &",
# then use "wait -n" to block _this_ script until
# the first of these background-running processes exits

# stream1 explanation:
#   "-loglevel warning":
#     on the default "info" loglevel, ffmpeg will write out plenty of HLS logs per second. this is very chatty, hence the "warning" log level.
#   "-i rtsp://localhost:8554/ipcamera":
#     take as input the h.265/Opus stream as prepared by mediamtx.yml > path "ipcamera" > "runOnInit".
#     youtube live allows to ingest RTMP and HLS streams. As Youtube allows h.265 for HLS, and to not reduce video quality by reencoding,
#     and to also not waste additional CPU resources on my small home server, just copy the video h.265 channel with "-c:v copy".
#   "-tag:v hvc1":
#     without this, ffmpeg complains/warns about a missing FourCC in the generated HLS stream or something.
#   "-c:a aac":
#     for HLS, youtube only accepts AAC or MP3. Youtube Live HLS silently fails when providing libopus/Opus as set from my source RTSP stream.
#     hence  reencode audio to the compatible aac.
#   " ... &":
#   the "&" at the end executes the ffmpeg command in the background, making the script continue.
#   p1="$!" keeps track of this first ffmpeg's background job PID for later use.
#   see https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html#index-_0021-1
 
echo "relaying stream with audio (youtube stream key: ...-abcd) ..."
ffmpeg -loglevel warning -i rtsp://localhost:8554/ipcamera \
-c:v copy -tag:v hvc1 -c:a aac -f hls -method POST -hls_time 1 -hls_playlist_type event -http_persistent 1 \
'https://a.upload.youtube.com/http_upload_hls?cid=abcd-abcd-abcd-abcd-abcd&copy=0&file=stream.m3u8' &

p1="$!"
echo "unlisted stream with audio has PID=${p1}"
echo "-----"

# stream2 explanation:
#   "-f lavfi -i anullsrc ... -c:a aac -map 0:a -map 1:v -shortest":
#     this second stream shall serve the same video material, but no audible audio. as youtube requires at least one audio channel,
#     this setup creates a new HLS mux with the original h.265 video channel, and a new silent/dummy AAC audio channel.
#     i'm not sure if "-shortest" is required at all, but it doesn't hurt.
#   " ... &":
#   the "&" at the end executes the ffmpeg command in the background, making the script continue.
#   p2="$!" keeps track of this second ffmpeg's background job PID for later use.
#   see https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html#index-_0021-1

echo "relaying stream without audio (silence) (...-wxyz) ..."
ffmpeg -loglevel warning -f lavfi -i anullsrc -i rtsp://localhost:8554/ipcamera \
-c:v copy -tag:v hvc1 -c:a aac -map 0:a -map 1:v -shortest -f hls -method POST -hls_time 1 -hls_playlist_type event -http_persistent 1 \
'https://a.upload.youtube.com/http_upload_hls?cid=wxyz-wxyz-wxyz-wxyz-wxyz&copy=0&file=stream.m3u8' &

p2="$!"
echo "public stream, without audio (silence), has PID=${p2}"
echo "-----"

# see https://stackoverflow.com/a/57189864/923560
# memorize exit status of earliest exited stream, and make sure a non-zero exit status
# does not early-exit the whole script in case "set -e" is in use
# see https://www.gnu.org/software/bash/manual/html_node/Lists.html
# see https://www.gnu.org/software/bash/manual/html_node/Job-Control-Builtins.html#index-wait
# see https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html#index-set
WAIT_N_EXIT_STATUS=0
wait -n -p FIRST_EXITED_PID || WAIT_N_EXIT_STATUS="$?"
echo "WAIT_N_EXIT_STATUS=${WAIT_N_EXIT_STATUS}"
echo "FIRST_EXITED_PID=${FIRST_EXITED_PID}"

# explanation:
#   once the script is past the previous "wait -n ...", at least one of the backgrounded two ffmpeg youtube streams has exited,
#   likely because of some ffmpeg error.
#   in the following, 'kill "$p1" "$p2"' will make sure that both ffmpeg youtube streams exit/are killed.
#   this script will then exit. once exited, mediamtx.yml's path "ipcamera" setup with "runOnReadyRestart: yes" will make sure
#   that _this_ script will execute again and set up both youtube streams again.
#   a more efficient setup would be to not kill both youtube streams and instead only restart the failing youtube stream.
#
#   also, via https://superuser.com/a/155915/137881 :
#   let kill exit with exit status 0, even if specified process to be killed does not exist anymore, for scripts using "set -e".
kill "$p1" "$p2" || :

echo "exiting with exit status ${WAIT_N_EXIT_STATUS}"
exit "$WAIT_N_EXIT_STATUS"
```
