### ISSUE TITLE
Playback does not work when recording path is non-default

### ISSUE THREAD

**Issue by davidrylance** [bluenviron/mediamtx#3172]
Dear Mediamtx developers and maintainers,

This is fantastic project. Thank you!

I enabled recording and I verified that mp4 files are created and saved.

Then I enabled `playback` and wanted to use it as:

``` sh
curl -L  'http://.../list?path=my_cam'
```

but I got:
```
ERR [playback] lstat /recordings/my_cam: no such file or directory
```
in logs.

My configuration has changed path for the recordings and that's probably the problem.

``` yaml
playback: yes

pathDefaults:
  record: no
  playback: yes
  recordFormat: fmp4
  recordPartDuration: 100ms
  recordSegmentDuration: 1h
  recordDeleteAfter: 0s

paths:
  my_cam:
    source: 'rtsp://...'
    record: true
    recordPath: '/var/...' # custom
  my_cam2:
    source: 'rtsp://...'
    record: false
    # ...
```

## Which version are you using?

v1.5.1

## Which operating system are you using?

- [x] Linux amd64 standard
