### ISSUE TITLE
K8s Deployment goes wrong without giving any useful hint

### ISSUE THREAD

**Issue by manfredipist** [bluenviron/mediamtx#3236]
## Which version are you using?

v1.6.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

I'm deploying the following configMap and deployment to my cluster

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mediamtx-config
  namespace: mytv
data:
  MTX_LOGLEVEL: "debug"
  MTX_PROTOCOLS: "tcp"
  MTX_RTMPDISABLE: "no"
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mediamtx-secret
  namespace: mytv
type: Opaque
stringData:
  MTX_PATHS_ALL_PUBLISHUSER: "user"
  MTX_PATHS_ALL_PUBLISHPASS: "pass"
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamtx-deployment
  namespace: mytv
spec:
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      containers:
      - image: bluenviron/mediamtx:latest-ffmpeg
        imagePullPolicy: IfNotPresent
        name: mediamtx
        ports:
          - containerPort: 8554
            protocol: TCP
          - containerPort: 1935
            protocol: TCP
          - containerPort: 8888
          - containerPort: 8889
        envFrom:
          - configMapRef:
              name: mediamtx-config
          - secretRef:
              name: mediamtx-secret
        livenessProbe:
          tcpSocket:
            port: 8554
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 3
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
```

## Did you attach the server logs?

```
ERR: all_others, all and '~^.*$' are aliases
ERR: all_others, all and '~^.*$' are aliases
ERR: all_others, all and '~^.*$' are aliases
ERR: all_others, all and '~^.*$' are aliases
```
