### ISSUE TITLE
Seperate Record Settings

### ISSUE THREAD

**Issue by pankajsaini1987** [bluenviron/mediamtx#3269]
## Describe the feature

Description
Right now there is only option either we can start recording or stop recording for all added devices and same settings for all like record duration, record format etc.
it will be better if we can control recording on/off for individual device and can be control by api, we can call api for start or stop recordings, and if possible related settings like duration, format etc.

thank you for understanding

**Comment by aler9** [comment]
Hello, you can already tune settings for individual devices by adding them to the `path` section, under the key that corresponds to each device:

```yml
paths:
  my_device_1:
    source: rtsp://my-source
    record: yes
    recordFormat: mpegts

  my_device_2:
    source: rtsp://my-source
    record: no

  my_published_path:
    source: publisher
    record: yes


```
