### ISSUE TITLE
Play other path if stream not ready or publisher dissconnected

### ISSUE THREAD

**Issue by mohsundiod** [bluenviron/mediamtx#3333]
## Describe the feature
media server play default file in loop (mp4 or jpeg or other path) if publisher is not ready.

**Comment by eravellaSC** [comment]
Have you tried using the `runOnNotReady`  hook in combination with ffmpeg to stream a file?

**Comment by mohsundiod** [comment]
tanx, runOnNotReady do it with this config:
```
paths:
  udp:
    source: udp://238.0.0.1:1234

    runOnReady: ./ffmpeg.exe -i rtsp://localhost:$RTSP_PORT/$MTX_PATH -c:v copy -c:a copy -f rtsp -rtsp_transport tcp rtsp://localhost:$RTSP_PORT/live
    runOnReadyRestart: no

    runOnNotReady: ./ffmpeg.exe -re -f lavfi -i testsrc=size=1280x720:rate=30 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -f rtsp -rtsp_transport tcp rtsp://localhost:$RTSP_PORT/live

  live:
```
Problem:
the client dissconnect from server.
can switch stream on the fly?
