### ISSUE TITLE
Configure a GitHub issue template

### ISSUE THREAD

**Issue by moenodedev** [bluenviron/mediamtx#3439]
## Describe the feature

Description

MediaMTX is an incredible project. We're using it in production and it's stable however when we encounter errors a GitHub issue form will make it easier to submit issues and attach logs and hopefully make it easier for people to review what's submitted 🙂

We will see less issues closed because of missing fields

![image](https://github.com/bluenviron/mediamtx/assets/113457600/e8a4d621-58bf-4922-a702-3aebb5b74ce4)

Making the OS selection a dropdown also removes the tasks completed message in the issue list

<img width="323" alt="image" src="https://github.com/bluenviron/mediamtx/assets/113457600/7611c60a-dc08-4fe3-bc8c-250030c091db">

## Preview
![image](https://github.com/bluenviron/mediamtx/assets/113457600/8e844e80-d515-4afb-a570-9b70eea5e819)

## Template
`.github/ISSUE_TEMPLATE/bug.yml`
```yaml
name: Bug
description:  Report a bug 
title: "BUG: "
labels: ["bug"]
projects: []
assignees: []
body:
  - type: input
    id: version
    attributes:
      label: Which version are you using?
      description: MediaMTX version or commit
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which operating system are you using?
      multiple: true
      options:
        - Linux amd64 standard
        - Linux amd64 Docker
        - Linux arm64 standard
        - Linux arm64 Docker
        - Linux arm7 standard
        - Linux arm7 Docker
        - Linux arm6 standard
        - Linux arm6 Docker
        - Windows amd64 standard
        - Windows amd64 Docker (WSL backend)
        - macOS amd64 standard
        - macOS amd64 Docker
        - Other (please describe)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe how to replicate the issue
      description: The maintainers must be able to REPLICATE your issue to solve it - therefore, describe in a very detailed way how to replicate it.
      placeholder: Tell us what you see!
      value: |
        1. start the server
        2. publish with ...
        3. read with ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Server logs
      description: Server logs are sometimes useful to identify the issue. If you think this is the case, set the parameter 'logLevel' to 'debug' and attach the server logs.
      placeholder: Paste or drag the log file here 
      # placeholder: This will be automatically formatted into code, so no need for backticks.
      # render: shell
  - type: textarea
    id: network
    attributes:
      label: Network dump
      description: |
        If the bug arises when using MediaMTX with external hardware or software, the most helpful content you can provide is a dump of the data exchanged between the server and the target (network dump).
        
        That can be generated in this way:
          1. Download wireshark (https://www.wireshark.org/)
          2. Start capturing on the interface used for exchanging packets
            * If the server and the external hardware or software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card
          3. Start the server and replicate the issue
          4. Stop capturing, save the result in .pcap format
          5. Attach
      placeholder: Attach the pcap file by dragging it here
```
