### ISSUE TITLE
rpiCameraHFlip flips vertically and rpiCameraVFlip flips horizontally

### ISSUE THREAD

**Issue by mdPlusPlus** [bluenviron/mediamtx#3472]
## Which version are you using?

v1.8.3

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [x] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

rpiCameraHFlip and rpiCameraVFlip are switched around

## Describe how to replicate the issue

Raspberry Pi Zero 2 W  
Raspbian Bullseye 64-bit  
Raspberry Camera Module v3

```
paths:
  cam:
    source: rpiCamera
    rpiCameraWidth: 1920
    rpiCameraHeight: 1080
    rpiCameraFPS: 30
    rpiCameraBitrate: 8000000
    rpiCameraHFlip: true
```
flips vertically (left/right)

```
paths:
  cam:
    source: rpiCamera
    rpiCameraWidth: 1920
    rpiCameraHeight: 1080
    rpiCameraFPS: 30
    rpiCameraBitrate: 8000000
    rpiCameraVFlip: true
```
flips horizontally (top/bottom)

## Did you attach the server logs?

no

## Did you attach a network dump?

no
