### ISSUE TITLE
recordDeleteAfter parameter not being applied correctly

### ISSUE THREAD

**Issue by anktx** [bluenviron/mediamtx#3556]
## Which version are you using?
MediaMTX v1.8.4, Linux amd64 Docker

## Describe the issue

Hi Team,

I am experiencing an issue with the recordDeleteAfter parameter in the MediaMTX configuration file. Despite setting a specific value for a path, the recordings are still being deleted based on the default value.

Here is my configuration file:

```
pathDefaults:
  record: no
  recordSegmentDuration: 1h
  recordDeleteAfter: 168h

paths:
  office:
    source: rtsp://go2rtc:8554/office-main
    recordDeleteAfter: 336h

  office-sub:
    source: rtsp://go2rtc:8554/office-sub
    record: yes
```

In this configuration, I expect the recordings for the office path to be stored for 336 hours and the recordings for the office-sub path to be stored for 168 hours. However, both paths seem to follow the default recordDeleteAfter value of 168 hours.

Additionally, I enable recording for the office path via the API.

Could you please help me understand why the recordDeleteAfter parameter is not being applied correctly for the office path? Is there something wrong with my configuration, or could this be a bug?

Thank you for your assistance.
