### ISSUE TITLE
recordDeleteAfter parameter not being applied correctly

### ISSUE THREAD

**Issue by anktx** [bluenviron/mediamtx#3557]
## Which version are you using?

v1.8.4

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Hi Team,

I am experiencing an issue with the recordDeleteAfter parameter in the MediaMTX configuration file. Despite setting a specific value for a path, the recordings are still being deleted based on the default value.

Here is my configuration file:
```
pathDefaults:
  record: no
  recordSegmentDuration: 1h
  recordDeleteAfter: 168h

paths:
  office:
    source: rtsp://go2rtc:8554/office-main
    recordDeleteAfter: 336h

  office-sub:
    source: rtsp://go2rtc:8554/office-sub
    record: yes
```
In this configuration, I expect the recordings for the office path to be stored for 336 hours and the recordings for the office-sub path to be stored for 168 hours. However, both paths seem to follow the default recordDeleteAfter value of 168 hours.

Additionally, I enable recording for the office path via the API.

Could you please help me understand why the recordDeleteAfter parameter is not being applied correctly for the office path? Is there something wrong with my configuration, or could this be a bug?

Thank you for your assistance.

## Describe how to replicate the issue

**Steps to reproduce the issue:**

1. Start the MediaMTX server with the provided configuration file.
2. Observe the recordings for both office and office-sub paths.
3. Verify the duration of stored recordings for both paths after 168 hours.

**Expected Result:**

    Recordings for the office path should be stored for 336 hours.
    Recordings for the office-sub path should be stored for 168 hours.

**Actual Result:**

    Both paths follow the default recordDeleteAfter value of 168 hours.

## Did you attach the server logs?

no

## Did you attach a network dump?

no
