### ISSUE TITLE
Allow runOnDemand in combination with source: udp

### ISSUE THREAD

**Issue by RedShift1** [bluenviron/mediamtx#3790]
When trying to use a runOnDemand command in combination with `source: udp://0.0.0.0:1234`, like so:

```yaml
paths:
  test:
   source: udp://0.0.0.0:1234
   runOnDemand: some_command_to_start_streaming_to_port_1234
```

it doesn't work because the `source` must be `publisher`: 

```ERR: 'runOnDemand' and 'runOnUnDemand' can be used only when source is 'publisher'```

I think there's technically no reason why runOnDemand can't work with a UDP source?
