### ISSUE TITLE
Path staying ready when pulled source no longer available

### ISSUE THREAD

**Issue by jahaddow** [bluenviron/mediamtx#3880]
### Which version are you using?

1.9.2

### Which operating system are you using?

Windows amd64 standard

### Describe how to replicate the issue

1. Pull SRT stream hosted as listener on another server using path: source:
2. Use RunOnReady: with gstreamer pipeline to output source as an NDI feed.
3. SRT feed disconnected from upstream server. Ie. Camera is turned off.
4. MediaMTX keeps trying to reconnect to SRT server. (as expected)
5. Path stays ready on MediaMTX.
6. Gstreamer command doesn't stop.

```
  path:
    source: srt://xxxxxxxxxxxx.net:8890?streamid=xxxxxxx
    runOnReady: gst-launch-1.0 srtsrc uri="srt://127.0.0.1:8890?streamid=read:path" ! decodebin name=dec dec. ! queue ! videoconvert ! ndisinkcombiner name=combiner ! ndisink ndi-name="NDIout" dec. ! queue ! audioconvert ! combiner.audio
    runOnReadyRestart: yes
```

When we turn off our upstream camera, which runs the srt listening service, MediaMTX keeps the path as ready. Which then causes Gstreamer pipeline to keep running and then fail as it keeps trying to reconnect.

MediaMTX should unpublish path until source reconnects.
