### ISSUE TITLE
configured the paths in yml using a regular expression, and the parameters in the url will be discarded when the server requests it

### ISSUE THREAD

**Issue by sean-0925** [bluenviron/mediamtx#3905]
### Which version are you using?

1.9.3

### Which operating system are you using?

Linux amd64 Docker

### Describe how to replicate the issue

I configured paths in yml using regular expressions. When the server forwards the URL request from the client, it will discard the parameter part of the client request URL link.

mediamtx.yml
![yml](https://github.com/user-attachments/assets/374945a5-4981-45a7-83f4-79e714e624f2)

mediamtx.log
![log](https://github.com/user-attachments/assets/b14767af-858d-4d5b-a09f-57db51ebb7ff)

**Comment by aler9** [comment]
Hello, the parameter part is stored inside the $MTX_QUERY variable, so the right configuration for achieving what you want is:

```yml
paths:
  "~proxy_(.+)$":
    source: rtsp://localhost:8554/$G1?$MTX_QUERY
    sourceOnDemand: true
```
