### ISSUE TITLE
(low) HLS endpoints do not trigger runOnDemand if hlsAlwaysRemux on

### ISSUE THREAD

**Issue by vgavro** [bluenviron/mediamtx#3954]
### Which version are you using?

1.9.3

### Which operating system are you using?

Linux amd64 standard

### Describe how to replicate the issue

1. start the server with:
```
logLevel: debug
# .... defaults

hlsAlwaysRemux: yes   # <-- this is reproducable specificly if it's on
paths:
  audio:
     runOnDemand: echo hello world
```
2. read with:
```
curl -v http://localhost:8888/audio/index.m3u8
curl -v http://localhost:8888/audio
curl -v http://localhost:8888/audio/
# 404 page not found
# doesn't print "hello world" in server console with debug enabled
```

ensure runOnDemand actually works:
```
mpv rtsp://localhost:8554/audio
# prints "hello world" in server console with debug enabled
```

ensure HLS actually works after runOnDemand was triggered by rtsp.
```
(well, it works, not with "echo hello world"  command but trust me i've checked :-)
```

### Server logs

 HTTP/1.1 404 Not Found
