### ISSUE TITLE
MTX_CONN_TYPE in webhooks contains simply word "conn" instead of connection type (rtmp, rtsp, etc)

### ISSUE THREAD

**Issue by terion-name** [bluenviron/mediamtx#3967]
### Which version are you using?

1.9.3

### Which operating system are you using?

Linux amd64 Docker

### Describe how to replicate the issue

config:

```yml
# Command to run when a client connects to the server.
# This is terminated with SIGINT when a client disconnects from the server.
# The following environment variables are available:
# * RTSP_PORT: RTSP server port
# * MTX_CONN_TYPE: connection type
# * MTX_CONN_ID: connection ID
runOnConnect: 'curl -X POST http://mtx-viewer:8080/start -H "Content-Type: application/x-www-form-urlencoded" -d "id=${MTX_CONN_ID}&ctype=${MTX_CONN_TYPE}"'
# Restart the command if it exits.
runOnConnectRestart: no
# Command to run when a client disconnects from the server.
# Environment variables are the same of runOnConnect.
runOnDisconnect: 'curl -X POST http://mtx-viewer:8080/stop -H "Content-Type: application/x-www-form-urlencoded" -d "id=${MTX_CONN_ID}&ctype=${MTX_CONN_TYPE}"'
```

connecting with rtmp or rtsp — and callbacks receive only word "conn" in payloads
