### ISSUE TITLE
support customizing internal authentication by protocol

### ISSUE THREAD

**Issue by aler9** [bluenviron/mediamtx#4103]
### Describe the feature

Discussed in #3908 

for instance:

```yml
authInternalUsers:
- user: any
  pass:
  ips: []
  permissions:
  - action: publish
    path:
    protocol: rtmp
```
