### ISSUE TITLE
WebRTC stream does not work, `x RTP packets lost` spammed in log

### ISSUE THREAD

**Issue by fxzzi** [bluenviron/mediamtx#4202]
### Which version are you using?

1.11.1

### Which operating system are you using?

Linux amd64 standard

### Describe how to replicate the issue

1. start the server with obs. i used a simple screen capture source at 1080p60 with a bitrate of 8000kbps.
2. publish it with webrtc
3. read it from any browser (i tried firefox and chromium)
4. notice the stream not working properly, with lots of "RTP packets lost" errors in the logs.
5. This is not an issue with firewall, the port I use (4200) is open and i can see on a port checker it is open as well.
6. This is not an issue with my network speed, shown below is my net speeds: 

![Image](https://github.com/user-attachments/assets/29a66566-eedb-4bf5-b177-277545b13503)

Here is my config:
```yaml
logLevel: debug
paths:
  all_others: {}
webrtc: true
webrtcAdditionalHosts:
- <publicip>
- 1.1.1.1
- 1.0.0.1
- 2606:4700:4700::1111
- 2606:4700:4700::1001
webrtcAddress: :4200
webrtcLocalUDPAddress: :4200
```

I do not think this issue is what was fixed by #4174 , as `webrtcIPsFromInterfaces` was not modified by me and should be true by default. That PR mentions it fixes things if this value is false.

### Server logs

https://paste.rs/VQrOM.txt contains the debug logs from mediamtx
