### ISSUE TITLE
write udp [::]:48533: missing address

### ISSUE THREAD

**Issue by Pepslee** [bluenviron/mediamtx#4253]
### Which version are you using?

1.11.3

### Which operating system are you using?

Linux amd64 standard

### Describe how to replicate the issue

1. add next  into config
```
rtspAnyPort: yes
...
paths:
  # example:
  lores:
    source: rtsp://10.10.10.2:554/live0
```
2. start mediamtx with config
3. If I'm trying to pull rtsp stream from mediamtx with gst-launch it interrupts after a few seconds, but if I'm pulling directly from rtsp://10.10.10.2:554/live0 with gst-launch it works fine.

In log I can see this message:
`ERR [path lores] [RTSP source] write udp [::]:43491: missing address`

Is there any way to solve this problem?

### Server logs

[mediamtx.log](https://github.com/user-attachments/files/18795312/mediamtx.log)
