### ISSUE TITLE
Support forwarding streams to other servers natively

### ISSUE THREAD

**Issue by aler9** [bluenviron/mediamtx#4273]
### Describe the feature

Discussed in #2879 

This feature is already available by using FFmpeg or GStreamer inside `runOnReady`, as described in the [README](https://github.com/bluenviron/mediamtx?tab=readme-ov-file#forward-streams-to-other-servers).

Supporting it natively would improve efficiency and decrease dependency on external software.

Sample configuration:

```yml
paths:
  mypath:
    source: rtsp://my-camera
    forward:
    - dest: whip://other-webrtc-server/other-whip-endpoint
    - dest: rtsp://other-rtsp-server/path
```
