### ISSUE TITLE
Unathorized error for streaming audio_with_cam on raspberrypi zero 2W using yocto

### ISSUE THREAD

**Issue by adejewski** [bluenviron/mediamtx#4358]
### Which version are you using?

1.9.3

### Which operating system are you using?

Other (please describe)

### Describe how to replicate the issue

Hi,

I am trying to make mediamtx work on raspberrypi zero 2w with yocto scarthgap. I've managed to compile mediamtx and make it work with the camera which works really nice. The problem is with the audio, I cannot stream that.

After solving a couple of issues I am getting unauthorized error and not sure what is the root cause of that.

My config is pretty basic the only thing I've modified is:
```
paths:
  # example:
  # my_camera:
  #   source: rtsp://my_camera
  cam:
    source: rpiCamera
  
  cam_with_audio:
    runOnInit: >
      gst-launch-1.0
      rtspclientsink name=s location=rtsp://localhost:$RTSP_PORT/cam_with_audio
      rtspsrc location=rtsp://127.0.0.1:$RTSP_PORT/cam latency=0 ! rtph264depay ! s.
      alsasrc device=hw:0 ! audioconvert ! vorbisenc ! s.
    runOnInitRestart: yes

  # Settings under path "all_others" are applied to all paths that
  # do not match another entry.
  all_others:

```

I am attaching log as well, in line 7238 you can see unauthorized error.

I am using the older version because this version of Yocto does not support Go1.23.

Thanks

### Server logs

[mediamtx.log](https://github.com/user-attachments/files/19368260/mediamtx.log)

**Comment by aler9** [comment]
Hello, if the server replies with an unauthorized error, it means that the publisher of the stream (in this case `gst-launch-1.0`) is not authorized to perform the operation. You can authorize it by adding an entry inside `authInternalUsers`:

```yml
authInternalUsers:

# enable all software on localhost to publish without credentials.
# you can also fill user / pass to increase security.
- user: any
  ips: [127.0.0.1]
  permissions:
    - action: publish

# other entries
````

Furthermore, the Vorbis codec is not supported by WebRTC, you have to use Opus:

```yml
  cam_with_audio:
    runOnInit: >
      gst-launch-1.0
      rtspclientsink name=s location=rtsp://localhost:$RTSP_PORT/cam_with_audio
      rtspsrc location=rtsp://127.0.0.1:$RTSP_PORT/cam latency=0 ! rtph264depay ! s.
      alsasrc device=default:CARD=U0x46d0x809 ! opusenc bitrate=16000 ! s.
    runOnInitRestart: yes
```
