### ISSUE TITLE
`recordDeleteAfter` does not delete old recordings or empty directories

### ISSUE THREAD

**Issue by anktx** [bluenviron/mediamtx#4449]
### Which version are you using?

v1.12.0

### Which operating system are you using?

Linux amd64 Docker

### Problem description

In MediaMTX v1.12.0, recordings are not being deleted automatically after the `recordDeleteAfter` duration. Additionally, empty directories created by the `recordPath` template are never removed, even after all files inside are deleted or expired.

There are two paths configured:

- For `parking`, I enable recording **dynamically via the API** (i.e. it’s not recorded by default).
- For `parking-sub`, recording is enabled in the config.

In `parking-sub`, old segments **are deleted properly** after the set time, but the empty folders remain.

In `parking`, **no old files are deleted at all**, even though `recordDeleteAfter: 14d` is set and files are well past that age.

### Configuration

```yaml
record: no
recordPath: /recordings/%path/%Y-%m-%d/%Y-%m-%d__%H-%M-%S
recordFormat: fmp4
recordPartDuration: 1s
recordSegmentDuration: 1h
recordDeleteAfter: 7d

paths:
  parking:
    source: rtsp://go2rtc:8554/parking-main
    recordDeleteAfter: 14d

  parking-sub:
    source: rtsp://go2rtc:8554/parking-sub
    record: yes
```

### Expected behavior

    Files older than recordDeleteAfter should be automatically deleted.

    Empty directories created via recordPath should be removed if they are unused.

### Actual behavior

    In parking-sub: old files are deleted as expected, empty folders remain.

    In parking: old files are not deleted at all, folders pile up.

    Restarting MediaMTX does not help.

    Time on system is synchronized via NTP.

### Additional notes

    Recording itself works correctly — segments are being created and accessible.

    Possibly related to #3557 (deletion) and #4227 (folder cleanup).

Please confirm whether this is a bug or if some extra configuration is required. If folder cleanup is not implemented, it would be a valuable feature.
