### ISSUE TITLE
can not play by webrtc

### ISSUE THREAD

**Issue by dannyxu2015** [bluenviron/mediamtx#4459]
### Which version are you using?

bluenviron/mediamtx:latest sha256:64a9223729c94395ca561a220e8d2b82c68797e8258a3b9c2ee82dca0e387757

### Which operating system are you using?

macOS amd64 standard

### Describe how to replicate the issue

1. start the server
2. publish with rtsp by ffmpeg
3. read with browser: http://localhost:8889/live

### Server logs

2025/04/22 07:24:44 INF [RTSP] [conn 192.168.65.1:42639] opened
2025/04/22 07:24:44 INF [RTSP] [session da363168] created by 192.168.65.1:42639
2025/04/22 07:24:44 INF [RTSP] [session da363168] is publishing to path 'live', 2 tracks (H264, MPEG-4 Audio)
2025/04/22 07:24:44 INF [WebRTC] [session b6d3e447] created by 192.168.65.1:51617
2025/04/22 07:24:44 WAR [WebRTC] [session b6d3e447] skipping track 2 (MPEG-4 Audio)
2025/04/22 07:25:02 INF [WebRTC] [session b6d3e447] closed: deadline exceeded while waiting connection
2025/04/22 07:25:09 INF [WebRTC] [session 5db9eada] created by 192.168.65.1:51617
2025/04/22 07:25:09 WAR [WebRTC] [session 5db9eada] skipping track 2 (MPEG-4 Audio)
2025/04/22 07:25:19 INF [WebRTC] [session f384dc78] created by 192.168.65.1:51617
2025/04/22 07:25:19 WAR [WebRTC] [session f384dc78] skipping track 2 (MPEG-4 Audio)
2025/04/22 07:25:27 INF [WebRTC] [session 5db9eada] closed: deadline exceeded while waiting connection
2025/04/22 07:25:37 INF [WebRTC] [session f384dc78] closed: deadline exceeded while waiting connection
2025/04/22 07:25:45 INF [WebRTC] [session ea072c6d] created by 192.168.65.1:51617
2025/04/22 07:25:45 WAR [WebRTC] [session ea072c6d] skipping track 2 (MPEG-4 Audio)

### Network dump

My PC: macos 15.4.1

ffmpeg command: `ffmpeg -re -stream_loop -1 -i ~/Downloads/oceans.mp4 -s 426x240 -c:v libx264 -profile:v baseline -b:v 1M -r 24 -g 60  -f rtsp rtsp://localhost:8554/live`

start the mediamtx by docker: `docker run -d --name mediamtx -v /path/x.yml:/mediamtx.yml:ro -p 8554:8554 -p 8889:8889 -p 9997:9997 -p 8888:8888 bluenviron/mediamtx`

localhost:8888/live is ok, but can not get the stream from localhost:8889/live(display info in browser: peer connection closed, retrying in some seconds')
my config file:
```
protocols: [tcp]
paths:
  all:
    source: publisher

# Enable controlling the server through the Control API.
api: yes
# Address of the Control API listener.
apiAddress: :9997

authInternalUsers:
  # Default unprivileged user.
  # Username. 'any' means any user, including anonymous ones.
#- user: admin
#  pass: admin123
#  permissions:
#  - action: publish
#  - action: read
#  - action: api
- user: any
  # Password. Not used in case of 'any' user.
  pass:
  # IPs or networks allowed to use this user. An empty list means any IP.
  ips: []
  # List of permissions.
  permissions:
    # Available actions are: publish, read, playback, api, metrics, pprof.
  - action: publish
    # Paths can be set to further restrict access to a specific path.
    # An empty path means any path.
    # Regular expressions can be used by using a tilde as prefix.
    path:
  - action: read
    path:
  - action: playback
    path:
  - action: api

###############################################
# Global settings -> WebRTC server

# Enable publishing and reading streams with the WebRTC protocol.
webrtc: yes
# Address of the WebRTC HTTP listener.
webrtcAddress: :8889
# Enable TLS/HTTPS on the WebRTC server.
webrtcEncryption: no
# Path to the server key.
# This can be generated with:
# openssl genrsa -out server.key 2048
# openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650
webrtcServerKey: server.key
# Path to the server certificate.
webrtcServerCert: server.crt
# Value of the Access-Control-Allow-Origin header provided in every HTTP response.
# This allows to play the WebRTC stream from an external website.
webrtcAllowOrigin: '*'
# List of IPs or CIDRs of proxies placed before the WebRTC server.
# If the server receives a request from one of these entries, IP in logs
# will be taken from the X-Forwarded-For header.
webrtcTrustedProxies: []
# Address of a local UDP listener that will receive connections.
# Use a blank string to disable.
webrtcLocalUDPAddress: :8189
# Address of a local TCP listener that will receive connections.
# This is disabled by default since TCP is less efficient than UDP and
# introduces a progressive delay when network is congested.
webrtcLocalTCPAddress: ''
# WebRTC clients need to know the IP of the server.
# Gather IPs from interfaces and send them to clients.
webrtcIPsFromInterfaces: yes
# List of interfaces whose IPs will be sent to clients.
# An empty value means to use all available interfaces.
webrtcIPsFromInterfacesList: []
# List of additional hosts or IPs to send to clients.
webrtcAdditionalHosts: []
# ICE servers. Needed only when local listeners can't be reached by clients.
# STUN servers allows to obtain and share the public IP of the server.
# TURN/TURNS servers forces all traffic through them.
webrtcICEServers2:
  - url: stun:stun.l.google.com:19302
# Time to wait for the WebRTC handshake to complete.
webrtcHandshakeTimeout: 10s
# Maximum time to gather video tracks.
webrtcTrackGatherTimeout: 2s
# The maximum time to gather STUN candidates.
webrtcSTUNGatherTimeout: 5s
```
