### ISSUE TITLE
Validation of the path.RecordPath parameters is throwing errors even if Record is false

### ISSUE THREAD

**Issue by IDisposable** [bluenviron/mediamtx#4481]
### Which version are you using?

1.12.0

### Which operating system are you using?

Linux arm64 Docker

### Describe how to replicate the issue

The [changes added between 1.11.3 and 1.12.0](https://github.com/bluenviron/mediamtx/compare/v1.11.3...v1.12.0#diff-30dcec31a211c0fbea65515bb9148d50a8d2dadc675034fcff5fa2a30b93cf07L479-R596) added more validation to the path recording configuration settings. This now throws an error in uses where there was no problem before because the validation of `RecordPath` is now executed and an error thrown **even if** the  path was never set to record. In 1.11.3, it was conditional on `if conf.Playback {` which is no longer tested.

This makes things previously working projects [docker_wyze_bridge](https://github.com/IDisposable/docker-wyze-bridge/) fail if we try to use 1.12.0 in situations where the previously unchecked recording path configuration in `mediamtx.yml` which _was accepted in 1.11.3 now fails in 1.12.0_. 

I am running a new fork of `docker-wyze-bridge` (due to the original author getting busy), and tried to get current on dependencies. A [bug report](https://github.com/IDisposable/docker-wyze-bridge/issues/16) filed in the `IDisposable\docker_wyze_bridge` repo shows that this is an unexpected issue when upgrading `MediaMTX`.

For the meantime, I'm going to add logic in version 3.10.2 to ensure we don't bomb, but it would be **REALLY** great if this breaking change on the MediaMTX side was reverted or corrected to only assert the validation of the recording parameters of a path _if_ the path is set to `.Record`  (was `.Playback` but that's now logged as deprecated).

The code block in [internal/conf/path.go](https://github.com/bluenviron/mediamtx/blob/main/internal/conf/path.go#L565-L595) should really test if `pconf.Record` and skip validation if it is not `true`.

Sample *mediamtx.yml* from inside the container:
```yaml
logLevel: info
logDestinations:
- stdout
logFile: mediamtx.log
sysLogPrefix: mediamtx
readTimeout: 10s
writeTimeout: 10s
writeQueueSize: 512
udpMaxPayloadSize: 1472
runOnConnect: null
runOnConnectRestart: false
runOnDisconnect: null
authMethod: internal
authInternalUsers:
- user: any
  ips:
  - 127.0.0.1
  - ::1
  permissions:
  - action: api
  - action: metrics
  - action: pprof
- user: any
  ips:
  - 127.0.0.1
  - ::1
  permissions:
  - action: read
  - action: playback
  - action: publish
- user: wb
  pass: WJ6tLgTF0uWmneJzy7Aq7WRYoP_aBB_cngiFyWhK
  permissions:
  - action: read
  - action: playback
authHTTPAddress: null
authHTTPExclude:
- action: api
- action: metrics
- action: pprof
authJWTJWKS: null
authJWTClaimKey: mediamtx_permissions
api: false
apiAddress: :9997
apiEncryption: false
apiServerKey: server.key
apiServerCert: server.crt
apiAllowOrigin: '*'
apiTrustedProxies: []
metrics: false
metricsAddress: :9998
metricsEncryption: false
metricsServerKey: server.key
metricsServerCert: server.crt
metricsAllowOrigin: '*'
metricsTrustedProxies: []
pprof: false
pprofAddress: :9999
pprofEncryption: false
pprofServerKey: server.key
pprofServerCert: server.crt
pprofAllowOrigin: '*'
pprofTrustedProxies: []
playback: false
playbackAddress: :9996
playbackEncryption: false
playbackServerKey: server.key
playbackServerCert: server.crt
playbackAllowOrigin: '*'
playbackTrustedProxies: []
rtsp: true
rtspTransports:
- udp
- multicast
- tcp
rtspEncryption: 'no'
rtspAddress: :8554
rtspsAddress: :8322
rtpAddress: :8000
rtcpAddress: :8001
multicastIPRange: 224.1.0.0/16
multicastRTPPort: 8002
multicastRTCPPort: 8003
rtspServerKey: server.key
rtspServerCert: server.crt
rtspAuthMethods:
- basic
rtmp: true
rtmpAddress: :1935
rtmpEncryption: 'no'
rtmpsAddress: :1936
rtmpServerKey: server.key
rtmpServerCert: server.crt
hls: true
hlsAddress: :8888
hlsEncryption: false
hlsServerKey: server.key
hlsServerCert: server.crt
hlsAllowOrigin: '*'
hlsTrustedProxies: []
hlsAlwaysRemux: false
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsSegmentMaxSize: 50M
hlsDirectory: ''
hlsMuxerCloseAfter: 60s
webrtc: true
webrtcAddress: :8889
webrtcEncryption: false
webrtcServerKey: server.key
webrtcServerCert: server.crt
webrtcAllowOrigin: '*'
webrtcTrustedProxies: []
webrtcLocalUDPAddress: :8189
webrtcLocalTCPAddress: ''
webrtcIPsFromInterfaces: true
webrtcIPsFromInterfacesList: []
webrtcAdditionalHosts: []
webrtcICEServers2: []
webrtcHandshakeTimeout: 10s
webrtcTrackGatherTimeout: 2s
webrtcSTUNGatherTimeout: 5s
srt: true
srtAddress: :8890
pathDefaults:
  source: publisher
  sourceFingerprint: null
  sourceOnDemand: false
  sourceOnDemandStartTimeout: 10s
  sourceOnDemandCloseAfter: 10s
  maxReaders: 0
  srtReadPassphrase: null
  fallback: null
  useAbsoluteTimestamp: false
  record: false
  recordPath: /recordings/%path/%Y/%m/%d/%H%M%S
  recordFormat: fmp4
  recordPartDuration: 1s
  recordSegmentDuration: 60s
  recordDeleteAfter: 0s
  overridePublisher: true
  srtPublishPassphrase: null
  rtspTransport: automatic
  rtspAnyPort: false
  rtspRangeType: null
  rtspRangeStart: null
  sourceRedirect: null
  rpiCameraCamID: 0
  rpiCameraSecondary: false
  rpiCameraWidth: 1920
  rpiCameraHeight: 1080
  rpiCameraHFlip: false
  rpiCameraVFlip: false
  rpiCameraBrightness: 0
  rpiCameraContrast: 1
  rpiCameraSaturation: 1
  rpiCameraSharpness: 1
  rpiCameraExposure: normal
  rpiCameraAWB: auto
  rpiCameraAWBGains:
  - 0
  - 0
  rpiCameraDenoise: 'off'
  rpiCameraShutter: 0
  rpiCameraMetering: centre
  rpiCameraGain: 0
  rpiCameraEV: 0
  rpiCameraROI: null
  rpiCameraHDR: false
  rpiCameraTuningFile: null
  rpiCameraMode: null
  rpiCameraFPS: 30
  rpiCameraAfMode: continuous
  rpiCameraAfRange: normal
  rpiCameraAfSpeed: normal
  rpiCameraLensPosition: 0.0
  rpiCameraAfWindow: null
  rpiCameraFlickerPeriod: 0
  rpiCameraTextOverlayEnable: false
  rpiCameraTextOverlay: '%Y-%m-%d %H:%M:%S - MediaMTX'
  rpiCameraCodec: auto
  rpiCameraIDRPeriod: 60
  rpiCameraBitrate: 5000000
  rpiCameraProfile: main
  rpiCameraLevel: '4.1'
  rpiCameraJPEGQuality: 60
  runOnInit: null
  runOnInitRestart: false
  runOnDemand: null
  runOnDemandRestart: false
  runOnDemandStartTimeout: 30s
  runOnDemandCloseAfter: 60s
  runOnUnDemand: null
  runOnReady: bash -c 'echo $MTX_PATH,Ready! > /tmp/mtx_event;'
  runOnReadyRestart: false
  runOnNotReady: bash -c 'echo $MTX_PATH,NotReady! > /tmp/mtx_event;'
  runOnRead: bash -c 'echo $MTX_PATH,Read! > /tmp/mtx_event;'
  runOnReadRestart: false
  runOnUnread: bash -c 'echo $MTX_PATH,Unread! > /tmp/mtx_event;'
  runOnRecordSegmentCreate: null
  runOnRecordSegmentComplete: null
paths:
  front-door:
    runOnDemand: bash -c 'echo $MTX_PATH,start! > /tmp/mtx_event'
    runOnUnDemand: bash -c 'echo $MTX_PATH,stop! > /tmp/mtx_event'
  bird-camera:
    runOnDemand: bash -c 'echo $MTX_PATH,start! > /tmp/mtx_event'
    runOnUnDemand: bash -c 'echo $MTX_PATH,stop! > /tmp/mtx_event'
  coop-camera:
    runOnDemand: bash -c 'echo $MTX_PATH,start! > /tmp/mtx_event'
    runOnUnDemand: bash -c 'echo $MTX_PATH,stop! > /tmp/mtx_event'
  basement-camera:
    runOnDemand: bash -c 'echo $MTX_PATH,start! > /tmp/mtx_event'
    runOnUnDemand: bash -c 'echo $MTX_PATH,stop! > /tmp/mtx_event'
  driveway-camera:
    runOnDemand: bash -c 'echo $MTX_PATH,start! > /tmp/mtx_event'
    runOnUnDemand: bash -c 'echo $MTX_PATH,stop! > /tmp/mtx_event'

```

### Server logs

```
[WyzeBridge] [MTX] starting MediaMTX 1.12.0
ERR: 'recordPath' must contain either %s or %Y %m %d %H %M %S
```

### Network dump

N/A
