### ISSUE TITLE
Unable to use existing RTSP credentials

### ISSUE THREAD

**Issue by hqkirkland** [bluenviron/mediamtx#4509]
### Which version are you using?

v1.12.2

### Which operating system are you using?

Windows amd64 standard

### Describe how to replicate the issue

After updating to 1.12, and without making any modifications to my YML, I am unable to authenticate using ffmpeg using the same credentials that I always use.

Don't panic, these credentials mean nothing to me. Will change them anyways.

FFMPEG Command:
`ffmpeg -re -ss 03:10:00.000 -i "D:\WQTV\Archive\Weekday\WQTV 2025-01-12-2.h265.mp4" -c:a libopus -c:v libvpx-vp9 -pix_fmt yuv420p -f rtsp -deadline realtime -row-mt 1 -minrate 2M -maxrate 2M -b:v 2M -strict experimental -filter:a loudnorm=I=-23:tp=-6 -compression_level 3 -cpu-used 4 rtsp://mediamtxusr:X8ofS3xgX@127.0.0.1:8554/nodebay`

FFMPEG Output:
`[rtsp @ 0000018976b06100] method ANNOUNCE failed: 401 Unauthorized`

YML:
```
- user: sha256:5u3rnPzFMrRfDrelJbqtqr9SsIqiGY9LAit2jb7zvLk=
  pass: sha256:uUDJxAp/w1A85AZ6LHYYpPst57kCjFVq8KDE6MQ1FhI=
  permissions:
  - action: publish
  - path:
```
