### ISSUE TITLE
Mediamtx Control API doesn't work

### ISSUE THREAD

**Issue by hyphypnotic** [bluenviron/mediamtx#4554]
### Which version are you using?

latest

### Which operating system are you using?

macOS amd64 Docker

### Describe how to replicate the issue

```mediamtx.yml
apiAddress: 0.0.0.0:9997
api: yes

rtspAddress: 0.0.0.0:8554
protocols: [tcp, udp]

rtmpAddress: 0.0.0.0:1935

paths:
  local_stream: {}
  internal_drone: {}
  local_platform: {}

```

```docker-compose.yml
version: '3'
services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - 8554:8554
      - 8322:8322
      - 1935:1935
      - 8888:8888
      - 8889:8889

    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
```

but when I do http request: curl http://0.0.0.0:9997/v3/paths/list
I got
curl: (7) Failed to connect to 0.0.0.0 port 9997 after 0 ms: Couldn't connect to server

logs:
```
[+] Running 2/0
 ✔ Network rtmp-to-rtsp_default  Created                                                                                                                    0.0s 
 ✔ Container mediamtx            Created                                                                                                                    0.0s 
Attaching to mediamtx
mediamtx  | 2025/05/24 06:31:40 WAR parameter 'protocols' is deprecated and has been replaced with 'rtspTransports'
mediamtx  | 2025/05/24 06:31:40 INF MediaMTX v1.12.2
mediamtx  | 2025/05/24 06:31:40 INF configuration loaded from /mediamtx.yml
mediamtx  | 2025/05/24 06:31:41 INF [RTSP] listener opened on 0.0.0.0:8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
mediamtx  | 2025/05/24 06:31:41 INF [RTMP] listener opened on 0.0.0.0:1935
mediamtx  | 2025/05/24 06:31:41 INF [HLS] listener opened on :8888
mediamtx  | 2025/05/24 06:31:41 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
mediamtx  | 2025/05/24 06:31:41 INF [SRT] listener opened on :8890 (UDP)
mediamtx  | 2025/05/24 06:31:41 INF [API] listener opened on :9997
```

**Comment by midoelhawy** [comment]
Hi @hyphypnotic,
you need to expose the API port in your `docker-compose.yml`. Here's an example:

```yaml
version: '3'
services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - 8554:8554
      - 8322:8322
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 9997:9997 # API is now accessible on port 9997 from the host
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
```
