### ISSUE TITLE
json: unknown field "runOnNotReady", json: unknown field "runOnRecordSegmentComplete"

### ISSUE THREAD

**Issue by ostrolucky** [bluenviron/mediamtx#4579]
### Which version are you using?

v1.11.3

### Which operating system are you using?

Linux amd64 standard

### Describe how to replicate the issue

I'm just trying to have a command launched whenever something is writing a stream and when this writing ends. So I tried `runOnRecordSegmentComplete` and `runOnNotReady` which I got from https://github.com/bluenviron/mediamtx/blob/main/mediamtx.yml, but neither seem working.

Example config
```yaml
hls: false
logLevel: debug
pathDefaults:
  record: true
  recordPath: /data/RTMP/%Y-%m%d_%H-%M-%S-%f
paths:
  mystream: null
playback: true
playbackAddress: :9996
rtmpAddress: 0.0.0.0:1935
runOnNotReady: "echo foo"
runOnReady: "echo bar"
```

I tried latest docker version too with no avail

### Server logs

```
máj 29 16:17:21 Kaby-Lake systemd[1]: mediamtx.service: Scheduled restart job, restart counter is at 4.
máj 29 16:17:21 Kaby-Lake systemd[1]: Started mediamtx.service.
máj 29 16:17:21 Kaby-Lake mediamtx[1466737]: ERR: json: unknown field "runOnNotReady"
máj 29 16:17:21 Kaby-Lake systemd[1]: mediamtx.service: Main process exited, code=exited, status=1/FAILURE
máj 29 16:17:21 Kaby-Lake systemd[1]: mediamtx.service: Failed with result 'exit-code'.
máj 29 16:17:21 Kaby-Lake systemd[1]: mediamtx.service: Scheduled restart job, restart counter is at 5.
máj 29 16:17:21 Kaby-Lake systemd[1]: mediamtx.service: Start request repeated too quickly.
máj 29 16:17:21 Kaby-Lake systemd[1]: mediamtx.service: Failed with result 'exit-code'.
máj 29 16:17:21 Kaby-Lake systemd[1]: Failed to start mediamtx.service.
```
