### ISSUE TITLE
[feature req] allow reading a list of webrtc additional hosts from a file

### ISSUE THREAD

**Issue by fxzzi** [bluenviron/mediamtx#4619]
### Describe the feature

When using secrets under NixOS, it becomes a challenge writing a secret directly to a file, due to many reasons. The best way would be to allow the upstream program to be given a path it can then read from.

Would this be possible with mediamtx? Possibly some extra configuration option which allows you to import config from another file?

so I can have

```yaml
webrtcAdditionalHosts:
- 9.9.9.9
- 149.112.112.112
- 192.168.0.46
import: "path/to/secret"
```

in the main file, and then import

```yaml
webrtcAdditionalHosts:
- secretipaddress
```

(just an example of possible usage)
