### ISSUE TITLE
is useAbsoluteTimestamp  depricated and removed ?

### ISSUE THREAD

**Issue by midoelhawy** [bluenviron/mediamtx#4625]
### Which version are you using?

docker:latest-ffmpeg

### Which operating system are you using?

Linux amd64 Docker

### Describe how to replicate the issue

Hi,
When I try to add this config to bypass the bad timestamp from a TLC camera:

```yml
pathDefaults:
  useAbsoluteTimestamp: true
```

MediaMTX throws the following error:

```
ERR: json: unknown field "useAbsoluteTimestamp"
```

Is the `useAbsoluteTimestamp` field deprecated or has it been removed?
If so, what is the recommended alternative to handle streams with incorrect or non-monotonic timestamps?

Thanks in advance.

### Server logs

mediamtx_main.1.zvsgao1u11nq@server-name-test   | Starting mediamtx
mediamtx_main.1.zvsgao1u11nq@server-name-test   | ERR: json: unknown field "useAbsoluteTimestamp"

**Comment by dan-nicholls** [comment]
Please double check this is nested in `pathDefaults`. If still having issues please share your `.yml` config

**Comment by midoelhawy** [comment]
Thank you @dan-nicholls for your replay 

The value is returned from the API. I just fetched the streams and generated my `mediamtx` config file.

By default, when I configure a stream via the API, `mediamtx` returns the full default configuration of the stream, including `useAbsoluteTimestamp`.
However, after a reboot, `mediamtx` crashes in a loop with the following error:

```
ERR: json: unknown field "useAbsoluteTimestamp"
```

Here is an example of my `mediamtx` configuration:

```yaml
api: yes
apiAddress: :9997

rtspAddress: :8554
rtspTransports: [tcp, udp]
rtspsAddress: :8322

hlsAddress: :8888
hlsAlwaysRemux: no
hlsSegmentCount: 30
hlsSegmentDuration: 4s
hlsPartDuration: 1s

authInternalUsers:
- user: <uname>
  pass: <pass>
  ips: []
  permissions:
  - action: publish
    path:
  - action: read
    path:

- user: <uname>
  pass: <pass>
  ips: []
  permissions:
  - action: api

paths:
  streams/192.168.1.68/profile1:
    name: streams/192.168.1.68/profile1
    source: rtsp://....@192.168.1.68:554/profile1
    sourceFingerprint: ""
    sourceOnDemand: false
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 10s
    useAbsoluteTimestamp: false
    ...
```

**Note:** In the current version, the `mediamtx` API does not return `useAbsoluteTimestamp` in the stream configuration.

My question is: why?
Was `useAbsoluteTimestamp` deprecated or removed?
