### ISSUE TITLE
HTTP seek not working on recorded stream playback server

### ISSUE THREAD

**Issue by midoelhawy** [bluenviron/mediamtx#4644]
### Which version are you using?

v1.12.3

### Which operating system are you using?

Linux amd64 Docker

## HTTP Seeking Issue with MediaMTX Recorded Streams

Hi,

I'm using MediaMTX to serve recorded streams via the playback server (`/get`), but I'm unable to perform HTTP seeking.

**Example URL:**

```
https://my-domain.example.com/get?duration=4799.132018&path=abc123%2Fvod-recordings%2Fcamera01%2FProfile000&start=2025-06-12T08%3A02%3A25.772371Z&format=mp4
```

I've tried adding the `&format=mp4` parameter, even though the documentation doesn't specify that it enables `Range` support. This made no difference.

**The Problem:**

The server **does not** return the `Accept-Ranges: bytes` header in the response, which prevents video player  from seeking correctly. You can see all headers in the attached image:

-----

## Stream Configuration (Simplified)

```yaml
"abc123/vod-recordings/camera01/Profile000":
  source: rtsp://stream_reader:<password>@192.168.x.x:8554/vod-recordings/camera01/Profile000
  record: true
  recordPath: ./recordings/%path/%Y-%m-%d_%H-%M-%S-%f
  recordFormat: fmp4
  recordPartDuration: 1s
  recordSegmentDuration: 2m0s
  recordDeleteAfter: 1h0m0s
```

-----

This issue specifically affects the **playback server for recorded streams**, not live streaming.

Are there any known limitations preventing HTTP seek support in this context?

Thanks for your great work and support.
