### ISSUE TITLE
rtspAddress doesn't work

### ISSUE THREAD

**Issue by Enaium** [bluenviron/mediamtx#4652]
### Which version are you using?

1.12.3

### Which operating system are you using?

Windows amd64 standard

### Describe how to replicate the issue

```yaml
paths:
  all:
    source: publisher
logLevel: debug
rtspAddress: 0.0.0.0:8554
```

`ffmpeg -re -stream_loop -1 -i .\video.mp4 -c copy -f rtsp rtsp://0.0.0.0:8554/stream`
or
`ffmpeg -re -stream_loop -1 -i .\video.mp4 -c copy -f rtsp rtsp://localhost:8554/stream`

![Image](https://github.com/user-attachments/assets/c1be0d08-9f97-4f0c-a55a-a6e4b9022e82)

---

It's worked fine if I do not use `rtspAddress`

```yaml
paths:
  all:
    source: publisher
logLevel: debug
```

`ffmpeg -re -stream_loop -1 -i .\video.mp4 -c copy -f rtsp rtsp://localhost:8554/stream`

![Image](https://github.com/user-attachments/assets/8177022a-ca73-40b7-9d35-57fc5559a8f9)
