### ISSUE TITLE
Internal auth for "api" and HTTP auth for "read"

### ISSUE THREAD

**Issue by element-code** [bluenviron/mediamtx#4659]
### Which version are you using?

1.12.3

### Which operating system are you using?

Linux amd64 Docker

### Describe how to replicate the issue

I configured http auth for reading streams and expected internal user auth for "auth http exclude" actions.
It seems to be that those actions are not authenticated in any way.
Is there a method to authenticate (publish, api, pprof, etc. )actions via internal user auth while authenticating (read) via http?

```yml
###############################################
# Global settings -> Authentication

authMethod: http

authInternalUsers:
  - user: any
    ips: []
    permissions: []

  - user: any
    pass:
    ips: ['127.0.0.1', '::1']
    permissions:
      - action: publish

  - user: admin
    pass: "foobar"
    permissions:
      - action: api
      - action: metrics
      - action: pprof

authHTTPAddress: "<HTTP_AUTH_ENDPOINT>"
authHTTPExclude:
  - action: publish
  - action: api
  - action: metrics
  - action: pprof

```

Log:
```log
WAR parameter 'protocols' is deprecated and has been replaced with 'rtspTransports'
WAR parameter 'encryption' is deprecated and has been replaced with 'rtspEncryption'
WAR parameter 'serverCert' is deprecated and has been replaced with 'rtspServerCert'
WAR parameter 'serverKey' is deprecated and has been replaced with 'rtspServerKey'
INF MediaMTX v1.12.3
INF configuration loaded from /mediamtx.yml
DEB [path initialize] created
DEB path manager created
INF [path initialize] runOnInit command started
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
INF [RTSP] listener opened on :8554 (TCP)
INF [RTSPS] listener opened on :8322 (TCP)
INF [RTMP] listener opened on :1935
INF [RTMPS] listener opened on :1936
INF [HLS] listener opened on :8888
INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
INF [SRT] listener opened on :8890 (UDP)
INF [API] listener opened on :9997

DEB [API] [conn <SRC_IP>:56652] [c->s] GET /v3/config/paths/list HTTP/2.0
Host: <HOSTNAME>:9997
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: de,en-US;q=0.7,en;q=0.3
Cookie: _ga=<REDACTED>; _ga_560JN0LPM0=<REDACTED>; _fbp=<REDACTED>; wfx_unq=<REDACTED>; _gcl_au=<REDACTED>
Priority: u=0, i
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Te: trailers
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0


DEB [API] [conn <SRC_IP>:56652] [s->c] HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Server: mediamtx

(body of 6187 bytes)



DEB [API] [conn <SRC_IP>:56653] [c->s] GET /favicon.ico HTTP/2.0
Host: <HOSTNAME>:9997
Accept: image/avif,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: de,en-US;q=0.7,en;q=0.3
Priority: u=6
Referer: https://<HOSTNAME>:9997/v3/config/paths/list
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: cross-site
Te: trailers
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0


DEB [API] [conn <SRC_IP>:56653] [s->c] HTTP/1.1 404 Not Found
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: text/plain
Server: mediamtx

(body of 18 bytes)
```
