### ISSUE TITLE
Regexp-based proxy

### ISSUE THREAD

**Issue by MayeulC** [bluenviron/mediamtx#824]
## Describe the feature

Building on #54 it would be nice to be able to automatically build a proxy rule:

```yaml
paths:
    '~proxy/(.+)':
        source: '~rtsp://upstream.example.com/feed/\1'
        sourceAnyPortEnable: yes
        sourceOnDemand: yes
```
I'm using a capture group in the example above, I'm not quite sure how yaml handles `\` escapes characters, but that should be fine before a number.
An alternative for me is to generate a configuration file with all the possible paths, but that's a lot less flexible.

Of course, there might be some security considerations (XSS/CSRF-class, as well as "SQL injection"-like).

**Comment by Warr1024** [comment]
I would very much like to have the ability to match paths on any kind of wildcard, including lua patterns or even simple shell globbing.  The ability to use references from the regex, like the `\1` in the example, would be _nice to have_, but even without that feature, we could get a lot of mileage out of this feature.  Just being able to match on `proxy/*`, we could use a runOnDemand command to parse the path and pipe in the necessary source.

**Comment by valkuc** [comment]
@Warr1024 @aler9 Sorry, I did not get, did you able to resolve this? When I'm trying to use regexp in the proxy (similarly to your example), I'm getting `ERR: a path with a regular expression (or path 'all') cannot have a RTSP source; use another path`.
For me it would be helpful to pass different IpCam streams/channels using single path mapping.

For example. My camera can publish two streams:
`rtsp://cameraip/stream0` and `rtsp://cameraip/stream1`
It would be super to have possiblility to create a proxy mapping like `/cam/{streamId}` and then use path variable in source URL like rtsp://cameraip/stream${streamId}

**Comment by valkuc** [comment]
UPDATE:
Another idea is to allow wildcard at the end of the proxy path.
Example:
```
paths:
    '/cam/*':
        source: rtsp://cameraip/
```
In this case all that supplied in input URL will be appended to the source URL: `/cam/stream0` --> `rtsp://cameraip/stream0`

**Comment by wiryonolau** [comment]
Hi, Just want to clarify Is this currently not possible on the latest version ?

```yml
paths:
    "~^siteA-([0-9]{1})$":
        source: rtsp://siteAPIP/cam/realmonitor?channel=$G1                                                                     
        sourceOnDemand: yes
```

**Comment by MayeulC** [comment]
> Hi, Just want to clarify Is this currently not possible on the latest version ?
> 
> ```yaml
> paths:
>     "~^siteA-([0-9]{1})$":
>         source: rtsp://siteAPIP/cam/realmonitor?channel=$G1                                                                     
>         sourceOnDemand: yes
> ```

You had my hopes up for a moment. I tried a variant of your example, and ended up with:

> ERR: a path with a regular expression (or path 'all') cannot have a RTSP source. use another path

**Comment by wiryonolau** [comment]
Yep it happen to me too. I try using runOnInit but it's also not working. The documentation in the config is not clear btw.

Currently I write all the camera one by one, almost 200 and growing :D.

**Comment by pikachu937** [comment]
> Yep it happen to me too. I try using runOnInit but it's also not working. The documentation in the config is not clear btw.
> 
> Currently I write all the camera one by one, almost 200 and growing :D.

i have over 1570 streams and i dont see finish... please developed... need it like air...
```yaml
paths:
    "~^([0-9]{20}|[0-9][0-9][5])$":
        source: rtsp://site_or_ip:port/~^([0-9]{20})$                                                                     
        sourceProtocol: tcp
```
