### ISSUE TITLE
I hope it can add a command option of "--no-console" to launch just like syncthing.exe

### ISSUE THREAD

**Issue by iesv** [bluenviron/mediamtx#872]
## Describe the feature

I hope it can add a command option of "--no-console" to launch just like syncthing.exe

**Comment by aler9** [comment]
Since some versions it's possible to set the verbosity and destination of logs through:

```yml
# Verbosity of the program; available values are "error", "warn", "info", "debug".
logLevel: info
# Destinations of log messages; available values are "stdout", "file" and "syslog".
logDestinations: [stdout]
# If "file" is in logDestinations, this is the file which will receive the logs.
logFile: mediamtx.log
```

Therefore, a `--no-console` equivalent for Windows is:

```
set MTX_LOGLEVEL=error && ./mediamtx.exe
```
